/**
 * Adds first-5-lesson skeletons for the 4 secondary paths.
 * Run from mobile/ folder: node scripts/append_paths_lessons.js
 */
const fs = require('fs');
const path = require('path');

const ADD_TR = {
  'silent-morning': {
    1: { title: 'Erken Kalkmanın Anahtarı: Erken Yat', teaching: 'Erken kalkmanın sırrı sabahın saati değil, gecenin saati. Yatma saatini erkeneye çekmeden, erken kalkma sürdürülemez.\n\nMelatonin döngüsü 22:00–06:00 arası optimumdur. Bu pencerede uyumayan beyin derin uyku evrelerini eksik yaşar — sabah yorgun uyanmanın ana sebebi.\n\nBugün denklemi tersinden başlatıyorsun: erken yat, erken kalk. 21:30 yatış hedefiyle başla.', action: 'Bu gece 21:30 yatağa gir. Telefonu yatak odasının dışına bırak. 22:00 uyumaya çalış.', reflectionPrompt: 'Erken yatmaya direnç gösteren ne oldu — beyninde hangi ses biraz daha dedi?' },
    2: { title: 'Alarmı Telefonsuz Yap', teaching: 'Alarm = telefon = scroll = günün başı zaten kaybedilmiş. Alarm fonksiyonunu telefondan ayırmak zihinsel sınır kurmaktır.\n\nFiziksel bir alarm saati al. Telefonu odanın dışında bırak. Sabah ilk dokunduğun şey alarm butonu olsun, ekran değil.', action: 'Bugün fiziksel bir alarm saati al ya da sipariş et. Yatmadan önce telefonu odanın dışına bırak.', reflectionPrompt: 'Alarm butonu yerine ekran açma alışkanlığını ne kadar zor değiştireceğini düşünüyorsun?' },
    3: { title: 'Su, Yüz, Pencere', teaching: 'Uyandığında üç eylem zinciri kur: bir bardak su iç, yüzünü yıka, pencereyi aç (veya dışarı çık 1 dakika).\n\nSu — gece dehidrasyonunu kırar, beyin uyandırır. Yüzünü yıkamak — soğuk şok parasempatik moddan çıkarır. Doğal ışık — sirkadiyen ritim sıfırlanır.\n\nBu 3 dakikalık zincir, sabahı eskisinden 10x daha berrak yapar.', action: 'Yarın bu zinciri uygula. Uyanır uyanmaz: su iç → yüzünü yıka → pencereye yaklaş. Telefonsuz.', reflectionPrompt: 'Üçlü zincirden sonra, eski sabahlara göre nasıl hissettin?' },
    4: { title: 'Sabah Sessizliği', teaching: 'Çoğu kişi sabahı bir gürültü banyosuna çevirir: bildirimler, haberler, podcast, telefon konuşması. Beyin, gün başlamadan tükenir.\n\nSessizlik bir lüks değil — temel ihtiyaç. İlk 60 dakikayı sessiz geçirmek, gün boyu daha az reaktif kılar.\n\nSessizlik hiçbir şey yapmamak değil. Düşünmek için yer açmak.', action: 'Yarın ilk 60 dakikayı sessiz geçir: müzik yok, podcast yok, ses yok. Sadece sabah rutini ve düşünme.', reflectionPrompt: 'Sessiz sabah seni daha mı yorgun yaptı, yoksa daha mı dingin?' },
    5: { title: 'Sabah 5 Dakikalık Niyet', teaching: 'Çoğu kişi gününü reaktif başlar: e-posta, WhatsApp, bildirimler. Niyet ettiğin değil, sana gelen şeylere tepki verirsin.\n\n5 dakikalık niyet değiştirir bunu. Bir defter al. Üç soru: (1) Bugünün ana önceliği ne? (2) Hangi alışkanlıkları sürdüreceğim? (3) Akşam neye gurur duyacağım?\n\nBu 5 dakika, günün geri kalanını şekillendirir.', action: 'Yarın sabah 5 dakika niyet pratiği yap. Bir kalem ve kağıt al, üç soruya yaz.', reflectionPrompt: 'Niyet yazılı olunca, gün boyu kararlarını etkiledi mi?' },
  },
  'mind-discipline': {
    1: { title: 'Tek Odak Kuralı', teaching: 'Beyin tek görev yapacak şekilde evrimleşmiş. Multitasking bir illüzyon — beyin sadece hızlı geçiş yapar, performans her geçişte düşer.\n\nDeep work tek odak demektir. Tek pencere, tek ses, tek niyet. Bu antrenman gerektirir — ilk gün 25 dakika zor, bir hafta sonra 90 dakika doğal.\n\nZihinsel kas. Geliştirilebilir. Bugün başlıyorsun.', action: 'Bugün 25 dakika tek görev bloku yap (Pomodoro). Telefon başka odada. Bilgisayarda sadece o iş için açık sekme.', reflectionPrompt: '25 dakika sonra zihnin yorgun mu, daha mı net?' },
    2: { title: 'Distraction Kill List', teaching: 'Dikkat dağıtıcılar görünmeyen düşmanlar. Her gün isimlerini listele: hangi uygulamalar, hangi kişiler, hangi düşünceler dikkatini bölüyor?\n\nListele = farkına var. Farkına vardığın şey gücünü kaybeder.\n\nBugün listene bakacak ve her dikkat dağıtıcı için bir savunma kuracaksın.', action: '5 dakikada bir liste yap: Bugün dikkatini bölen 5 şey ne? Her biri için bir savunma yaz.', reflectionPrompt: 'Listenin en şaşırtıcı maddesi hangisiydi?' },
    3: { title: 'Deep Work Bloku', teaching: 'Cal Newport: deep work = deep value. Yüzeysel iş kolayca yapılır, kolayca taklit edilir, az değer üretir. Derin iş zor, nadir, çok değerli.\n\nGünde 90 dakika gerçek deep work, 8 saatlik sığ işten 10x daha değerli sonuç verir.\n\nBu seviyeye ulaşmak için kademeli antrenman gerekir.', action: 'Bugün 90 dakikalık tek görev bloku yap (Pomodoro değil — 90 dakika kesintisiz).', reflectionPrompt: '90 dakikadan sonra bitirdiğin iş, sığ modunda kaç saatte biterdi?' },
    4: { title: 'Sabah Kuralı: Önemli İlk', teaching: 'Sabah istem gücün en yüksek. Akşam tükenmiş. Önemli işi sabaha al.\n\nSabah ilk 90 dakika = günün altın penceresi. Bu pencerede sığ iş yapmak (e-posta, WhatsApp) suç.\n\nÖncelik kuralı: günün en zorlu, en derin işi → ilk yapılır. Diğer her şey bekleyebilir.', action: 'Yarın gününün en zor işini sabah 9–10:30 arasında yap. E-posta hayır. WhatsApp hayır. Sadece o iş.', reflectionPrompt: 'Sabah ilk 90 dk derin işle başladığında, gün geri kalanı nasıl gitti?' },
    5: { title: 'Telefon Aralık Kuralı', teaching: 'Telefonun sürekli açık olması = sürekli kesinti. Çalıştığın 8 saatte 50 kez bakıyorsan, 50 mikro-kesinti yaşıyor demektir.\n\nTelefon aralık kuralı: günde 2–3 belirlenmiş zaman dışında telefonu kapalı tut. Diğer zamanlar uçak modu.\n\nİlk hafta zor olur. İkinci hafta normalleşir.', action: 'Bugün telefon aralık kuralını dene: 12:00, 17:00 ve 20:00 15 dakikalık kontrol. Diğer her zaman uçak modu.', reflectionPrompt: 'Uçak modunda kaç kez telefon istedi? Hangi anda?' },
  },
  'body-discipline': {
    1: { title: 'Hareket Eşiği', teaching: 'Modern hayat hareketsiz. 8 saat oturma kafanı kaplayan bulanıklığın ana sebebi. Kan akışı yavaşlıyor, beyin az oksijen alıyor, motivasyon düşüyor.\n\nÇözüm karmaşık değil: günde 30 dakika hareket. Yürüyüş, basit egzersiz, koşu — fark etmez. Önemli olan kan akışını arttırmak.\n\nGyme ihtiyaç yok. Bedeninle başla.', action: 'Bugün 30 dakika tempolu yürüyüş yap. Sıkışık zaman varsa öğle aralağında 10 dk, akşam 20 dk böl.', reflectionPrompt: 'Yürüyüş sonrası zihinsel berraklık hissettin mi?' },
    2: { title: 'Soğuk Duş Protokolü', teaching: 'Soğuk şok = sempatik sinir sistemi aktivasyonu = adrenalin + dopamin = berrak zihin.\n\nWim Hof bilimi: soğuk maruziyet bağışıklık sistemini güçlendiriyor, depresyon belirtilerini azaltıyor, motivasyonu arttırıyor.\n\nİlk gün dayanılmaz. 7. gün rutine girer. 30. gün özlersin.', action: 'Bugün duşun sonunda 30 saniye soğuk suyla bitir. Sıcaktan soğuğa geçiş — mücadele et.', reflectionPrompt: 'Soğuk duştan sonra ilk dakikada ne hissettin?' },
    3: { title: 'Beslenmenin Temeli: Protein', teaching: 'Beden proteinden inşa olur. Yetersiz protein = düşük enerji, düşük doku onarımı, düşük doygunluk.\n\nKural: vücut ağırlığının her kilogramı için 1g protein. 70 kg kişi için 70g/gün.\n\nKaynak: et, balık, yumurta, baklagiller, süt ürünleri. Atıştırmalık değil — öğün.', action: 'Bugün her öğüne protein kaynağı ekle. Akşam toplam protein gramını hesapla.', reflectionPrompt: 'Yeterli protein aldığında enerjin nasıldı?' },
    4: { title: 'Şeker Kesme', teaching: 'İşlenmiş şeker dopamin sömürüsünün en eski formu. Kan şekeri yükselir, çakılır, krash yaşarsın. Yorgunluk → daha şeker → döngü.\n\n7 günlük şeker kesme: net berraklaşma, kararlı enerji, uyku kalitesi artışı, kilo kaybı.\n\nBağımlılık 7 günde kırılır. Ondan sonra şeker tatsızlaşır.', action: 'Bugün hiç işlenmiş şeker yeme. Tatlılar, gazlı içecekler, paketli atıştırmalıklar — hiçbiri. Doğal meyve OK.', reflectionPrompt: 'Öğleden sonra şeker krizi hissettin mi? Ne yaptın?' },
    5: { title: 'Uyku Sertliği', teaching: 'Uyku kalitesi tüm disiplinin temeli. Kötü uyumuş bir adam disiplinsizlik için optimize edilmiş. Karar verme zayıflar, irade pili düşük.\n\nUyku sertliği: 7-8 saat, 22:00 önce yatış, karanlık oda, serin sıcaklık (18-20°C).\n\nBu pazarlık edilmez. Hayatının her başka tarafı buna bağlı.', action: 'Bugün uyku odanı sertleştir: perdeleri kapat, sıcaklığı 19°C ye al, telefon dışarıda. 22:30 yatış.', reflectionPrompt: 'Sert uyku ortamında uykuya dalış süresinde değişim oldu mu?' },
  },
  'money-discipline': {
    1: { title: 'Görünmez Harcama Tehlikesi', teaching: 'En tehlikeli harcamalar görünmez olanlar: aboneliğe giren, otomatik çekilen, küçük olan ama biriken.\n\nHerkesin 5–15 unutulmuş aboneliği var. Yıllık binlerce TL kayıp. Hiç fark edilmeden.\n\nBugün görünmezi görünür yapacağız.', action: 'Banka hesap özetinden son 3 ayı geç. Her abonelik/tekrarlanan ödemeyi listele. Kullanmadıklarını şu an iptal et.', reflectionPrompt: 'Kaç abonelik bulundun? Yıllık ne kadar paraydı?' },
    2: { title: 'Bütçe = Özgürlük', teaching: 'Çoğu kişi bütçe kelimesinden kısıtlama anlar. Ama gerçekte bütçe = özgürlük.\n\nBilmediğin şeyi kontrol edemezsin. Ne kazandığını ve ne harcadığını net bilmek = paranı yönetmek.\n\n50/30/20 kuralı: gelirinin %50si zorunlu, %30u istediklerin, %20si tasarruf/yatırım. Sadelik var.', action: 'Bugün bir tablo aç. Aylık gelirini yaz. 50/30/20 kategorilerine böl. Gerçek harcamalarını karşılaştır.', reflectionPrompt: 'Hangi kategori sınırı aştı?' },
    3: { title: '24-Saat Bekleme Kuralı', teaching: 'Anlık satın alma dürtüsü = dopamin, gerçek ihtiyaç değil. 24 saat bekledikten sonra %80inin gerekli olmadığını fark edersin.\n\nKural: 100 TL üstü her satın alma, sepete koy ama 24 saat bekle. Hala istiyor musun? Al. Unuttuysan, unutman gereken bir şeydi.\n\nBu basit kural yıllık binlerce TL kurtarır.', action: 'Bugünden başlayarak 100 TL üstü her satın almayı 24 saat ertele. Bir bekleme listesi tut.', reflectionPrompt: 'Bugün ertelediğin neydi? 24 saat sonra hala istedin mi?' },
    4: { title: 'Yemek Maliyeti Görünümü', teaching: 'Dışarıda yemek vs evde pişirmek 5–10x maliyet farkı yaratır. Çoğu kişi bunu görmüyor çünkü küçük harcamalar.\n\n200 TL bir öğün × günde 3 öğün × ayda 30 = 18,000 TL/ay. Aynı yemekleri evde 60 TL ye yapabilirsin.\n\nDışarıda yemek tatil deneyimi olmalı, günlük rutin değil.', action: 'Bugün 1 öğünü evde pişir. Maliyetini hesapla, dışarıda aynı yemeğin maliyetiyle karşılaştır.', reflectionPrompt: 'Evde pişirmek ne kadar tasarruf etti? Tatlı miydi?' },
    5: { title: 'Acil Durum Fonu', teaching: 'Mali stres → kötü kararlar. Yatırımları erken sat, kredi al, ucuz işlere razı ol. Hepsi pahalı hatalar.\n\nAcil durum fonu = 3 aylık zorunlu giderlerin. İşsizlik, sağlık, beklenmedik durum için.\n\nBu fon olmadan finansal disiplin yapay. Gerçek temel bu.', action: 'Bugün ayrı bir hesap aç (faizli mevduat OK). Maaşının %10unu o hesaba transfer et. Bu fon büyüyene kadar dokunma.', reflectionPrompt: '%10 transfer hangi alandan kesilecek?' },
  },
};

const ADD_EN = {
  'silent-morning': {
    1: { title: 'The Key to Waking Early: Sleep Early', teaching: 'The secret of waking early is not the morning hour, it is the night hour. Without bringing bedtime earlier, waking early is not sustainable.\n\nThe melatonin cycle is optimal between 22:00 and 06:00. Brains that do not sleep in this window miss deep sleep stages, the main reason for tired mornings.\n\nToday you reverse the equation: sleep early, wake early. Start with a 21:30 bedtime goal.', action: 'Tonight, get in bed by 21:30. Leave the phone outside the bedroom. Try to sleep by 22:00.', reflectionPrompt: 'What resisted sleeping early?' },
    2: { title: 'Phoneless Alarm', teaching: 'Alarm = phone = scroll = the day already lost. Separating the alarm function from the phone is creating a mental boundary.\n\nGet a physical alarm clock. Leave the phone outside the room. The first thing your hand touches in the morning should be the alarm button, not a screen.', action: 'Buy or order a physical alarm clock today. Leave the phone outside the room before bed.', reflectionPrompt: 'How hard will it be to switch from screen-on to alarm-button?' },
    3: { title: 'Water, Face, Window', teaching: 'When you wake, build a 3-step chain: drink a glass of water, wash your face, open a window or step outside for 1 minute.\n\nWater breaks overnight dehydration. Face wash pulls you out of parasympathetic. Natural light resets circadian rhythm.\n\nThis 3-minute chain makes mornings 10x clearer than before.', action: 'Tomorrow apply this chain. Right after waking: water then face then window. Phoneless.', reflectionPrompt: 'How did you feel after the triple chain?' },
    4: { title: 'Morning Silence', teaching: 'Most people turn morning into a noise bath: notifications, news, podcasts, calls. The brain is exhausted before the day starts.\n\nSilence is not a luxury, it is a basic need. Spending the first 60 minutes silent makes you less reactive all day.\n\nSilence is not doing nothing. It is making space to think.', action: 'Tomorrow spend the first 60 minutes silent: no music, no podcasts, no sound.', reflectionPrompt: 'Did silent morning make you more tired or more calm?' },
    5: { title: '5-Minute Morning Intent', teaching: 'Most start the day reactive: email, WhatsApp, notifications. You react to what comes to you, not what you intended.\n\n5 minutes of intent changes this. Three questions: (1) Today is main priority? (2) Which habits will I sustain? (3) What will I be proud of tonight?\n\nThese 5 minutes shape the rest of the day.', action: 'Practice morning intent for 5 minutes tomorrow. Pen and paper, answer the three questions.', reflectionPrompt: 'Did written intent influence your decisions throughout the day?' },
  },
  'mind-discipline': {
    1: { title: 'Single-Focus Rule', teaching: 'The brain evolved to do one task at a time. Multitasking is an illusion: the brain just switches fast and performance drops at every switch.\n\nDeep work means single focus. One window, one sound, one intent. This requires training.\n\nMental muscle. Trainable. You start today.', action: 'Do one 25-minute single-focus block (Pomodoro) today. Phone in another room. Only relevant tab open.', reflectionPrompt: 'After 25 minutes was your mind tired or clearer?' },
    2: { title: 'Distraction Kill List', teaching: 'Distractions are invisible enemies. Every day list their names: which apps, which people, which thoughts split your attention?\n\nList means notice. What you notice loses its power.\n\nToday look at the list and build a defense for each.', action: 'In 5 minutes list 5 things that split your attention today. For each write a defense.', reflectionPrompt: 'What was the most surprising item on the list?' },
    3: { title: 'Deep Work Block', teaching: 'Cal Newport: deep work = deep value. Shallow work is easily replicated, produces little value. Deep work is hard, rare, very valuable.\n\n90 minutes of true deep work per day produces 10x more output than 8 hours of shallow.\n\nReaching this requires gradual training.', action: 'Do one 90-minute single-task block today. 90 min uninterrupted.', reflectionPrompt: 'How long would the same task have taken in shallow mode?' },
    4: { title: 'Morning Rule: Important First', teaching: 'Willpower is highest in the morning. By night you are depleted. Move important work to morning.\n\nFirst 90 minutes is the day golden window. Doing shallow work in this window is a crime.\n\nPriority rule: hardest task first. Everything else can wait.', action: 'Tomorrow do your hardest task between 9:00 and 10:30. No email or WhatsApp.', reflectionPrompt: 'When you started with deep work first, how did the rest of the day go?' },
    5: { title: 'Phone Interval Rule', teaching: 'A phone always on means constant interruption. If you check 50 times in 8 work hours, you have 50 micro-interruptions.\n\nPhone interval rule: keep the phone off outside 2 to 3 designated times per day. Other times: airplane mode.\n\nFirst week is hard. Second week normalizes.', action: 'Try the interval rule today: 12:00, 17:00, 20:00 — 15-minute checks. Airplane mode all other times.', reflectionPrompt: 'How many times did the phone want you in airplane mode?' },
  },
  'body-discipline': {
    1: { title: 'Movement Threshold', teaching: 'Modern life is sedentary. 8 hours of sitting is the main reason for the fog over your head. Blood flow slows, brain gets less oxygen, motivation drops.\n\nSolution is not complex: 30 minutes of movement daily. What matters is increasing blood flow.\n\nNo gym needed. Start with your body.', action: 'Take a 30-minute brisk walk today.', reflectionPrompt: 'Did you feel mental clarity after the walk?' },
    2: { title: 'Cold Shower Protocol', teaching: 'Cold shock = sympathetic activation = adrenaline + dopamine = clear mind.\n\nWim Hof science: cold exposure strengthens immunity, reduces depression, increases motivation.\n\nDay 1 unbearable. Day 7 routine. Day 30 you miss it.', action: 'End your shower with 30 seconds of cold water today.', reflectionPrompt: 'What did you feel in the first minute after?' },
    3: { title: 'Nutrition Foundation: Protein', teaching: 'The body is built from protein. Insufficient protein = low energy, slow tissue repair, low satiety.\n\nRule: 1g of protein per kilogram of body weight.\n\nSources: meat, fish, eggs, legumes, dairy.', action: 'Add a protein source to every meal today. Calculate total protein grams in the evening.', reflectionPrompt: 'How was your energy when you got enough protein?' },
    4: { title: 'Cut Sugar', teaching: 'Processed sugar is the oldest form of dopamine exploitation. Spike, crash, fatigue, more sugar — the loop.\n\n7-day sugar cut: clear thinking, stable energy, better sleep, weight loss.\n\nThe addiction breaks in 7 days.', action: 'Today eat zero processed sugar. Sweets, sodas, packaged snacks — none. Natural fruit OK.', reflectionPrompt: 'Did you feel an afternoon sugar crash?' },
    5: { title: 'Sleep Hardness', teaching: 'Sleep quality is the foundation of all discipline. Decision-making weakens, willpower battery low.\n\nSleep hardness: 7–8 hours, sleep before 22:00, dark room, cool 18–20°C.\n\nNon-negotiable. Every other part of your life depends on it.', action: 'Today harden your sleep environment. Lights out by 22:30.', reflectionPrompt: 'Did your time-to-sleep change?' },
  },
  'money-discipline': {
    1: { title: 'Invisible Spending Danger', teaching: 'Most dangerous spending is invisible: subscriptions, auto-debits, small but accumulating.\n\nEveryone has 5–15 forgotten subscriptions. Thousands lost annually.\n\nToday we make the invisible visible.', action: 'Go through last 3 months of bank statements. List every subscription. Cancel ones you do not use.', reflectionPrompt: 'How many subscriptions? Annual cost?' },
    2: { title: 'Budget = Freedom', teaching: 'Most hear budget as restriction. Really, budget = freedom.\n\nYou cannot control what you do not know.\n\n50/30/20 rule: 50% essentials, 30% wants, 20% savings.', action: 'Open a sheet. Write monthly income. Split into 50/30/20. Compare against actual.', reflectionPrompt: 'Which category went over its limit?' },
    3: { title: '24-Hour Wait Rule', teaching: 'Impulse buying = dopamine, not real need. After 24 hours, you realize 80% was not necessary.\n\nRule: any purchase over $10 — wait 24 hours.\n\nThis simple rule saves thousands annually.', action: 'Postpone every $10+ purchase by 24 hours. Keep a waiting list.', reflectionPrompt: 'What did you postpone today?' },
    4: { title: 'Food Cost Visibility', teaching: 'Eating out vs cooking is a 5–10x cost difference. Most do not see it.\n\nEating out should be a vacation experience, not daily routine.', action: 'Cook one meal at home today. Calculate cost.', reflectionPrompt: 'How much did cooking save?' },
    5: { title: 'Emergency Fund', teaching: 'Financial stress leads to bad decisions.\n\nEmergency fund = 3 months of essential expenses.\n\nWithout this fund, financial discipline is artificial.', action: 'Open a separate account. Transfer 10% of your salary.', reflectionPrompt: 'Where will the 10% come from?' },
  },
};

const update = (lang, additions) => {
  const filePath = path.join(__dirname, '..', 'src', 'i18n', 'locales', `lessons.${lang}.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  Object.entries(additions).forEach(([pathId, lessons]) => {
    data.lessons[pathId] = lessons;
  });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
  console.log(`Updated ${filePath}`);
};

update('tr', ADD_TR);
update('en', ADD_EN);
