/**
 * Seed body-discipline lessons 6-30 (25 new) + add proTip to 1-5.
 * Run: node scripts/seed_body_discipline.js
 */
const fs = require('fs');
const path = require('path');

const PROTIPS_TR = {
  1: 'Hareket eşiğine dolaşırsan kahve ya da çay alırken ekstra adım at. Bu sezgisel olarak günlüğe eklenir.',
  2: 'Soğuk duşa nefes verince başla. İçeride tutarsan beden gerilir, ver ki rahatlasın.',
  3: 'Protein her öğüne. 20-30g/öğün × 3 öğün = günlük 60-90g optimum.',
  4: 'Şeker özlemini su + 1 tatlı meyve (elma) ile karşıla. 7 gün sonra özlem kırılır.',
  5: 'Yatak odası 18-20°C, karanlık, sessiz. 3 koşul = derin uyku garantisi.',
};
const PROTIPS_EN = {
  1: 'Add extra steps fetching coffee/tea — small additions compound to your daily threshold.',
  2: 'Start cold shower on the exhale. Holding breath tenses you; release it to relax.',
  3: 'Protein every meal. 20-30g/meal × 3 meals = daily 60-90g optimum.',
  4: 'Replace sugar craving with water + 1 sweet fruit (apple). After 7 days the craving breaks.',
  5: 'Bedroom 18-20°C, dark, silent. 3 conditions = deep sleep guarantee.',
};

const NEW_TR = {
  6: { title: 'Yatma Saati: 22:00', teaching: 'Sirkadiyen ritm sabit yatış saatiyle güçlenir. 22:00 = melatonin doğal zirvesi. Hafta içi-sonu fark etmez. Yatış saati esnek olunca uyku kalitesi %40 düşer (Matthew Walker araştırması).', action: 'Bugün gece 22:00\'da yatakta ol. Telefon başka odada.', reflectionPrompt: '22:00\'da yatağa geçmek dünden ne kadar farklı?', proTip: '21:00\'dan sonra mavi ışık filtre + sarı renk gece lambası. Beden saat 22\'ye hazırlanır.' },
  7: { title: 'Hidrasyon: 2 Litre', teaching: 'Vücudun %60\'ı su. %2 dehidratasyon = bilişsel performansta %20 düşüş. Çoğu insan kronik dehidre. Çözüm: 2 litre = ~8 bardak. Sabah, öğleden önce, öğleden sonra 0.5L\'lik bloklar.', action: 'Bugün 2 litre su iç. 1L sabah, 1L öğleden sonra. Şişe görünür yere koy.', reflectionPrompt: 'Bedeninde tam hidrasyonun farkını ne zaman hissettin?', proTip: 'Sabah ilk içecek su. Hidrasyon kahveden 90 dk önce başlar.' },
  8: { title: 'Günde 10.000 Adım', teaching: 'Adım sayma modaymış gibi görünür ama bilim katı: günde 7-10K adım = %30 daha düşük ölüm riski (Lancet 2023). Sürekli oturma kanserle eş tehlikeli. Hareket = ilaç.', action: 'Bugün 10.000 adıma ulaş. Telefonda sayar var.', reflectionPrompt: '10K adıma ulaşmak gününü nasıl yapılandırdı?', proTip: 'Toplantıyı yürüyerek yap. Telefonla konuşurken yürü. Asansör yerine merdiven.' },
  9: { title: 'Direnç Antrenmanına Giriş', teaching: 'Kardiyo iyi, ama direnç antrenmanı (ağırlık, vücut ağırlığı) %30 daha çok ömür ekler. Kas = ikinci kalp. 30+ yaşta kas kaybı her yıl %1 — antrenmansız 50\'sinde dimdik durmazsın.', action: 'Bugün 3 temel hareketi 3 set yap: squat, push-up, plank. 10 tekrar each.', reflectionPrompt: 'Direnç antrenmanı sonrası enerjin nasıldı?', proTip: 'Hafta 3 gün yeterli. Pazartesi-çarşamba-cuma 20 dakika ev egzersizi.' },
  10: { title: 'Günlük Push-Up', teaching: 'Tek hareket = ömrün artar. Çinli araştırma: 40+ erkekler 40\'tan fazla push-up yapabilenlerin kalp hastalığı riski %96 daha düşük. Bedel: 5 dakika.', action: 'Bugün 20 push-up yap. Tek serisinde değilse bile, gün sonu toplam 20.', reflectionPrompt: 'Push-up sayını günlük artırmak ne kadar zor?', proTip: 'Diş fırçaladıktan sonra 5 push-up. Dişle yığma = 100 günde 500 push-up.' },
  11: { title: 'Günlük Squat', teaching: 'Squat = tüm vücut hareketi. Kuadriseps, glutes, kor, denge. 50 yaşında zorlanmadan oturup kalkmak istiyorsan, 30\'da squat yap. Eklem dostu, ekipmansız, etkili.', action: 'Bugün 30 squat yap. Set bölersen 3x10. Form > sayı.', reflectionPrompt: 'Squat formuna dikkat etmek nasıldı?', proTip: 'Kalçayı geriye it, dizler ayak parmağı hizasını geçmesin. Aynaya bak ya da videoya çek.' },
  12: { title: 'Plank Disiplini', teaching: 'Kor güçsüzse her hareket sızdırır. Plank = pasif kor antrenmanı. 60 saniye plank = 100 sit-up\'tan etkili. Sırt ağrısının %80\'i zayıf kor.', action: 'Bugün 30 saniye plank yap. Yarın 35, ertesi gün 40. 60\'a ulaşana dek artır.', reflectionPrompt: 'Plank tutmaya çalışırken zihninde ne oldu?', proTip: 'Nefes verme. Yanlış: nefes tut. Doğru: yavaş nefes ver, kor aktif kalır.' },
  13: { title: 'Kardiyo Bölgeleri', teaching: 'Tüm kardiyo aynı değil. Zone 2 (orta yoğunluk, konuşabildiğin tempoda) = mitokondri çoğalması, yağ yakımı, dayanıklılık. Zone 5 (sprint) = anlık güç. Çoğu insan zone 3-4\'te takılır — etkisiz orta bölge.', action: 'Bugün 30 dakika zone 2 kardiyo yap. Yürüyüş tempolu / hafif jog. Konuşabildiğin yoğunluk.', reflectionPrompt: 'Zone 2 ne kadar yavaş geldi?', proTip: 'Apple Watch ya da Garmin\'de zone monitor var. Yoksa: konuşabiliyorsan zone 2.' },
  14: { title: 'Mobilite Çalışması', teaching: 'Esneklik ≠ mobilite. Esneklik pasif uzanma. Mobilite kontrollü hareket aralığı. 30+ yaşta her gün omuz/kalça/ayak bilek mobilitesi yapmazsan, 50\'de hareket kısıtlanır.', action: 'Bugün 5 dakika mobilite yap. Kol daireleri, kalça açılışı, ayak bileği rotasyonu.', reflectionPrompt: 'Hangi eklem en kısıtlı geldi?', proTip: 'Sabah duştan sonra yap. Kaslar ısınmış, mobilite optimum.' },
  15: { title: 'Öğün Zamanlaması', teaching: 'Ne yediğin önemli, ama ne zaman yediğin de. Geç gece yemek = uyku kalitesi düşüşü, sindirim yavaşlığı. Son öğün yatmadan 3 saat önce. 19:00 yatma 22:00 = ideal.', action: 'Bugün son öğünü 19:00\'dan sonraya bırakma.', reflectionPrompt: 'Erken son öğün uykuna nasıl etki etti?', proTip: 'Erken yiyorsan akşam atıştırma riski düşer. Aç yatma — ağzın doluyken yatma arasını bul.' },
  16: { title: 'Şekersiz Gün', teaching: 'Şeker = bağımlılık molekülü. Beyin ödül merkezini hijack eder. 1 günlük şekersiz challenge: meyveden gelen doğal şeker hariç. Çikolata, kek, gazlı içecek, paketli ürün yok.', action: 'Bugün hiç işlenmiş şeker tüketme.', reflectionPrompt: 'Şekersiz günde hangi anda en çok özledin?', proTip: 'İlk 3 gün zor, 4. günden sonra özlem yumuşar. 14. günde tatlı seni rahatsız etmeye başlar.' },
  17: { title: 'Alkol Farkındalığı', teaching: 'Alkol = beden için stres + uyku kalitesi düşüşü + protein sentezi engeli. 1 kadeh = 3 gün toparlanma. "Sosyal" alkol bile uzun vadede zehir. Disiplinli insan haftada 0-2 kadeh.', action: 'Bugün alkol tüketme. Eğer alışkansan, "alkolsüz pazartesi" diye başla.', reflectionPrompt: 'Alkolsüz akşam nasıl geçti? Uyku kalitesi farkı?', proTip: 'Sosyal ortamda "soda + lime" iste. Görüntüsü kokteyl, etkisi 0.' },
  18: { title: 'Bağırsak Sağlığı', teaching: 'Bağırsak = "ikinci beyin." Bağırsak florası bozuk = depresyon, yorgunluk, bağışıklık zayıflığı. Çözüm: fermente gıda (yoğurt, kefir, lahana turşusu) + lif (yeşillik, baklagil) + işlenmiş yiyecek azaltma.', action: 'Bugün 1 fermente gıda + 1 yeşillik öğünü yap.', reflectionPrompt: 'Bağırsak sağlığını ne kadar düşünüyordun?', proTip: 'Sabah 1 yemek kaşığı kefir. 1 hafta sonra fark hissedilir.' },
  19: { title: 'Güneş Maruziyeti', teaching: 'D vitamini eksikliği = halk sağlığı krizi. Çoğu insan kronik düşük. Çözüm: günde 15-20 dk doğrudan güneş (kol/yüz). Krem yokken. Sabah/öğle güneşi en güçlü.', action: 'Bugün 15 dakika doğrudan güneş al. Krem yok, açık alan.', reflectionPrompt: 'Güneş maruziyeti ruh halini nasıl etkiledi?', proTip: 'Öğle yemeğini dışarıda ye. 30 dakika güneş + sosyal değer.' },
  20: { title: 'Yatmadan Esneme', teaching: 'Sırt-bel-bacak gerginliği = uyku kalitesi düşüşü. Yatmadan 5 dk esneme = parasempatik aktivasyon, kas gevşemesi, daha derin uyku. Yoga gerekmez, basit hareketler.', action: 'Bu gece yatmadan 5 dk esneme yap. 3 hareket: öne eğil, butterfly, omuz açılışı.', reflectionPrompt: 'Esnemeli akşamla esnememiş akşam farkı?', proTip: 'Yataktayken yap. Yer doşeği gerekmez. Sırtüstü, bacaklar yukarı duvara.' },
  21: { title: 'Oturuş Postürü', teaching: 'Günün 8 saati oturuyorsan, postürün her şeyi etkiler. Doğru oturuş: ayaklar yerde, dizler 90°, kalça en yüksek nokta, omuzlar geride. Yanlış: kambur, çapraz bacak, sandalye ucu.', action: 'Bugün her saat 30 saniye postür kontrolü yap. Saatte 1 kez 30 sn ayağa kalk.', reflectionPrompt: 'Postür farkındalığın gün boyu nasıl değişti?', proTip: 'Bel yastığı kullan. 5 TL\'lik yastık, 5.000 TL\'lik kiropraktör masrafını önler.' },
  22: { title: 'Uyku Hijyeni', teaching: 'Uyku ilaç değil — günlük tasarımdır. 8 koşul: 1) sabit saat, 2) karanlık, 3) sessiz, 4) serin (18°C), 5) telefonsuz, 6) son öğün 3h önce, 7) kafein 14:00\'dan sonra yok, 8) alkol minimum.', action: 'Bugün 8 koşulu kontrol et. Hangisi bozuk?', reflectionPrompt: 'En kolay düzelteceğin koşul hangisi?', proTip: '8 koşulu yatak başı kâğıda yaz. Her gece tikle. 30 günde sistem oturur.' },
  23: { title: 'Plato Kırma', teaching: 'Antrenmanda 4-6 hafta sonra ilerleme durur — plato. Beden adapte olur. Kırmak için: 1) ağırlık artır, 2) tekrar artır, 3) dinlenme süresini değiştir, 4) hareket çeşitliliği. Tek değişken yeter.', action: 'Bugün antrenmanında 1 değişken değiştir (sayı, ağırlık, tempo, hareket).', reflectionPrompt: 'Hangi değişkeni değiştirdin? Beden tepkisi?', proTip: '6 hafta sonra plato — 7. hafta yeniden değiştir. Beden adapte oldukça sen de adapte ol.' },
  24: { title: 'Nefes Kontrolü', teaching: 'Nefes = otonom sinir sisteminin uzaktan kumandası. Hızlı nefes = stres. Yavaş nefes = sakinlik. Burundan al, nefesi 1.5x kadar uzun ver. 5 dk pratik = anlık sakinlik.', action: 'Bugün stresli anda 1 dakika 4 sn al / 6 sn ver tekniğini uygula.', reflectionPrompt: 'Nefes pratiği stresini ne kadar değiştirdi?', proTip: 'Burnundan nefes al. Ağızdan nefes alma alışkanlığı = uyku apnesi riski + diş çürüğü.' },
  25: { title: 'Toparlanma Protokolleri', teaching: 'Antrenman küçük yıkım — toparlanma onarım. Kötü toparlanma = sürekli yorgun. İyi toparlanma araçları: 1) uyku 7-9 saat, 2) protein, 3) hidrasyon, 4) yürüyüş, 5) sıcak/soğuk kontrast.', action: 'Bugün toparlanmanın 5 koşulundan en az 4\'ünü uygula.', reflectionPrompt: 'Hangi toparlanma aracı en çok fark yarattı?', proTip: 'Antrenman sonrası soğuk duş = enflamasyon azaltır. Sıcak banyo = kas gevşemesi.' },
  26: { title: 'Haftalık Antrenman', teaching: 'Düzensiz antrenman = düzensiz sonuç. Haftalık plan: 3 gün direnç + 2 gün kardiyo + 2 gün dinlen. 7 günlük yapı = 12 hafta sonra dönüşüm.', action: 'Bu hafta için 7 günlük antrenman planı yaz. Her gün ne, ne kadar.', reflectionPrompt: 'Plan yapmadan haftan nasıl geçerdi?', proTip: 'Pazar akşamı plan yap. Pazartesi otomatik başlasın.' },
  27: { title: 'Uyku Apnesi Farkındalığı', teaching: '%25 erkek uyku apnesi taşır — çoğu farkında değil. Belirtiler: gündüz aşırı uyku, horlama, sabah baş ağrısı, gece sık uyanma. Tedavi edilmeyen uyku apnesi = kalp hastalığı + diabet riski.', action: 'Bugün partnerinden gece horlamanı dinlemesini iste. Aşırı uykulu mu? Sabah baş ağrılı mı?', reflectionPrompt: 'Uyku apnesi olabileceğine dair hangi belirti taşıyorsun?', proTip: 'Şüphe varsa uyku doktoruna git. Polisomnografi tek gece, hayat kurtarır.' },
  28: { title: 'Disiplin Kimliği', teaching: '"Sağlıklıyım" demek değil — "sağlıklı yaşayan biriyim" demek. Kimlik > davranış. Sigara içen biriydim, içmiyorum şu an = geri dönüş. İçici değilim = kalıcı.', action: 'Bugün kendine 1 yeni beden kimliği etiketi yapıştır.', reflectionPrompt: 'Hangi kimliği seçtin? Kanıtın ne?', proTip: 'Kimliği yüksek sesle her sabah söyle. Beyin tekrara inanır.' },
  29: { title: 'Final Sprint', teaching: '29 gün boyunca beden disiplini pratik ettin. Yarın "tamamladın." Ama beden yarınla bitmiyor. Final test: bu 30 günde işe yarayan en güçlü 1 alışkanlığı seç. 100 gün daha.', action: 'Bugün 30 günün en güçlü 1 beden disiplinini seç. Hangisi?', reflectionPrompt: 'Niye bu disiplini seçtin? Hangi sonucu verdi?', proTip: 'O 1 disiplini takvime "non-negotiable" olarak işaretle. Pazartesi-pazar her gün.' },
  30: { title: 'Tamamlandı — Yeni Beden', teaching: '30 gün önce beden zayıf, dağınık, uyusuzdun. Şimdi: hareket, uyku, beslenme yapılı. Beden değişti — sen değiştin çünkü. Bu sabah aynaya bak: yeni bir beden, yeni bir kimlik.', action: 'Bugün 30 günün özetini yaz: 3 öğrendiğim, 3 sürdüreceğim, 3 unutmayacağım.', reflectionPrompt: 'Yeni bedenle hangi büyük şeyi yapacaksın?', proTip: 'Bir sonraki yola geçmeden 3 gün dinlen. Beden tutarlılıkla şekillenir.' },
};

const NEW_EN = {
  6: { title: 'Bedtime: 22:00', teaching: 'Circadian rhythm strengthens with fixed sleep time. 22:00 = natural melatonin peak. Weekday/weekend doesn\'t matter. Flexible bedtime drops sleep quality 40% (Walker research).', action: 'Tonight be in bed by 22:00. Phone in another room.', reflectionPrompt: 'How is 22:00 bed time different from yesterday?', proTip: 'Blue-light filter + warm night-lamp after 21:00. Body prepares for 22.' },
  7: { title: 'Hydration: 2 Liters', teaching: 'Body is 60% water. 2% dehydration = 20% cognitive drop. Most people chronically dehydrated. Solution: 2L = ~8 glasses. Morning, before-noon, after-noon 0.5L blocks.', action: 'Today drink 2L water. 1L morning, 1L afternoon. Visible bottle.', reflectionPrompt: 'When did you feel full hydration in your body?', proTip: 'First drink water. Hydration starts 90 min before coffee.' },
  8: { title: '10,000 Steps a Day', teaching: 'Step counting looks trendy but science is firm: 7-10K daily = 30% lower mortality (Lancet 2023). Constant sitting equals cancer risk. Movement = medicine.', action: 'Today reach 10,000 steps. Phone has a counter.', reflectionPrompt: 'How did 10K steps shape your day?', proTip: 'Walk meetings. Walk while on calls. Stairs over elevator.' },
  9: { title: 'Resistance Training Intro', teaching: 'Cardio is good, but resistance training (weight, bodyweight) adds 30% more lifespan. Muscle = second heart. After 30, muscle loss is 1%/year — without training, you don\'t stand straight at 50.', action: 'Today do 3 basics × 3 sets: squat, push-up, plank. 10 reps each.', reflectionPrompt: 'How was your energy after resistance work?', proTip: '3 days/week is enough. Mon-Wed-Fri 20 min home workout.' },
  10: { title: 'Daily Push-Ups', teaching: 'One move = added years. Chinese study: men 40+ who do >40 push-ups have 96% lower heart disease risk. Cost: 5 minutes.', action: 'Today do 20 push-ups. Even split across the day, total 20.', reflectionPrompt: 'How hard is daily push-up progress?', proTip: '5 push-ups after brushing teeth. Stack = 500 in 100 days.' },
  11: { title: 'Daily Squat', teaching: 'Squat = whole-body. Quads, glutes, core, balance. Want easy stand-up at 50? Squat at 30. Joint-friendly, no equipment, effective.', action: 'Today do 30 squats. Splits ok: 3x10. Form > count.', reflectionPrompt: 'How was paying attention to form?', proTip: 'Push hips back, knees behind toes. Mirror or video yourself.' },
  12: { title: 'Plank Discipline', teaching: 'Weak core = leaks in every move. Plank = passive core training. 60-sec plank = more effective than 100 sit-ups. 80% of back pain is weak core.', action: 'Today plank for 30 seconds. Tomorrow 35, then 40. Build to 60.', reflectionPrompt: 'What ran through your mind holding the plank?', proTip: 'Don\'t hold breath. Slow exhale keeps core engaged.' },
  13: { title: 'Cardio Zones', teaching: 'Not all cardio equal. Zone 2 (moderate, conversational) = mitochondria growth, fat burn, endurance. Zone 5 (sprint) = peak power. Most stuck in 3-4 — ineffective middle.', action: 'Today do 30 min zone 2 cardio. Brisk walk / light jog. Speak-able pace.', reflectionPrompt: 'How slow did zone 2 feel?', proTip: 'Apple Watch / Garmin show zones. None: if you can talk, you\'re zone 2.' },
  14: { title: 'Mobility Work', teaching: 'Flexibility ≠ mobility. Flexibility = passive stretch. Mobility = controlled range of motion. After 30, daily shoulder/hip/ankle mobility prevents range loss at 50.', action: 'Today do 5 min mobility. Arm circles, hip openers, ankle rotations.', reflectionPrompt: 'Which joint felt most restricted?', proTip: 'Do post-shower morning. Muscles warm, mobility optimum.' },
  15: { title: 'Meal Timing', teaching: 'What you eat matters; when you eat matters too. Late dinner = sleep loss, slow digestion. Last meal 3h before bed. 19:00 dinner, 22:00 sleep = ideal.', action: 'Today don\'t eat after 19:00.', reflectionPrompt: 'How did early dinner affect sleep?', proTip: 'Earlier dinner = less evening snacking. Find balance: not starving, not full.' },
  16: { title: 'Sugar-Free Day', teaching: 'Sugar = addiction molecule. Hijacks brain reward. 1-day sugar-free challenge: only natural fruit sugar allowed. No chocolate, cake, soda, packaged.', action: 'Today consume zero processed sugar.', reflectionPrompt: 'When did you crave the most?', proTip: 'First 3 days hard, 4th softens. By day 14, sweets bother you.' },
  17: { title: 'Alcohol Awareness', teaching: 'Alcohol = body stress + sleep loss + protein synthesis block. 1 glass = 3-day recovery. Even "social" alcohol is long-term poison. Disciplined person: 0-2 glasses/week.', action: 'Today no alcohol. If habit, start "Alcohol-Free Monday."', reflectionPrompt: 'How did the alcohol-free evening go? Sleep difference?', proTip: 'Order soda + lime in social settings. Looks like cocktail, zero impact.' },
  18: { title: 'Gut Health', teaching: 'Gut = "second brain." Damaged microbiome = depression, fatigue, weak immunity. Solution: fermented food (yogurt, kefir, sauerkraut) + fiber (greens, legumes) + less processed.', action: 'Today eat 1 fermented food + 1 greens meal.', reflectionPrompt: 'How much did you think about gut health before?', proTip: 'Tablespoon of kefir morning. Difference felt in 1 week.' },
  19: { title: 'Sun Exposure', teaching: 'Vitamin D deficiency = public health crisis. Most chronically low. Solution: 15-20 min direct sun (arms/face) without sunscreen daily. Morning/midday strongest.', action: 'Today 15 min direct sun. Skin uncovered, no sunscreen.', reflectionPrompt: 'How did sunlight affect your mood?', proTip: 'Eat lunch outside. 30 min sun + social value combined.' },
  20: { title: 'Pre-Sleep Stretch', teaching: 'Back-leg-spine tension = poor sleep. 5 min pre-sleep stretch = parasympathetic activation, muscle release, deeper sleep. No yoga needed, just simple moves.', action: 'Tonight 5 min stretch before bed. 3 moves: forward bend, butterfly, shoulder opener.', reflectionPrompt: 'Stretched vs unstretched evening — difference?', proTip: 'Do it in bed. No mat needed. Lie back, legs up wall.' },
  21: { title: 'Sitting Posture', teaching: '8h/day sitting? Posture rules everything. Right: feet flat, knees 90°, hips highest, shoulders back. Wrong: hunched, crossed legs, edge-of-chair.', action: 'Today posture-check 30s every hour. Stand 30s once an hour.', reflectionPrompt: 'How did posture awareness shift through the day?', proTip: 'Lumbar pillow. $5 pillow saves $5,000 chiropractor.' },
  22: { title: 'Sleep Hygiene', teaching: 'Sleep isn\'t medicine — it\'s daily design. 8 conditions: 1) fixed time, 2) dark, 3) silent, 4) cool (18°C), 5) phoneless, 6) last meal 3h prior, 7) caffeine before 14:00, 8) minimal alcohol.', action: 'Today check the 8 conditions. Which is broken?', reflectionPrompt: 'Easiest one to fix?', proTip: 'Write 8 conditions on bedside note. Tick each night. 30 days = system.' },
  23: { title: 'Plateau Break', teaching: 'In training, progress stops 4-6 weeks in — plateau. Body adapts. Break: 1) up weight, 2) up reps, 3) change rest time, 4) move variety. One variable suffices.', action: 'Today change 1 variable in training (reps, weight, tempo, exercise).', reflectionPrompt: 'Which variable changed? Body response?', proTip: '6 weeks → plateau → week 7 change again. As body adapts, you adapt.' },
  24: { title: 'Breath Control', teaching: 'Breath = autonomic nervous system remote. Fast breath = stress. Slow breath = calm. Inhale through nose, exhale 1.5x longer. 5-min practice = instant calm.', action: 'Today in stress moment, do 1 min of 4-in / 6-out.', reflectionPrompt: 'How much did breath practice change stress?', proTip: 'Nose breathing. Mouth breathing = sleep apnea risk + tooth decay.' },
  25: { title: 'Recovery Protocols', teaching: 'Training = micro damage; recovery = repair. Bad recovery = constant fatigue. Tools: 1) 7-9h sleep, 2) protein, 3) hydration, 4) walking, 5) hot/cold contrast.', action: 'Today apply at least 4 of the 5 recovery tools.', reflectionPrompt: 'Which recovery tool moved the needle most?', proTip: 'Cold shower post-workout = inflammation drop. Hot bath = muscle release.' },
  26: { title: 'Weekly Workout', teaching: 'Random training = random results. Weekly: 3 resistance + 2 cardio + 2 rest. 7-day structure → 12-week transformation.', action: 'This week write a 7-day plan. Each day what + how much.', reflectionPrompt: 'How would the week go without a plan?', proTip: 'Plan Sunday night. Monday auto-starts.' },
  27: { title: 'Sleep Apnea Awareness', teaching: '25% of men carry sleep apnea — most unaware. Symptoms: excessive daytime sleep, snoring, morning headache, frequent waking. Untreated = heart disease + diabetes risk.', action: 'Today ask your partner to listen for snoring. Sleepy daytime? Morning headache?', reflectionPrompt: 'Which apnea symptom might you have?', proTip: 'If suspected, see a sleep doctor. Polysomnography = one night, life-saving.' },
  28: { title: 'Discipline Identity', teaching: 'Don\'t say "I am healthy" — say "I am someone who lives healthy." Identity > behavior. "I used to smoke, not now" = relapse risk. "I\'m not a smoker" = permanent.', action: 'Today claim 1 new body identity label.', reflectionPrompt: 'Which identity? Your evidence?', proTip: 'Speak the identity aloud each morning. Brain believes repetition.' },
  29: { title: 'Final Sprint', teaching: '29 days of body discipline. Tomorrow you "complete." But body doesn\'t end with tomorrow. Final test: which 1 most powerful habit of 30 days? 100 more days.', action: 'Today pick the strongest 1 body discipline of 30 days. Which?', reflectionPrompt: 'Why this one? What result did it deliver?', proTip: 'Mark it "non-negotiable" on calendar. Mon-Sun every day.' },
  30: { title: 'Complete — New Body', teaching: '30 days ago body weak, scattered, sleepless. Now: movement, sleep, nutrition structured. Body changed — because you did. Look in mirror: new body, new identity.', action: 'Today summarize 30 days: 3 learned, 3 to keep, 3 not to forget.', reflectionPrompt: 'With this new body, what big thing will you do?', proTip: 'Rest 3 days before next path. Body shapes through consistency.' },
};

const QUIZ_TR = {
  6: [ { q: 'Optimum yatış saati?', options: ['20:00', '22:00', '00:00', '02:00'], correct: 1, explain: '22:00 = melatonin doğal zirvesi.' }, { q: 'Esnek yatış uyku düşüşü?', options: ['Yok', '%10', '%40', '%80'], correct: 2, explain: '%40 uyku kalitesi düşer.' } ],
  7: [ { q: 'Optimum günlük su?', options: ['500ml', '1L', '2L', '5L'], correct: 2, explain: '2 litre = ~8 bardak.' }, { q: '%2 dehidratasyon etkisi?', options: ['Yok', '%5 düşüş', '%20 düşüş', '%50'], correct: 2, explain: 'Bilişsel %20 düşüş.' } ],
  8: [ { q: 'Günlük adım hedefi?', options: ['1K', '5K', '10K', '50K'], correct: 2, explain: '7-10K = optimum sağlık.' }, { q: 'Adımla ölüm riski?', options: ['Aynı', '%30 düşük', '%80 yüksek', 'Bilinmez'], correct: 1, explain: '%30 daha düşük ölüm.' } ],
  9: [ { q: 'Direnç antrenmanı ömür?', options: ['Yok', '%10 artış', '%30 artış', '%200'], correct: 2, explain: '%30 daha çok ömür.' }, { q: '30 sonrası kas kaybı?', options: ['Yok', '%1/yıl', '%5/yıl', '%10/yıl'], correct: 1, explain: 'Yıllık %1, antrenmansız.' } ],
  10: [ { q: 'Push-up sayısı kalp riski?', options: ['Etkisiz', '40+ = %96 düşük', '10+ = %50', '100+ = aynı'], correct: 1, explain: '40+ push-up = %96 düşük risk.' }, { q: 'Stack tekniği?', options: ['Yok', 'Diş sonrası 5', '100\'lük set', 'Random'], correct: 1, explain: 'Diş + push-up = otomatik.' } ],
  11: [ { q: 'Squat formu?', options: ['Diz öne', 'Kalça geri', 'Dik', 'Hızlı'], correct: 1, explain: 'Kalçayı geriye it.' }, { q: 'Squat kapsamı?', options: ['Sadece bacak', 'Tüm vücut', 'Kor', 'Sırt'], correct: 1, explain: 'Tüm vücut hareketi.' } ],
  12: [ { q: 'Plank başlangıç?', options: ['10 sn', '30 sn', '5 dk', '1 saat'], correct: 1, explain: '30 sn ile başla.' }, { q: 'Sırt ağrısı sebebi?', options: ['Yaş', 'Zayıf kor', 'Genetik', 'Şans'], correct: 1, explain: 'Sırt ağrısının %80 zayıf kor.' } ],
  13: [ { q: 'Zone 2 ne demek?', options: ['Sprint', 'Konuşabildiğin tempo', 'Maksimum', 'Yürüyüş'], correct: 1, explain: 'Konuşabildiğin orta yoğunluk.' }, { q: 'Çoğu insan hangi zone\'da?', options: ['1', '2', '3-4 takılı', '5'], correct: 2, explain: 'Etkisiz orta bölge.' } ],
  14: [ { q: 'Mobilite vs esneklik?', options: ['Aynı', 'Mobilite kontrollü hareket', 'Esneklik aktif', 'Bilinmez'], correct: 1, explain: 'Mobilite = kontrollü hareket.' }, { q: '30+ yaş mobilite?', options: ['Yok', 'Günlük şart', 'Haftalık', 'Aylık'], correct: 1, explain: 'Günlük 5 dk yeterli.' } ],
  15: [ { q: 'Son öğün yatma arası?', options: ['1h', '2h', '3h', '5h'], correct: 2, explain: '3 saat ideal.' }, { q: 'Geç yemek etkisi?', options: ['Yok', 'Uyku düşüşü', 'Daha iyi', 'Pozitif'], correct: 1, explain: 'Uyku kalitesi düşüşü.' } ],
  16: [ { q: 'Şekersiz challenge süresi?', options: ['1 saat', '1 gün', '1 hafta', '1 ay'], correct: 1, explain: '1 günle başla.' }, { q: 'Şeker özlemi ne zaman kırılır?', options: ['1 gün', '4-7 gün', '14 gün', '30 gün'], correct: 1, explain: '4. günden sonra yumuşar.' } ],
  17: [ { q: '1 kadeh alkol toparlanma?', options: ['Yok', '1 saat', '1 gün', '3 gün'], correct: 3, explain: '3 gün toparlanma süresi.' }, { q: 'Disiplinli haftalık alkol?', options: ['Sınırsız', '0-2 kadeh', '5+ kadeh', 'Sadece akşam'], correct: 1, explain: '0-2 kadeh maksimum.' } ],
  18: [ { q: 'Bağırsak = ?', options: ['Sindirim', 'İkinci beyin', 'Filtre', 'Pasif'], correct: 1, explain: 'İkinci beyin — flora kritik.' }, { q: 'Fermente gıda örneği?', options: ['Çikolata', 'Kefir', 'Beyaz ekmek', 'Şeker'], correct: 1, explain: 'Kefir = probiyotik.' } ],
  19: [ { q: 'D vitamini için süre?', options: ['1 dk', '15-20 dk', '2 saat', '5 saat'], correct: 1, explain: 'Günde 15-20 dk yeterli.' }, { q: 'Krem etkisi?', options: ['Yok', 'D vitaminini engeller', 'Artırır', 'Aynı'], correct: 1, explain: 'Krem = D vitamini bloğu.' } ],
  20: [ { q: 'Yatmadan önce esneme?', options: ['Yok', '5 dk yeter', '1 saat şart', 'Hiç'], correct: 1, explain: '5 dakika yeterli.' }, { q: 'Esneme etkisi?', options: ['Stres artar', 'Parasempatik', 'Sempatik', 'Etkisiz'], correct: 1, explain: 'Parasempatik = sakinlik.' } ],
  21: [ { q: 'Doğru oturuş?', options: ['Çapraz bacak', 'Dizler 90°', 'Ucu sandalye', 'Hareketli'], correct: 1, explain: 'Dizler 90°, ayaklar yerde.' }, { q: 'Saatte ne yap?', options: ['Hep otur', '30sn ayağa kalk', 'Yat', 'Koş'], correct: 1, explain: 'Saatte 30 saniye dur.' } ],
  22: [ { q: 'Optimum oda sıcaklığı?', options: ['15°C', '18-20°C', '24°C', '28°C'], correct: 1, explain: '18-20°C derin uyku.' }, { q: 'Kafein son saati?', options: ['Yok', '14:00', '18:00', '22:00'], correct: 1, explain: 'Saat 14\'ten sonra hayır.' } ],
  23: [ { q: 'Plato kaç hafta sonra?', options: ['1', '4-6', '12', '52'], correct: 1, explain: 'Beden adapte olur.' }, { q: 'Plato kırma?', options: ['Bırak', 'Variabledeği', 'Daha hızlı', 'Aynı'], correct: 1, explain: 'Tek değişken yeter.' } ],
  24: [ { q: 'Nefes ritmi sakinlik?', options: ['1:1', '4 al / 6 ver', '10 al', 'Hızlı'], correct: 1, explain: 'Verme uzun = sakinlik.' }, { q: 'Burun vs ağız nefes?', options: ['Aynı', 'Burun > ağız', 'Ağız iyi', 'Bilinmez'], correct: 1, explain: 'Burun = filtre + ısıt + nemlendir.' } ],
  25: [ { q: 'Toparlanma araçları?', options: ['1', '5', '10', '20'], correct: 1, explain: '5 ana araç (uyku, protein, su, yürüyüş, ısı).' }, { q: 'Antrenman sonrası soğuk?', options: ['Tehlikeli', 'Enflamasyon azaltır', 'Etkisiz', 'Sadece sıcak'], correct: 1, explain: 'Soğuk = enflamasyon düşer.' } ],
  26: [ { q: 'Optimum haftalık?', options: ['7 gün direnç', '3 direnç + 2 kardiyo + 2 dinlen', 'Hep kardiyo', 'Sıfır plan'], correct: 1, explain: 'Dengeli yapı.' }, { q: 'Plan yapma zamanı?', options: ['Cumartesi', 'Pazar gece', 'Pazartesi sabah', 'Hiç'], correct: 1, explain: 'Pazar planla, pazartesi başla.' } ],
  27: [ { q: 'Uyku apnesi taşıyan erkek %?', options: ['%5', '%15', '%25', '%50'], correct: 2, explain: '%25 erkek apnesi taşır.' }, { q: 'Apne belirtisi?', options: ['Hiç', 'Horlama + gündüz uyku', 'Mutluluk', 'Etkisiz'], correct: 1, explain: 'Horlama + gündüz uyku.' } ],
  28: [ { q: '"Sigara içmiyorum" vs "İçici değilim"?', options: ['Aynı', 'Kimlik 10x güçlü', 'Davranış güçlü', 'Bilinmez'], correct: 1, explain: 'Kimlik kalıcı.' }, { q: 'Disiplin = ?', options: ['Davranış', 'Kimlik', 'Plan', 'Motivasyon'], correct: 1, explain: 'Kimlik > davranış.' } ],
  29: [ { q: 'Final disiplin testi?', options: ['Bitiş', 'Hangi 1 sürdürülecek?', 'Yorgunluk', 'Memnuniyet'], correct: 1, explain: '1 alışkanlık seç, devam et.' }, { q: 'Non-negotiable ne?', options: ['Esnek', 'Pazardan pazara her gün', 'Haftada 1', 'Aylık'], correct: 1, explain: 'Her gün şart.' } ],
  30: [ { q: 'Geçişten sonra dinlenme?', options: ['Yok', '3 gün', '1 hafta', '1 ay'], correct: 1, explain: '3 gün dinlen.' }, { q: '30 günün özeti?', options: ['Yok', '3+3+3', 'Random', 'Liste'], correct: 1, explain: '3 öğrendiğim, 3 sürdüreceğim, 3 unutmayacağım.' } ],
};

const QUIZ_EN = {
  6: [ { q: 'Optimum bedtime?', options: ['20:00', '22:00', '00:00', '02:00'], correct: 1, explain: '22:00 = melatonin natural peak.' }, { q: 'Flexible bedtime sleep drop?', options: ['None', '10%', '40%', '80%'], correct: 2, explain: '40% sleep quality drop.' } ],
  7: [ { q: 'Optimum daily water?', options: ['500ml', '1L', '2L', '5L'], correct: 2, explain: '2 liters = ~8 glasses.' }, { q: '2% dehydration effect?', options: ['None', '5% drop', '20% drop', '50%'], correct: 2, explain: 'Cognitive 20% drop.' } ],
  8: [ { q: 'Daily steps target?', options: ['1K', '5K', '10K', '50K'], correct: 2, explain: '7-10K = optimum.' }, { q: 'Steps and mortality?', options: ['Same', '30% lower', '80% higher', 'Unknown'], correct: 1, explain: '30% lower mortality.' } ],
  9: [ { q: 'Resistance training lifespan?', options: ['None', '+10%', '+30%', '+200%'], correct: 2, explain: '30% more years.' }, { q: 'Muscle loss after 30?', options: ['None', '1%/year', '5%/year', '10%'], correct: 1, explain: 'Yearly 1%, untrained.' } ],
  10: [ { q: 'Push-ups & heart risk?', options: ['No effect', '40+ = -96%', '10+ = -50%', '100+ = same'], correct: 1, explain: '40+ push-ups = 96% lower risk.' }, { q: 'Stack technique?', options: ['None', 'After brushing 5', '100 set', 'Random'], correct: 1, explain: 'Brush + push-up = automatic.' } ],
  11: [ { q: 'Squat form?', options: ['Knees forward', 'Hips back', 'Stiff', 'Fast'], correct: 1, explain: 'Push hips back.' }, { q: 'Squat scope?', options: ['Legs only', 'Full body', 'Core', 'Back'], correct: 1, explain: 'Full body move.' } ],
  12: [ { q: 'Plank starter?', options: ['10s', '30s', '5 min', '1h'], correct: 1, explain: 'Start 30s.' }, { q: 'Back pain cause?', options: ['Age', 'Weak core', 'Genes', 'Luck'], correct: 1, explain: '80% of back pain = weak core.' } ],
  13: [ { q: 'Zone 2 means?', options: ['Sprint', 'Speakable pace', 'Maximum', 'Walk'], correct: 1, explain: 'Conversational moderate.' }, { q: 'Most people in zone?', options: ['1', '2', '3-4 stuck', '5'], correct: 2, explain: 'Ineffective middle.' } ],
  14: [ { q: 'Mobility vs flexibility?', options: ['Same', 'Mobility = controlled motion', 'Flexibility active', 'Unknown'], correct: 1, explain: 'Mobility = controlled motion.' }, { q: '30+ mobility?', options: ['None', 'Daily required', 'Weekly', 'Monthly'], correct: 1, explain: 'Daily 5 min suffices.' } ],
  15: [ { q: 'Last meal to bed gap?', options: ['1h', '2h', '3h', '5h'], correct: 2, explain: '3 hours ideal.' }, { q: 'Late meal effect?', options: ['None', 'Sleep drop', 'Better', 'Positive'], correct: 1, explain: 'Sleep quality drops.' } ],
  16: [ { q: 'Sugar-free challenge?', options: ['1h', '1 day', '1 week', '1 month'], correct: 1, explain: 'Start 1 day.' }, { q: 'Craving breaks when?', options: ['1 day', '4-7 days', '14 days', '30 days'], correct: 1, explain: 'Day 4 onwards softens.' } ],
  17: [ { q: '1 drink recovery time?', options: ['None', '1h', '1 day', '3 days'], correct: 3, explain: '3 days recovery.' }, { q: 'Disciplined weekly alcohol?', options: ['Unlimited', '0-2 drinks', '5+', 'Only evening'], correct: 1, explain: '0-2 drinks max.' } ],
  18: [ { q: 'Gut = ?', options: ['Digestion', 'Second brain', 'Filter', 'Passive'], correct: 1, explain: 'Second brain — flora critical.' }, { q: 'Fermented food example?', options: ['Chocolate', 'Kefir', 'White bread', 'Sugar'], correct: 1, explain: 'Kefir = probiotic.' } ],
  19: [ { q: 'Vitamin D sun duration?', options: ['1 min', '15-20 min', '2h', '5h'], correct: 1, explain: '15-20 min daily.' }, { q: 'Sunscreen effect?', options: ['None', 'Blocks D', 'Boosts', 'Same'], correct: 1, explain: 'Sunscreen = D blocker.' } ],
  20: [ { q: 'Pre-sleep stretch?', options: ['None', '5 min suffices', '1h required', 'Never'], correct: 1, explain: '5 min suffices.' }, { q: 'Stretch effect?', options: ['Stress up', 'Parasympathetic', 'Sympathetic', 'No effect'], correct: 1, explain: 'Parasympathetic = calm.' } ],
  21: [ { q: 'Right sitting?', options: ['Crossed legs', 'Knees 90°', 'Edge of chair', 'Active'], correct: 1, explain: 'Knees 90°, feet flat.' }, { q: 'Hourly do?', options: ['Always sit', '30s standing', 'Lie', 'Run'], correct: 1, explain: 'Stand 30s every hour.' } ],
  22: [ { q: 'Optimal room temp?', options: ['15°C', '18-20°C', '24°C', '28°C'], correct: 1, explain: '18-20°C deep sleep.' }, { q: 'Caffeine cutoff?', options: ['None', '14:00', '18:00', '22:00'], correct: 1, explain: 'No caffeine after 14:00.' } ],
  23: [ { q: 'Plateau weeks?', options: ['1', '4-6', '12', '52'], correct: 1, explain: 'Body adapts.' }, { q: 'Break plateau?', options: ['Quit', 'Change variable', 'Push harder', 'Same'], correct: 1, explain: 'One variable suffices.' } ],
  24: [ { q: 'Calming breath rhythm?', options: ['1:1', '4 in / 6 out', '10 in', 'Fast'], correct: 1, explain: 'Longer exhale = calm.' }, { q: 'Nose vs mouth breath?', options: ['Same', 'Nose > mouth', 'Mouth fine', 'Unknown'], correct: 1, explain: 'Nose = filter + warm + humidify.' } ],
  25: [ { q: 'Recovery tools?', options: ['1', '5', '10', '20'], correct: 1, explain: '5 main (sleep, protein, water, walk, hot/cold).' }, { q: 'Post-workout cold?', options: ['Dangerous', 'Reduces inflammation', 'No effect', 'Hot only'], correct: 1, explain: 'Cold = less inflammation.' } ],
  26: [ { q: 'Optimum weekly?', options: ['7 days resistance', '3 res + 2 cardio + 2 rest', 'All cardio', 'Zero plan'], correct: 1, explain: 'Balanced structure.' }, { q: 'Plan when?', options: ['Saturday', 'Sunday night', 'Monday morning', 'Never'], correct: 1, explain: 'Plan Sunday, start Monday.' } ],
  27: [ { q: 'Men with sleep apnea %?', options: ['5%', '15%', '25%', '50%'], correct: 2, explain: '25% of men.' }, { q: 'Apnea symptom?', options: ['None', 'Snoring + day sleep', 'Joy', 'No effect'], correct: 1, explain: 'Snoring + daytime sleep.' } ],
  28: [ { q: '"Don\'t smoke" vs "Not a smoker"?', options: ['Same', 'Identity 10x stronger', 'Behavior strong', 'Unknown'], correct: 1, explain: 'Identity is permanent.' }, { q: 'Discipline = ?', options: ['Behavior', 'Identity', 'Plan', 'Motivation'], correct: 1, explain: 'Identity > behavior.' } ],
  29: [ { q: 'Final discipline test?', options: ['End', 'Which 1 to keep?', 'Tiredness', 'Satisfaction'], correct: 1, explain: 'Pick 1 habit to continue.' }, { q: 'Non-negotiable means?', options: ['Flexible', 'Every day Mon-Sun', 'Weekly', 'Monthly'], correct: 1, explain: 'Daily required.' } ],
  30: [ { q: 'Rest after transition?', options: ['None', '3 days', '1 week', '1 month'], correct: 1, explain: '3 days rest.' }, { q: '30-day summary?', options: ['None', '3+3+3', 'Random', 'List'], correct: 1, explain: '3 learned, 3 to keep, 3 not to forget.' } ],
};

function buildLessons(newContent, quizMap, protips) {
  const out = {};
  for (const [order, tip] of Object.entries(protips)) out[order] = { proTip: tip };
  for (const [order, lesson] of Object.entries(newContent)) {
    out[order] = {
      title: lesson.title, teaching: lesson.teaching, action: lesson.action,
      reflectionPrompt: lesson.reflectionPrompt, proTip: lesson.proTip,
      quiz: quizMap[order] || [],
    };
  }
  return out;
}
function applyToFile(filePath, pathId, lessonsMerge) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (!data.lessons[pathId]) data.lessons[pathId] = {};
  for (const [order, fields] of Object.entries(lessonsMerge)) {
    data.lessons[pathId][order] = { ...(data.lessons[pathId][order] || {}), ...fields };
  }
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
}

const TR_MERGE = buildLessons(NEW_TR, QUIZ_TR, PROTIPS_TR);
const EN_MERGE = buildLessons(NEW_EN, QUIZ_EN, PROTIPS_EN);
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.tr.json'), 'body-discipline', TR_MERGE);
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.en.json'), 'body-discipline', EN_MERGE);
console.log(`✓ Body Discipline seeded — ${Object.keys(NEW_TR).length} new lessons + 5 pro tips × 2 langs`);
