/** Silent-morning lessons 31-50 (advanced phase). TR + EN. */
const fs = require('fs');
const path = require('path');

const NEW_TR = {
  31: { title: 'Sabah Yürüyüş Meditasyonu', teaching: 'Otururken meditasyon zor. Yürürken meditasyon doğal. Her adım = nefes. Her adım = farkındalık. 10 dakika sabah yürüyüş + meditasyon = 1 saat oturma denkliği.', action: 'Bugün 10 dk yürüyüş meditasyonu yap. Her adımı say.', reflectionPrompt: 'Yürüme meditasyonu oturma\'dan farklı mı?', proTip: 'Burnundan al, ağzından ver. Her 4 adımda bir nefes.' },
  32: { title: 'Stillness 10 Dakika', teaching: 'Hareket disiplinin yarısı. Diğer yarısı durabilmek. 10 dakika tam stillness — kıpırdamadan, düşünmeden, yapmadan. Bedeniniz ve zihniniz reset.', action: 'Bugün 10 dk tam hareketsiz otur.', reflectionPrompt: 'Stillness ne kadar zor geldi?', proTip: 'Tam dik otur, gözleri %30 açık. Sırt yastığı al.' },
  33: { title: 'Soğuk Daldırma', teaching: 'Soğuk duş başlangıç. Soğuk daldırma master. 1-2 dk 10°C su = norepinefrin %500 artar, depresyon riski %29 düşer (Wim Hof). Vücudun 10x güçlenir.', action: 'Bugün soğuk duşu 1 dakikaya çıkar.', reflectionPrompt: '1 dakikada bedenim ne öğrendi?', proTip: 'Nefes kontrolü ile gir. Şok = nefesi tut yapar; tam tersi: derin yavaş nefes.' },
  34: { title: 'Güneş Selamı Varyasyonları', teaching: 'Sun salutation = 12 hareket, tüm vücut esnetme + güç. Sabah 5 dakika = ısınma + esneme + omuz açılışı. Yoga değil disiplindir.', action: 'Bugün 5 sun salutation yap.', reflectionPrompt: 'Hangi pozisyon zorluydu?', proTip: 'YouTube\'da "5 min sun salutation" video. İlk 1 hafta video ile, sonra ezberle.' },
  35: { title: 'Tek Sayfa Günlük', teaching: 'Morning pages 3 sayfa zor. Tek sayfa yapılabilir. Her sabah aynı tek sayfa: bugün niyetim, dünden ne öğrendim, bugünün 3 önceliği.', action: 'Bugün tek sayfa günlük yaz. Yargılamadan.', reflectionPrompt: 'Tek sayfa yazınca zihninde ne değişti?', proTip: 'Sabit format kullan: niyet / öğrenme / öncelik. Karar yorgunluğu azaltır.' },
  36: { title: 'Affirmasyon Pratiği', teaching: 'Affirmasyonlar = kendi kendine sözler. "Disiplinliyim. Odaklıyım. Sürdürürüm." 5 dakika tekrar. Beyin tekrara inanır, gerçeğe değil.', action: 'Bugün 5 dakika 3 affirmasyon tekrar et.', reflectionPrompt: 'En çok hangi affirmasyon vurdu?', proTip: 'Aynaya bakarak yüksek sesle söyle. Etkisi 3x güçlenir.' },
  37: { title: 'Görselleştirme 3 Dakika', teaching: 'Görselleştirme dersini 3 dakikalık günlük rutine al. Hedef gerçekleşmiş gibi gör — duygular, sesler, kokular. Beyin "başardım" zaten der.', action: 'Bugün 3 dk hedefini görselleştir, sabah ilk şey.', reflectionPrompt: 'Görselleştirmede en canlı detay neydi?', proTip: 'Yatakta yap. Gözler kapalı, dik otur, derin nefes.' },
  38: { title: 'Hedef Günlük Review', teaching: 'Yıllık hedef yazıp unutmak = 0 etki. Günlük 30 saniye okumak = sürekli farkındalık. Hedef cebinde gibi olur — her küçük karar onu destekler.', action: 'Bugün ana hedefini sabah 30 saniye oku.', reflectionPrompt: 'Hedefi okuyunca öncelikler değişti mi?', proTip: 'Hedefi telefon kilit ekranı yap. Günde 50x bakacaksın.' },
  39: { title: 'Enerji Auditi', teaching: 'Sabah enerji 10/10 olmazsa sebep var. Geç yatma, alkol, ağır akşam yemeği, stres. Her sabah 1-10 puan ver. Düşük günleri analiz et.', action: 'Bugün sabah enerji puanı + sebebini yaz.', reflectionPrompt: 'Düşük enerjili günlerin ortak sebebi?', proTip: '7 gün boyunca yap, pattern ortaya çıkar. Optimum öğrenme yaşam tarzı.' },
  40: { title: 'Uyku Döngüsü Takibi', teaching: '8 saat = mit. Önemli olan döngü sayısı. 1 döngü = 90 dakika. 4-5 döngü ideal. Yatma saati / 1.5 = uyanma saati. 22:00 → 5:30 = 5 döngü.', action: 'Bugün döngü hesabıyla uyu. 22:00 → 05:30.', reflectionPrompt: 'Döngü hesabıyla uyku farklı mıydı?', proTip: 'Apple Watch / Whoop = otomatik takip. Yoksa manuel.' },
  41: { title: 'Alarmsız Uyanma', teaching: 'Alarmla uyanmak = beyni şok etme. 30 gün düzenli uyku sonrası beden alarmsız uyanır. Alarmı 6:00\'a kur, 5:55\'te alarm öncesi uyan = master.', action: 'Bugün alarmdan 5 dk önce uyanmayı dene.', reflectionPrompt: 'Alarmsız uyandığında nasıl hissettin?', proTip: 'Aynı saatte yat — body clock keskinleşir.' },
  42: { title: 'Sabah Mantra', teaching: 'Tek cümle. Her sabah ilk düşünce. "Bugün disiplinli. Bugün odaklı. Bugün şükran." Her tekrar = beyin programlama.', action: 'Bugün kendi mantra cümleni yaz, 10 kez tekrar et.', reflectionPrompt: 'Hangi mantra seçtin?', proTip: 'Mantrayı duş aynasına yapıştır. Sabah otomatik gelir.' },
  43: { title: '5-AM Protokolü', teaching: 'Robin Sharma "5 AM Club": 5\'te kalk, ilk saat: 20 dk hareket / 20 dk pratik / 20 dk yansıma. 30 günde "the 1 percent" girersin.', action: 'Bugün 5\'te kalk, 60-20-20-20 dene.', reflectionPrompt: 'İlk 60 dakika hangi blok en güçlüydü?', proTip: 'Aşamalı geç: önce 7, sonra 6:30, sonra 6, sonra 5:30, sonra 5.' },
  44: { title: 'İleri Seviye Nefes', teaching: 'Wim Hof method: 30 derin nefes + nefes tutma + 15 sn tutma + tekrar. 3 round = bağışıklık güçlenir, depresyon azalır, dayanıklılık artar.', action: 'Bugün 1 round Wim Hof yap.', reflectionPrompt: 'Nefes kontrolü zihnini değiştirdi mi?', proTip: 'YouTube "Wim Hof basic" + uygulamadan 1 hafta sonra denemeye geç.' },
  45: { title: 'Soğuk Maruz Mastery', teaching: 'Soğuk vücut için seroni-norepi-dopamin patlaması. Her gün soğuk = bağışıklık 10x. Hedef: 2 dk altında 10°C, 30 gün sürdür.', action: 'Bugün 2 dk soğuk duş yap.', reflectionPrompt: '2 dk sonu zihinsel net mi?', proTip: 'İlk 30 sn nefesi kontrol et — sonrası kolaylaşır.' },
  46: { title: 'Hareket Atıştırmaları', teaching: 'Saat başı 30 sn hareket = oturmanın etkisi nötrlenir. 10 squat, omuz daireleri, boyun esnetme. Çalışma sırasında saat başı yap.', action: 'Bugün her saat başı 30 sn hareket et.', reflectionPrompt: 'Akşam enerjin farklı mıydı?', proTip: 'Saat başı hatırlatıcı kur. 7 gün sonra otomatik olur.' },
  47: { title: 'Kimlik Mantra', teaching: '"Erken kalkıyorum" geçici. "Ben sabah insanıyım" kalıcı. Kimlik mantra = davranışın değil kimliğin tekrarı. Beyin "ben buyum" der ve davranış uyar.', action: 'Bugün kimlik mantranı yaz, 30 gün her sabah söyle.', reflectionPrompt: 'Kimlik vs davranış farkını nasıl hissediyorsun?', proTip: 'Mantrayı "Ben ___" ile başlat. Şimdiki zaman.' },
  48: { title: 'Final Sprint', teaching: 'Son 3 gün. 50 günde sabahların kaotikten sistematik dönüştü. Bu son sprint = locked-in. Yarın master\'sın.', action: 'Bugün son sprintin niyetini yaz.', reflectionPrompt: 'Niyetin sürdürebilir mi?', proTip: 'Niyet fotoğraf çek, telefona kaydet.' },
  49: { title: '49 Gün İçinde', teaching: '49 günde sabahların gözardı edilmez güç. Erken kalkmak artık zorlama değil. Sessizlik artık huzur. 10 değişiklik listesi yap.', action: 'Bugün 49 günde değişen 10 sabah ritüelini yaz.', reflectionPrompt: 'En unutulmaz değişim?', proTip: 'Listeyi profile picture\'a yaz, hatırlatma.' },
  50: { title: 'Master Tamamlandı', teaching: '50 sabah. Her biri kanıt. Sen değiştin — sabahların değişti çünkü. Yeni baseline: sistematik, sessiz, niyetli. Disiplin = kimlik şimdi.', action: 'Bugün aynaya bak. Yeni Sen\'i selamla.', reflectionPrompt: '50 sabah önce sen şimdi olmak ister miydi?', proTip: '7 gün dinlen, sonra mind veya body discipline path.' },
};

const NEW_EN = {
  31: { title: 'Walking Meditation', teaching: 'Sitting meditation is hard. Walking meditation is natural. Each step = breath. Each step = awareness. 10 min morning walking meditation = 1 hour sitting equivalent.', action: 'Today do 10 min walking meditation. Count each step.', reflectionPrompt: 'Was walking meditation different from sitting?', proTip: 'Inhale through nose, exhale mouth. One breath every 4 steps.' },
  32: { title: 'Stillness 10 Min', teaching: 'Movement is half of discipline. Other half is stillness. 10 minutes of full stillness — no move, no thought, no doing. Body and mind reset.', action: 'Today sit fully still for 10 min.', reflectionPrompt: 'How hard was stillness?', proTip: 'Sit fully upright, eyes 30% open. Use a back cushion.' },
  33: { title: 'Cold Plunge', teaching: 'Cold shower is start. Cold plunge is master. 1-2 min in 10°C water = +500% norepinephrine, -29% depression risk (Wim Hof). Body 10x stronger.', action: 'Today extend cold shower to 1 minute.', reflectionPrompt: 'What did body learn in 1 minute?', proTip: 'Enter with breath control. Shock makes you hold breath; do opposite: deep slow breath.' },
  34: { title: 'Sun Salutation Variations', teaching: 'Sun salutation = 12 moves, full-body stretch + strength. 5 min in morning = warm-up + stretch + shoulder opener. Not yoga — discipline.', action: 'Today do 5 sun salutations.', reflectionPrompt: 'Which pose was hardest?', proTip: 'YouTube "5 min sun salutation" video. First week with video, then memorize.' },
  35: { title: 'Single-Page Journal', teaching: '3-page morning pages is hard. Single page is doable. Same single page each morning: today\'s intent, what I learned yesterday, today\'s top 3.', action: 'Today write a single-page journal. No judging.', reflectionPrompt: 'What changed mentally after one page?', proTip: 'Use fixed format: intent / learning / priority. Reduces decision fatigue.' },
  36: { title: 'Affirmation Practice', teaching: 'Affirmations = words to self. "I am disciplined. I am focused. I persist." 5 min repetition. Brain believes repetition, not truth.', action: 'Today repeat 3 affirmations for 5 min.', reflectionPrompt: 'Which affirmation hit hardest?', proTip: 'Speak aloud in mirror. Effect 3x stronger.' },
  37: { title: 'Visualization 3 Min', teaching: 'Take visualization lesson and make it a 3-min daily ritual. See goal as if achieved — emotions, sounds, smells. Brain says "I succeeded."', action: 'Today visualize goal for 3 min, first thing in morning.', reflectionPrompt: 'Most vivid detail in visualization?', proTip: 'Do it in bed. Eyes closed, sit upright, deep breath.' },
  38: { title: 'Daily Goal Review', teaching: 'Writing yearly goal then forgetting = zero effect. 30 sec daily reading = constant awareness. Goal lives in pocket — every small decision supports it.', action: 'Today read your main goal for 30 sec in morning.', reflectionPrompt: 'Did priorities shift after reading the goal?', proTip: 'Goal as phone lock screen. You\'ll see it 50x daily.' },
  39: { title: 'Energy Audit', teaching: 'Morning energy != 10/10 has reasons. Late bedtime, alcohol, heavy dinner, stress. Score 1-10 each morning. Analyze low days.', action: 'Today write morning energy score + reason.', reflectionPrompt: 'Common cause of low-energy days?', proTip: 'Do 7 days, pattern emerges. Optimum-learning lifestyle.' },
  40: { title: 'Sleep Cycle Tracking', teaching: '8 hours = myth. What matters is cycle count. 1 cycle = 90 min. 4-5 ideal. Bedtime / 1.5 = wake time. 22:00 → 5:30 = 5 cycles.', action: 'Today sleep with cycle math. 22:00 → 05:30.', reflectionPrompt: 'Was sleep different with cycle math?', proTip: 'Apple Watch / Whoop = auto-track. Else manual.' },
  41: { title: 'Wake Without Alarm', teaching: 'Alarm wake = brain shock. After 30 days regular sleep, body wakes alarm-less. Alarm at 6:00, you wake at 5:55 = master.', action: 'Today try waking 5 min before alarm.', reflectionPrompt: 'How did alarm-less wake feel?', proTip: 'Sleep at same time — body clock sharpens.' },
  42: { title: 'Morning Mantra', teaching: 'One sentence. First thought every morning. "Today disciplined. Today focused. Today grateful." Each repetition = brain programming.', action: 'Today write your mantra, repeat 10 times.', reflectionPrompt: 'Which mantra did you pick?', proTip: 'Stick mantra on bathroom mirror. Morning auto-arrives.' },
  43: { title: '5-AM Protocol', teaching: 'Robin Sharma "5 AM Club": wake at 5, first hour: 20 min movement / 20 min practice / 20 min reflection. 30 days = "the 1 percent."', action: 'Today wake at 5, try the 60-20-20-20.', reflectionPrompt: 'Which 60-min block was strongest?', proTip: 'Step gradually: first 7, then 6:30, 6, 5:30, 5.' },
  44: { title: 'Advanced Breath', teaching: 'Wim Hof method: 30 deep breaths + breath-hold + 15 sec hold + repeat. 3 rounds = immunity strengthens, depression drops, endurance up.', action: 'Today do 1 round Wim Hof.', reflectionPrompt: 'Did breath control change your mind?', proTip: 'YouTube "Wim Hof basic" + try after 1 week of practice.' },
  45: { title: 'Cold Mastery', teaching: 'Cold for body = sero-norepi-dopa explosion. Daily cold = immunity 10x. Goal: under 2 min at 10°C, 30 days sustained.', action: 'Today do 2-min cold shower.', reflectionPrompt: 'Mental clarity after 2 min?', proTip: 'First 30 sec control breath — rest gets easier.' },
  46: { title: 'Movement Snacks', teaching: 'Hourly 30 sec movement = sitting effect neutralized. 10 squats, shoulder circles, neck stretch. Do it during work hourly.', action: 'Today move for 30 sec every hour.', reflectionPrompt: 'Was your evening energy different?', proTip: 'Hourly reminder. After 7 days becomes automatic.' },
  47: { title: 'Identity Mantra', teaching: '"I wake early" is temporary. "I am a morning person" is permanent. Identity mantra = repetition of identity, not behavior. Brain says "this is me" and behavior follows.', action: 'Today write identity mantra, say each morning for 30 days.', reflectionPrompt: 'How does identity vs behavior feel different?', proTip: 'Start with "I am ___." Present tense.' },
  48: { title: 'Final Sprint', teaching: 'Last 3 days. 50 days transformed mornings from chaos to systematic. This last sprint = locked-in. Tomorrow you are master.', action: 'Today write final-sprint intent.', reflectionPrompt: 'Is your intent sustainable?', proTip: 'Photo the intent, save in phone.' },
  49: { title: '49 Days In', teaching: 'In 49 days mornings are undeniable strength. Early rising no longer forced. Silence is now peace. Make a 10-change list.', action: 'Today list 10 morning rituals that changed in 49 days.', reflectionPrompt: 'Most unforgettable change?', proTip: 'Write list as profile picture, reminder.' },
  50: { title: 'Master Complete', teaching: '50 mornings. Each one proof. You changed — your mornings changed because of it. New baseline: systematic, silent, intent. Discipline = identity now.', action: 'Today look in mirror. Greet New You.', reflectionPrompt: 'Would 50-mornings-ago you want to be now?', proTip: 'Rest 7 days, then mind or body discipline path.' },
};

const QUIZ_TR = {
  31: [{ q: 'Yürüyüş meditasyonu vs oturma?', options: ['Aynı', 'Yürüyüş daha doğal', 'Yürüyüş zayıf', 'Bilinmez'], correct: 1, explain: 'Hareket + farkındalık birleştirir.' }, { q: 'Süre?', options: ['1 dk', '10 dk = 1 saat', '1 saat', '5 dk'], correct: 1, explain: '10 dk yürüme = 1 saat oturma denkliği.' }],
  32: [{ q: 'Stillness ne demek?', options: ['Hareket', 'Tam hareketsiz', 'Yorgun', 'Pasif'], correct: 1, explain: 'Düşünme, yapma yok.' }, { q: 'Süre?', options: ['1 dk', '10 dk', '1 saat', 'Tüm gün'], correct: 1, explain: '10 dk reset.' }],
  33: [{ q: 'Soğuk daldırma süre?', options: ['10 sn', '1-2 dk', '10 dk', '1 saat'], correct: 1, explain: '1-2 dakika master seviyesi.' }, { q: 'Norepinefrin artışı?', options: ['%10', '%500', 'Yok', 'Negatif'], correct: 1, explain: '%500 artış (Wim Hof).' }],
  34: [{ q: 'Sun salutation kaç hareket?', options: ['3', '12', '50', '100'], correct: 1, explain: '12 hareket dizisi.' }, { q: 'Süre öneri?', options: ['30 sn', '5 dk', '1 saat', 'Yok'], correct: 1, explain: '5 dk yeterli.' }],
  35: [{ q: 'Tek sayfa günlük format?', options: ['Belirsiz', 'Niyet/öğrenme/öncelik', 'Random', 'Boş'], correct: 1, explain: 'Sabit format = az karar yorgunluğu.' }, { q: 'Avantajı?', options: ['Pahalı', 'Tutarlı', 'Yorucu', 'Etkisiz'], correct: 1, explain: 'Tutarlılık = uzun vade.' }],
  36: [{ q: 'Affirmasyon süre?', options: ['1 sn', '5 dk', '1 saat', 'Yok'], correct: 1, explain: '5 dk pratik.' }, { q: 'Aynaya söylemek?', options: ['Etkisiz', '3x güç', 'Risk', 'Pahalı'], correct: 1, explain: 'Aynalı = 3x etki.' }],
  37: [{ q: 'Görselleştirme süre?', options: ['1 dk', '3 dk', '1 saat', '0'], correct: 1, explain: '3 dk yeterli.' }, { q: 'En iyi yer?', options: ['Sokak', 'Yatak', 'Ofis', 'Otobüs'], correct: 1, explain: 'Yatakta gözler kapalı.' }],
  38: [{ q: 'Hedef günlük review süre?', options: ['30 sn', '1 saat', '1 hafta', 'Hiç'], correct: 0, explain: '30 saniye yeterli.' }, { q: 'Optimum yer?', options: ['Defter', 'Telefon kilit ekranı', 'Cüzdan', 'Bellek'], correct: 1, explain: 'Günde 50x bakacaksın.' }],
  39: [{ q: 'Enerji audit ölçek?', options: ['Yok', '1-10 puan', '0-1', 'Renkli'], correct: 1, explain: '10 üzerinden puanla.' }, { q: 'Pattern ne kadarda çıkar?', options: ['1 gün', '7 gün', '1 ay', '1 yıl'], correct: 1, explain: '7 gün = pattern.' }],
  40: [{ q: '1 uyku döngüsü?', options: ['30 dk', '90 dk', '4 saat', '8 saat'], correct: 1, explain: '90 dk = 1 cycle.' }, { q: 'Optimum cycle?', options: ['1', '4-5', '10', '20'], correct: 1, explain: '4-5 cycle ideal.' }],
  41: [{ q: 'Alarmsız uyanma?', options: ['Imkansız', '30 gün regular sonra', 'Hep', 'Asla'], correct: 1, explain: 'Beden saat ayarlanır.' }, { q: 'Anahtar?', options: ['Erken yat', 'Aynı saatte yat', 'Geç yat', 'Random'], correct: 1, explain: 'Sabit yatma = sabit kalkma.' }],
  42: [{ q: 'Mantra format?', options: ['Liste', 'Tek cümle', 'Roman', 'Şarkı'], correct: 1, explain: 'Tek cümle, tekrar.' }, { q: 'Tekrar sayısı?', options: ['1', '10', '100', '1000'], correct: 1, explain: '10 tekrar yeter.' }],
  43: [{ q: '5-AM Club kim?', options: ['Naval', 'Robin Sharma', 'James Clear', 'Tim Ferriss'], correct: 1, explain: 'Robin Sharma kitabı.' }, { q: '60-20-20-20?', options: ['Spor + pratik + yansıma', 'Sadece spor', 'Sadece okuma', 'Yok'], correct: 0, explain: '20 hareket + 20 pratik + 20 yansıma.' }],
  44: [{ q: 'Wim Hof temel?', options: ['Yavaş nefes', '30 deep + hold', 'Egzersiz', 'Soğuk'], correct: 1, explain: '30 nefes + hold + repeat.' }, { q: 'Round sayısı?', options: ['1', '3', '10', '100'], correct: 1, explain: '3 round optimum.' }],
  45: [{ q: 'Soğuk hedef süresi?', options: ['10 sn', '2 dk', '10 dk', '1 saat'], correct: 1, explain: '2 dakika master.' }, { q: 'İlk 30 sn?', options: ['Pasif', 'Nefes kontrolü', 'Bağır', 'Çık'], correct: 1, explain: 'Nefesle yumuşat.' }],
  46: [{ q: 'Hareket atıştırması süre?', options: ['1 sn', '30 sn', '5 dk', '1 saat'], correct: 1, explain: 'Saat başı 30 sn.' }, { q: 'Etki?', options: ['Yok', 'Oturmayı nötrler', 'Yorgunluk', 'Acı'], correct: 1, explain: 'Oturmanın hasarını siler.' }],
  47: [{ q: 'Kimlik mantra başlangıcı?', options: ['Olucam', 'Ben ___', 'Belki', 'Olmaz'], correct: 1, explain: '"Ben" = şimdiki zaman.' }, { q: 'Davranış mı kimlik mi?', options: ['Davranış', 'Kimlik kalıcı', 'Aynı', 'Bilinmez'], correct: 1, explain: 'Kimlik = uzun vade.' }],
  48: [{ q: 'Final sprint süre?', options: ['1 gün', '3 gün', '1 ay', 'Hiç'], correct: 1, explain: 'Son 3 gün master locking.' }, { q: 'Niyet nereye?', options: ['Kafa', 'Telefon foto', 'Çöp', 'Unut'], correct: 1, explain: 'Foto = görünür.' }],
  49: [{ q: '49 günde değişen?', options: ['Hiç', '10+ ritüel', '1 şey', 'Görünmez'], correct: 1, explain: 'Çok değişiklik.' }, { q: 'Liste yer?', options: ['Çek defteri', 'Profile picture', 'Kafa', 'Çöp'], correct: 1, explain: 'Görünür hatırlatma.' }],
  50: [{ q: 'Yeni baseline ne?', options: ['Eski', 'Sistematik+sessiz+niyetli', 'Yorgun', 'Bilinmez'], correct: 1, explain: 'Master sabah profili.' }, { q: 'Disiplin = ?', options: ['Davranış', 'Kimlik', 'Plan', 'Motivasyon'], correct: 1, explain: 'Artık kimlik = disiplin.' }],
};

const QUIZ_EN = {
  31: [{ q: 'Walking vs sitting meditation?', options: ['Same', 'Walking more natural', 'Walking weak', 'Unknown'], correct: 1, explain: 'Movement + awareness combined.' }, { q: 'Duration?', options: ['1 min', '10 min = 1 hour', '1 hour', '5 min'], correct: 1, explain: '10 walk = 1 hour sitting equivalent.' }],
  32: [{ q: 'Stillness means?', options: ['Movement', 'Fully still', 'Tired', 'Passive'], correct: 1, explain: 'No thought, no doing.' }, { q: 'Duration?', options: ['1 min', '10 min', '1 hour', 'All day'], correct: 1, explain: '10 min reset.' }],
  33: [{ q: 'Cold plunge duration?', options: ['10 sec', '1-2 min', '10 min', '1 hour'], correct: 1, explain: '1-2 min master level.' }, { q: 'Norepinephrine increase?', options: ['10%', '500%', 'None', 'Negative'], correct: 1, explain: '500% rise (Wim Hof).' }],
  34: [{ q: 'Sun salutation moves?', options: ['3', '12', '50', '100'], correct: 1, explain: '12-move sequence.' }, { q: 'Duration?', options: ['30 sec', '5 min', '1 hour', 'No'], correct: 1, explain: '5 min suffices.' }],
  35: [{ q: 'Single page format?', options: ['Vague', 'Intent/learning/priority', 'Random', 'Empty'], correct: 1, explain: 'Fixed format = less decision fatigue.' }, { q: 'Advantage?', options: ['Expensive', 'Consistent', 'Tiring', 'No effect'], correct: 1, explain: 'Consistency = long-term.' }],
  36: [{ q: 'Affirmation duration?', options: ['1 sec', '5 min', '1 hour', 'No'], correct: 1, explain: '5 min practice.' }, { q: 'Mirror speaking?', options: ['No effect', '3x power', 'Risk', 'Expensive'], correct: 1, explain: 'Mirror = 3x effect.' }],
  37: [{ q: 'Visualization duration?', options: ['1 min', '3 min', '1 hour', '0'], correct: 1, explain: '3 min suffices.' }, { q: 'Best place?', options: ['Street', 'Bed', 'Office', 'Bus'], correct: 1, explain: 'In bed, eyes closed.' }],
  38: [{ q: 'Goal review duration?', options: ['30 sec', '1 hour', '1 week', 'Never'], correct: 0, explain: '30 sec sufficient.' }, { q: 'Optimal place?', options: ['Journal', 'Phone lock screen', 'Wallet', 'Memory'], correct: 1, explain: 'See it 50x daily.' }],
  39: [{ q: 'Energy audit scale?', options: ['No', '1-10 score', '0-1', 'Color'], correct: 1, explain: 'Score out of 10.' }, { q: 'Pattern emerges?', options: ['1 day', '7 days', '1 month', '1 year'], correct: 1, explain: '7 days = pattern.' }],
  40: [{ q: '1 sleep cycle?', options: ['30 min', '90 min', '4 hours', '8 hours'], correct: 1, explain: '90 min = 1 cycle.' }, { q: 'Optimal cycles?', options: ['1', '4-5', '10', '20'], correct: 1, explain: '4-5 cycles ideal.' }],
  41: [{ q: 'Wake without alarm?', options: ['Impossible', 'After 30 days regular', 'Always', 'Never'], correct: 1, explain: 'Body clock adjusts.' }, { q: 'Key?', options: ['Sleep early', 'Same bedtime', 'Late', 'Random'], correct: 1, explain: 'Fixed bed = fixed wake.' }],
  42: [{ q: 'Mantra format?', options: ['List', 'Single sentence', 'Novel', 'Song'], correct: 1, explain: 'Single sentence, repeat.' }, { q: 'Repeat count?', options: ['1', '10', '100', '1000'], correct: 1, explain: '10 reps enough.' }],
  43: [{ q: '5-AM Club author?', options: ['Naval', 'Robin Sharma', 'James Clear', 'Tim Ferriss'], correct: 1, explain: 'Robin Sharma book.' }, { q: '60-20-20-20?', options: ['Sport + practice + reflect', 'Only sport', 'Only reading', 'No'], correct: 0, explain: '20 movement + 20 practice + 20 reflection.' }],
  44: [{ q: 'Wim Hof basics?', options: ['Slow breath', '30 deep + hold', 'Exercise', 'Cold'], correct: 1, explain: '30 breaths + hold + repeat.' }, { q: 'Round count?', options: ['1', '3', '10', '100'], correct: 1, explain: '3 rounds optimum.' }],
  45: [{ q: 'Cold target duration?', options: ['10 sec', '2 min', '10 min', '1 hour'], correct: 1, explain: '2 min master.' }, { q: 'First 30 sec?', options: ['Passive', 'Breath control', 'Scream', 'Exit'], correct: 1, explain: 'Soften with breath.' }],
  46: [{ q: 'Movement snack duration?', options: ['1 sec', '30 sec', '5 min', '1 hour'], correct: 1, explain: 'Hourly 30 sec.' }, { q: 'Effect?', options: ['No', 'Neutralizes sitting', 'Tired', 'Pain'], correct: 1, explain: 'Erases sitting damage.' }],
  47: [{ q: 'Identity mantra start?', options: ['Will be', 'I am ___', 'Maybe', 'Won\'t'], correct: 1, explain: '"I am" = present.' }, { q: 'Behavior or identity?', options: ['Behavior', 'Identity permanent', 'Same', 'Unknown'], correct: 1, explain: 'Identity = long-term.' }],
  48: [{ q: 'Final sprint duration?', options: ['1 day', '3 days', '1 month', 'No'], correct: 1, explain: 'Last 3 = master locking.' }, { q: 'Intent where?', options: ['Head', 'Phone photo', 'Trash', 'Forget'], correct: 1, explain: 'Photo = visible.' }],
  49: [{ q: '49-day changes?', options: ['None', '10+ rituals', '1 thing', 'Invisible'], correct: 1, explain: 'Many changes.' }, { q: 'List location?', options: ['Drawer', 'Profile picture', 'Head', 'Trash'], correct: 1, explain: 'Visible reminder.' }],
  50: [{ q: 'New baseline?', options: ['Old', 'Systematic+silent+intent', 'Tired', 'Unknown'], correct: 1, explain: 'Master morning profile.' }, { q: 'Discipline = ?', options: ['Behavior', 'Identity', 'Plan', 'Motivation'], correct: 1, explain: 'Now identity = discipline.' }],
};

function buildLessons(c, q) { const o = {}; for (const [k, v] of Object.entries(c)) o[k] = { ...v, quiz: q[k] || [] }; return o; }
function applyToFile(filePath, pathId, m) { const d = JSON.parse(fs.readFileSync(filePath, 'utf8')); if (!d.lessons[pathId]) d.lessons[pathId] = {}; for (const [k, v] of Object.entries(m)) d.lessons[pathId][k] = { ...(d.lessons[pathId][k] || {}), ...v }; fs.writeFileSync(filePath, JSON.stringify(d, null, 2) + '\n'); }
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.tr.json'), 'silent-morning', buildLessons(NEW_TR, QUIZ_TR));
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.en.json'), 'silent-morning', buildLessons(NEW_EN, QUIZ_EN));
console.log(`✓ Silent-morning 31-50 seeded — ${Object.keys(NEW_TR).length} new lessons × 2 langs`);
