/**
 * Seed money-discipline lessons 6-30 (25 new) + add proTip to 1-5.
 * Run: node scripts/seed_money_discipline.js
 */
const fs = require('fs');
const path = require('path');

const PROTIPS_TR = {
  1: 'Banka ekstresinin son 3 ayını yan yana koy. Tekrar eden harcamalar görünür olur.',
  2: '50/30/20\'yi 1 ay sıkı uygula, sonra esnetebilirsin. İlk ay temel oturmazsa esneklik anlamsız.',
  3: '24 saat geçtikten sonra hala istediğini almak istiyorsan, gerçekten istediğindir. Çoğu için cevap "hayır" gelir.',
  4: 'Evde pişirmek karmaşık olmak zorunda değil. 4 hareket: doğra, kavur, baharatla, ye.',
  5: 'Acil fonu erişilemez yere koy: ayrı banka, ayrı kart. "Görünür" para harcanır.',
};
const PROTIPS_EN = {
  1: 'Lay 3 months of bank statements side by side. Recurring charges become visible.',
  2: 'Apply 50/30/20 strictly 1 month, then flex. Without baseline, flex is meaningless.',
  3: 'After 24 hours, if you still want it, you really want it. Most often the answer is "no."',
  4: 'Cooking at home need not be complex. 4 moves: chop, sauté, season, eat.',
  5: 'Park emergency fund out of reach: separate bank, separate card. "Visible" money gets spent.',
};

const NEW_TR = {
  6: { title: 'Net Servet Tarama', teaching: 'Çoğu insan kendi servetini bilmez. Net servet = varlık (nakit, yatırım, gayrimenkul) - borç (kredi, kart, kredi kartı). Bu sayı senin gerçek finansal hayatın. Yıl sonu vs yıl başı: artıyor mu, azalıyor mu?', action: 'Bugün net servetini hesapla. Excel\'e yaz, fotoğrafını çek.', reflectionPrompt: 'Net servetin beklediğinden ne kadar farklı çıktı?', proTip: 'Aylık net servet takibi yap. Yıllık değişim = gerçek gelişimin göstergesi.' },
  7: { title: 'Abonelik Denetimi', teaching: 'Ortalama insan farkında olmadan 7-12 abonelik öder: streaming, app, gym, dergi, premium servis. 1 yılda 5.000-15.000 TL. %50\'sini sen kullanmıyorsun. İptal et.', action: 'Bugün son 3 ayın kart ekstresini incele. Tüm abonelikleri listele.', reflectionPrompt: 'Şaşırtan kaç tane "uyuyan" abonelik buldun?', proTip: 'Truebill, Bobby gibi uygulamalar otomatik bulup iptal eder.' },
  8: { title: 'Latte Faktörü', teaching: 'Günde 50 TL kahve = ayda 1.500 TL = yılda 18.000 TL = 30 yılda 540.000 TL (faiz hariç). Yatırırsan: ~1.5 milyon TL. Küçük günlük "lüksler" emekliliğini yiyor.', action: 'Bugün otomatik küçük harcamalarını listele. Toplam aylık?', reflectionPrompt: 'Hangi "küçük" harcama aslında büyüktü?', proTip: 'Hepsini kesme — 1\'ini değiştir. Etki büyük olur.' },
  9: { title: 'Tek Hesap Stratejisi', teaching: 'Çok hesap = kafa karışıklığı. 1 ana hesap (gelir + günlük), 1 tasarruf hesabı (yatırılmaz), 1 yatırım hesabı (uzun vade). Kart sayısı: 1 günlük, 1 yedek. Daha fazla = karışıklık.', action: 'Bugün tüm hesaplarını listele. Gerekmeyen 1\'i kapat.', reflectionPrompt: 'Hesap sadeliği sana hangi mental yer açtı?', proTip: 'Birden fazla bankada gereksiz hesap = giriş şifresi yorgunluğu + yıllık ücret katmanları.' },
  10: { title: 'Otomatik Tasarruf', teaching: 'İrade gücüne güvenme. Otomasyona güven. Maaş geldiğinde önce %20 otomatik tasarruf hesabına geçsin. Sen kalanını yaşa. Görmediğin para = harcamadığın para.', action: 'Bugün maaşının %20\'sini otomatik transfer ayarla.', reflectionPrompt: 'Otomatik kesintinin hayatına etkisi nasıl olur?', proTip: 'Tasarruf hesabını başka bankada aç. Aynı bankada = "kolayca al" tehlikesi.' },
  11: { title: 'Önce Kendine Öde', teaching: 'Çoğu insan: önce harcar, kalanı tasarruf. Bu sıralama yanlış. Doğrusu: önce kendine öde (tasarruf/yatırım), kalanı harcamaya. Tek değişiklik = 10 yıl içinde milyonluk fark.', action: 'Bugün geliri alır almaz önce tasarrufa, sonra harcamalara dağıt.', reflectionPrompt: 'Sıralama değişikliği zihninde hangi cümleyi değiştirdi?', proTip: 'Maaş gününde "kendi maaşını öde" — kendine ilk fatura.' },
  12: { title: 'Borç Çığ Yöntemi', teaching: 'Birkaç borcun varsa: en yüksek faizli borca odaklan, diğerlerine minimum öde. En yüksek faizli bitince → bir sonrakine. Buna "çığ" denir. Matematiksel olarak en hızlı bitirir.', action: 'Bugün tüm borçlarını faiz oranına göre listele. Çığ planı yap.', reflectionPrompt: 'En yüksek faizli borcunu görmek nasıl hissettirdi?', proTip: 'Snowball metodu (küçükten büyüğe) psikolojik. Avalanche (yüksek faize) matematiksel. İkisi de işler — 1\'ini seç.' },
  13: { title: 'Kredi Kartı Disiplini', teaching: 'Kredi kartı = enstrüman. Kötü kullanılırsa kelepçe, iyi kullanılırsa kaldıraç. Kural: 1) Sadece zaten alınacak şeylere, 2) Tam miktarda öde, 3) Faiz ödeme. Yapamazsan kart kapat.', action: 'Bugün kredi kartı bakiyenle harcamalarını eşleştir. Açık var mı?', reflectionPrompt: 'Kart kullanımın disiplinli mi yoksa sömürüye mi açık?', proTip: 'Kredi kartını yanına alma — sadece bilinçli alışveriş için. Cüzdanda taşımayan harcamayı %15 azaltır.' },
  14: { title: 'Tutumlu Sevinç', teaching: 'Tutumluluk ≠ yoksulluk. Sürdürülemez tutumluluk = kısa süreli. Tutumlu sevinç: ucuza yapabildiğin keyifleri keşfet. Park yürüyüşü, ev yemeği, kütüphane kitabı, ev konseri. Pahalı = keyifli değildir.', action: 'Bugün 0 TL\'lik 1 büyük keyif yap.', reflectionPrompt: 'Para harcamadan en keyifli neyi yaptın?', proTip: 'Listele: 0 TL aktiviteler, 50 TL altı, 100 TL altı. 30 alternatif görmek = harcama refleksini kırar.' },
  15: { title: 'Bir Kez Kalite Al', teaching: 'Ucuz × 5 = pahalı. Pahalı × 1 = pahalı görünür ama daha ucuz. 200 TL\'lik 5 yılda biten ayakkabı vs 1.000 TL\'lik 20 yıl giyilen ayakkabı. Hesapla, kaliteyi seç.', action: 'Bugün bozulmaya yakın 1 ürünü daha kaliteli alternatife terfi et.', reflectionPrompt: 'Kaliteli alternatif uzun vadede ne kadar tasarruf eder?', proTip: 'Buy-it-for-life (BIFL) topluluklarına bak. Reddit\'te sınırsız öneri.' },
  16: { title: 'Haftalık Para Review', teaching: 'Para = ölçülmediği şey. Haftada 1 saat: gelir-gider tablosu, bütçe vs gerçek, hedeflerin durumu. 1 saat × 52 hafta = yılda 52 saat. Yıllık geliri belirleyen 52 saat.', action: 'Bu hafta para review için 30 dakika harca. Excel ya da defter.', reflectionPrompt: 'Haftalık review olmadan paran nasıl yönetilirdi?', proTip: 'Aynı gün-saat sabit tut. Pazar 09:00 ya da cumartesi 10:00. Esnek olma.' },
  17: { title: 'Gelir Çoğaltma', teaching: 'Tasarruf = sınırlı. Gelir = sınırsız. Tek geliri olmak risk. 2-3 gelir kanalı disiplinli kişinin profili: ana iş + freelance/online + yatırım geliri.', action: 'Bugün ana işin dışında 1 ek gelir fikrini araştır. Freelance, online satış, kira, dividend.', reflectionPrompt: 'En kolay başlatabileceğin ek gelir hangisi?', proTip: 'İlk hedef: ayda ekstra 5.000 TL. Bu kira ödemen = aylık 5K = yıllık 60K = ekstra emeklilik.' },
  18: { title: 'Yatırım 101: Endeks Fonları', teaching: 'Hisse seçmek zor — index fund kolay. Tüm pazarın küçük dilimi, ortalama %7-10 yıllık getiri (ABD), çok düşük komisyon. Warren Buffett: emekliliği için endeks fonu öner.', action: 'Bugün endeks fonunu (Türkiye için BIST 100, dünya için VOO/VT) araştır.', reflectionPrompt: 'Endeks fonu yatırım korkunu nasıl etkiledi?', proTip: 'Aylık küçük miktar (Dollar-cost averaging) > tek seferde büyük yatırım. Riski dağıtır.' },
  19: { title: 'Ek Gelir Disiplini', teaching: 'Ek gelir başlamak değil — sürdürmek zor. İlk 6 ay 0 TL kazanabilirsin. Çoğu vazgeçer. 12. ayda kazanmaya başlar. 24. ayda hayatını dönüştürür. Sürdürürsen.', action: 'Bugün ek gelir için 30 dakika ayır. Hiç para gelmese bile.', reflectionPrompt: 'Ek gelir başlatma korkun ne? Para kazanamamak mı, yargı mı?', proTip: 'Sosyal medyaya çıkma korkusu varsa, yazıyla başla. Medium, blog, newsletter.' },
  20: { title: 'Yaşam Tarzı Şişmesi', teaching: 'Maaş arttı = harcama arttı. Buna lifestyle inflation denir. %10 artış maaşa = %10 artış araba/kira/yemeğe. Net etkisi sıfır. Disiplin: artışın %50\'sini tasarrufa.', action: 'Bugün son maaş artışını incele. Nereye gitti?', reflectionPrompt: 'Lifestyle inflation\'a ne kadar düştün?', proTip: 'Yeni maaşla 3 ay aynı yaşa. Beden eski standardı normal kabul eder, fazlası tasarruf.' },
  21: { title: 'Pazarlık Becerisi', teaching: 'Pazarlık = batı kültüründe utanç verici, doğu\'da norm. Maaşta pazarlık = 1 saatlik tartışma = yılda 50K-200K fark. Pazarlık ucuz değil — kaçınılmaz. "Asıl rakam ne?" sor.', action: 'Bugün 1 fiyatı pazarlık et. Online da olsa: indirim kodu sor.', reflectionPrompt: 'Pazarlık denemen nasıl gitti? Korktuğun kadar zor mu?', proTip: '"Bu en iyi fiyatınız mı?" — sihir cümle. Çoğu zaman %5-15 indirim açar.' },
  22: { title: 'Vergi Farkındalığı', teaching: 'Vergi = en büyük yıllık harcaman. Çoğu insan vergi kanunlarını bilmez, indirim hakkını kullanmaz, fazla öder. 1-2 saat öğrenmek = yılda binlerce TL tasarruf.', action: 'Bugün vergi indirim haklarını araştır (eğitim, sağlık, bağış, kira).', reflectionPrompt: 'Hangi indirim hakkından haberdar değildin?', proTip: 'Mali müşavir 1 saatlik = 5.000 TL. Kazanır 50.000 TL\'yi.' },
  23: { title: 'Sigorta Disiplini', teaching: 'Sigorta = sıkıcı ama hayat kurtaran. Olmazsa olmaz: 1) Sağlık (özel poliçe), 2) Hayat (aile varsa), 3) Mesleki sorumluluk. Olmaması olmazsa olmaz: araba kasko + sandalye sigortası.', action: 'Bugün sigortalarını gözden geçir. Eksik mi, fazla mı?', reflectionPrompt: 'Sigortasız riskini taşıdığını fark ettiğin alan?', proTip: 'Yılda 1 kez sigortaları karşılaştır. Aynı koruma %30 daha ucuza bulunabilir.' },
  24: { title: 'Finansal Hedefler', teaching: 'Hedefsiz para = amacsız harcanır. Net hedef: "1 yıl sonra 50.000 TL acil fonu," "5 yıl sonra ev peşinatı," "10 yıl sonra emekli olacak kadar yatırım." Tarih + miktar + amaç.', action: 'Bugün 3 finansal hedef yaz. Kısa (1 yıl), orta (5 yıl), uzun (20+ yıl).', reflectionPrompt: 'Hangi hedef seni en çok motive ediyor?', proTip: 'Hedefleri görünür yere yaz: dolap içi, masa kenarı. Görünmek = hatırlatma.' },
  25: { title: 'Para Hikayeni Yeniden Yaz', teaching: 'Çocukluktan gelen "para hikayesi" finansal davranışını şekillendirir. "Para kötüdür," "zenginler hırsızdır," "biz zengin değiliz." Bu hikayeleri tanı, yenisini yaz: "Para araçtır, ben yaratıcıyım."', action: 'Bugün 5 dakika kendi para hikayeni yaz. Sonra yeni versiyonunu yaz.', reflectionPrompt: 'Eski para hikayen seni nasıl tutuyor?', proTip: 'Yeni hikaye 30 gün boyunca her sabah oku. Beyin tekrara inanır.' },
  26: { title: 'Harcama Farkındalığı', teaching: 'Çoğu harcama bilinçaltı: stres, sıkıntı, sosyal baskı, reklam tetikleyici. Farkındalık tek silah. Her harcama öncesi: "Bunu duygusal mı, gerçek ihtiyaçtan mı alıyorum?"', action: 'Bugün her harcama öncesi 10 saniye dur, niyetini sorgula.', reflectionPrompt: 'Hangi harcama duygusaldı? Niye?', proTip: 'Duygusal harcama = elin telefona gider, "şunu alayım" der. Eli durdur.' },
  27: { title: 'Bilinçli Para', teaching: 'Para = enerji + zaman değişimi. Her 100 TL = saatler emek. Bunu unutunca israf başlar. Hatırla: telefonun 30.000 TL = 100 saat çalışmış oldun. Telefonu hak ediyor mu?', action: 'Bugün bir alacak şeye baktığında çalışma saatine çevir. "100 saat" gözüne büyür mü, küçük mü gelir?', reflectionPrompt: 'Saate çevirince hangi alımın yeniden değerlendi?', proTip: 'Saatlik kazancını bil. 200 TL/saat ise 1.000 TL\'lik şey = 5 saatlik emek.' },
  28: { title: 'Kuşak Disiplini', teaching: 'Para disiplini sadece sen değil — çocuklarını etkiler. Servet 3 kuşakta yok olur eğer disiplin geçmezse. Onları "para konuşmasından" uzak tutmak = miras değil yük.', action: 'Bugün ailenle 1 finansal konu konuş. Bütçe, hedef, yatırım — fark etmez.', reflectionPrompt: 'Aile içi para tabusu hangi konularda var?', proTip: 'Çocuklarına maaş + bütçe örneği göster. Para okur-yazarlığı en değerli miras.' },
  29: { title: 'Final Sprint', teaching: '29 gün boyunca para disiplini pratik ettin. Yarın "tamamladın." Ama para yarınla bitmiyor. Final test: bu 30 günde işe yarayan en güçlü 1 alışkanlığı seç. 100 gün daha.', action: 'Bugün 30 günün en güçlü 1 para disiplinini seç. Hangisi?', reflectionPrompt: 'Niye bu disiplini seçtin? Hangi sonucu verdi?', proTip: 'Otomatik tasarruf en kolay sürdürülebilen. İrade gücü yok, sistem var.' },
  30: { title: 'Tamamlandı — Yeni Para', teaching: '30 gün önce parayla ilişki bulanıktı. Şimdi: net servet, bütçe, hedefler net. Para sahibi sen değildin — şimdi sensin. Bu sabah aynaya bak: yeni bir finansal kimlik.', action: 'Bugün 30 günün özetini yaz: 3 öğrendiğim, 3 sürdüreceğim, 3 unutmayacağım.', reflectionPrompt: 'Yeni para zihninle hangi finansal hedefi yakalayacaksın?', proTip: 'Bir sonraki yola 3 gün dinlendikten sonra geç. Tutarlılık = kalıcılık.' },
};

const NEW_EN = {
  6: { title: 'Net Worth Audit', teaching: 'Most people don\'t know their own wealth. Net worth = assets (cash, investments, real estate) - liabilities (loans, cards). This number is your real financial life. Year-over-year: growing or shrinking?', action: 'Today calculate your net worth. Excel it, screenshot it.', reflectionPrompt: 'How different was the result from your guess?', proTip: 'Track monthly. Yearly change = real progress meter.' },
  7: { title: 'Subscription Audit', teaching: 'Average person pays 7-12 forgotten subscriptions: streaming, app, gym, magazine, premium service. 1 year = $200-500. 50% you don\'t use. Cancel.', action: 'Today review last 3 months of card statements. List all subscriptions.', reflectionPrompt: 'How many "sleeping" subscriptions surprised you?', proTip: 'Apps like Truebill / Bobby auto-find and cancel them.' },
  8: { title: 'Latte Factor', teaching: '$5 daily coffee = $150/month = $1,800/year = $54,000 in 30 years (no interest). Invested = ~$160K. Tiny daily "luxuries" eat your retirement.', action: 'Today list automatic small expenses. Total monthly?', reflectionPrompt: 'Which "small" expense was actually big?', proTip: 'Don\'t cut all — change 1. Big effect.' },
  9: { title: 'Single Account Strategy', teaching: 'Many accounts = mental noise. 1 main (income + daily), 1 savings (untouched), 1 investment (long-term). Cards: 1 daily, 1 backup. More = clutter.', action: 'Today list all accounts. Close 1 unnecessary.', reflectionPrompt: 'What mental space did account simplicity open?', proTip: 'Multiple banks for unused accounts = login fatigue + annual fee layers.' },
  10: { title: 'Automate Savings', teaching: 'Don\'t trust willpower. Trust automation. When salary lands, 20% auto-transfers to savings. You live the rest. Money you don\'t see = money you don\'t spend.', action: 'Today set 20% auto-transfer of salary to savings.', reflectionPrompt: 'How would auto-deduction change your life?', proTip: 'Open savings at a different bank. Same bank = "easy access" risk.' },
  11: { title: 'Pay Yourself First', teaching: 'Most people: spend first, save what\'s left. Wrong order. Correct: pay yourself first (savings/investing), then expenses. One change = millions difference in 10 years.', action: 'Today on receiving income, route to savings first, expenses second.', reflectionPrompt: 'How did the order shift change your inner sentence?', proTip: 'On payday, "pay your own salary" — first invoice to yourself.' },
  12: { title: 'Debt Avalanche', teaching: 'Multiple debts? Focus on highest-interest first, minimum on others. When done → next highest. Called "avalanche." Mathematically the fastest.', action: 'Today list all debts by interest rate. Plan the avalanche.', reflectionPrompt: 'How did seeing the highest-interest debt feel?', proTip: 'Snowball (smallest first) is psychological. Avalanche (highest interest) is math. Both work — pick one.' },
  13: { title: 'Credit Card Discipline', teaching: 'Credit card = instrument. Misused = handcuff, used right = leverage. Rule: 1) Only on already-planned purchases, 2) Pay full, 3) No interest. Can\'t? Close it.', action: 'Today match credit card balance with expenses. Any gap?', reflectionPrompt: 'Are you disciplined or exposed to exploitation?', proTip: 'Don\'t carry it — only for intentional purchases. Out-of-wallet cuts spending 15%.' },
  14: { title: 'Frugal Joy', teaching: 'Frugality ≠ poverty. Unsustainable frugality = short-lived. Frugal joy: discover cheap pleasures. Park walk, home cooking, library book, home concert. Expensive ≠ joyful.', action: 'Today do 1 big enjoyment that costs $0.', reflectionPrompt: 'What gave you joy without cost?', proTip: 'List 30 alternatives: $0, <$5, <$10. Seeing options breaks spending reflex.' },
  15: { title: 'Buy Quality Once', teaching: 'Cheap × 5 = expensive. Expensive × 1 = looks pricey but cheaper. $40 shoes lasting 5 years vs $200 shoes lasting 20. Calculate, choose quality.', action: 'Today upgrade 1 about-to-break item to a higher-quality alternative.', reflectionPrompt: 'How much does quality save long-term?', proTip: 'Check Buy-It-For-Life (BIFL) communities. Reddit has endless suggestions.' },
  16: { title: 'Weekly Money Review', teaching: 'Money = unmeasured = unmanaged. 1 hour weekly: income-expense, budget vs actual, goal status. 52 hours yearly defines yearly income.', action: 'This week spend 30 min on money review. Excel or journal.', reflectionPrompt: 'How would your money roll without review?', proTip: 'Fixed time-day. Sunday 09:00 or Saturday 10:00. No flex.' },
  17: { title: 'Income Multiplication', teaching: 'Saving = limited. Income = unlimited. Single income is risk. 2-3 income channels is disciplined-person profile: main job + freelance/online + investments.', action: 'Today research 1 side income (freelance, online sales, rent, dividend).', reflectionPrompt: 'Easiest extra income to start?', proTip: 'First target: extra $500/mo. That\'s a rent payment = $6K/yr = extra retirement.' },
  18: { title: 'Investing 101: Index Funds', teaching: 'Stock-picking is hard — index funds are easy. Slice of the whole market, average 7-10% annual return (US), tiny fees. Warren Buffett: index funds for retirement.', action: 'Today research index funds (S&P 500, VOO, VT, world index).', reflectionPrompt: 'How did index funds shift investing fear?', proTip: 'Monthly small (Dollar-cost averaging) > one-time big. Spreads risk.' },
  19: { title: 'Side Income Discipline', teaching: 'Side income — starting easy, sustaining hard. First 6 months: $0. Most quit. Month 12 starts earning. Month 24 transforms life. If you sustain.', action: 'Today spend 30 min on a side hustle. Even with $0 income.', reflectionPrompt: 'Fear in starting side income? No money or judgment?', proTip: 'Camera shy? Start with writing. Medium, blog, newsletter.' },
  20: { title: 'Lifestyle Inflation', teaching: 'Salary up = expenses up. Called lifestyle inflation. 10% raise → 10% more car/rent/food. Net effect zero. Discipline: 50% of raise to savings.', action: 'Today inspect last raise. Where did it go?', reflectionPrompt: 'How much did lifestyle inflation hit you?', proTip: 'Live 3 months on old salary. Body accepts old as normal, extra goes to savings.' },
  21: { title: 'Negotiation Skill', teaching: 'Negotiation = embarrassing in West, normal in East. Salary negotiation = 1 hour talk = $5K-20K/yr difference. Negotiation isn\'t cheap — it\'s essential. Ask "what\'s the real number?"', action: 'Today negotiate one price. Even online: ask for a discount code.', reflectionPrompt: 'How did the negotiation attempt go? As scary as feared?', proTip: '"Is this your best price?" — the magic phrase. Often unlocks 5-15% off.' },
  22: { title: 'Tax Awareness', teaching: 'Tax = your biggest annual expense. Most don\'t know tax laws, miss deductions, overpay. 1-2 hours of learning = thousands saved annually.', action: 'Today research deductions (education, health, donations, rent).', reflectionPrompt: 'Which deduction were you unaware of?', proTip: '1-hour with accountant = $200. Saves $2,000.' },
  23: { title: 'Insurance Discipline', teaching: 'Insurance = boring but life-saving. Must-haves: 1) Health (private), 2) Life (if family), 3) Professional liability. Skip: extended warranties, rental car insurance.', action: 'Today review your insurance. Underinsured or overinsured?', reflectionPrompt: 'In what area do you carry uninsured risk?', proTip: 'Compare insurance yearly. Same coverage 30% cheaper elsewhere.' },
  24: { title: 'Financial Goals', teaching: 'Without goals, money = aimless spend. Clear goals: "$5K emergency fund in 1 year," "house down payment in 5 years," "retirement-ready in 20." Date + amount + purpose.', action: 'Today write 3 financial goals. Short (1y), mid (5y), long (20+y).', reflectionPrompt: 'Which goal motivates you most?', proTip: 'Keep goals visible: closet door, desk edge. Visibility = reminder.' },
  25: { title: 'Rewrite Your Money Story', teaching: 'Childhood "money story" shapes financial behavior. "Money is bad," "rich people are thieves," "we\'re not wealthy." Recognize, then rewrite: "Money is a tool, I am the creator."', action: 'Today write your money story for 5 min. Then write a new version.', reflectionPrompt: 'How does your old story hold you back?', proTip: 'Read new story every morning for 30 days. Brain trusts repetition.' },
  26: { title: 'Spending Awareness', teaching: 'Most spending is subconscious: stress, boredom, social pressure, ad triggers. Awareness is the only weapon. Before each purchase: "Is this emotional or real need?"', action: 'Today pause 10 sec before each purchase. Question intent.', reflectionPrompt: 'Which purchase was emotional? Why?', proTip: 'Emotional spending = "I\'ll just buy this" reflex. Stop the hand.' },
  27: { title: 'Mindful Money', teaching: 'Money = energy + time exchange. $100 = hours of effort. Forgetting that starts waste. Remember: $1,000 phone = 50 work hours. Worth it?', action: 'Today, looking at a purchase, convert to work hours. Big or small?', reflectionPrompt: 'Which purchase got reframed when in hours?', proTip: 'Know your hourly. $20/hr = $1,000 item = 50 hours of life.' },
  28: { title: 'Generational Discipline', teaching: 'Money discipline isn\'t just you — it shapes your kids. Wealth dies in 3 generations without transferred discipline. Hiding "money talk" = burden, not legacy.', action: 'Today discuss 1 financial topic with family. Budget, goal, investment.', reflectionPrompt: 'What money topics are taboo in your family?', proTip: 'Show kids salary + budget. Money literacy = most valuable inheritance.' },
  29: { title: 'Final Sprint', teaching: '29 days of money discipline. Tomorrow you "complete." But money doesn\'t end with tomorrow. Final test: which 1 powerful habit of 30 days? 100 more days.', action: 'Today pick the strongest 1 money discipline of 30 days. Which?', reflectionPrompt: 'Why this? What result did it deliver?', proTip: 'Auto-savings is easiest sustained. No willpower, just system.' },
  30: { title: 'Complete — New Money', teaching: '30 days ago money relationship was murky. Now: net worth, budget, goals are clear. You didn\'t own money — now you do. Look in mirror: new financial identity.', action: 'Today summarize 30 days: 3 learned, 3 to keep, 3 not to forget.', reflectionPrompt: 'With this new money mind, which financial goal next?', proTip: 'Rest 3 days before next path. Consistency = permanence.' },
};

const QUIZ_TR = {
  6: [ { q: 'Net servet hesaplaması?', options: ['Sadece nakit', 'Varlık - Borç', 'Sadece maaş', 'Cari kar'], correct: 1, explain: 'Varlık - Borç = net servet.' }, { q: 'Ne sıklıkla takip?', options: ['Yıllık', 'Aylık', 'Asla', 'Günlük'], correct: 1, explain: 'Aylık takip = aylık görünüm.' } ],
  7: [ { q: 'Ortalama abonelik sayısı?', options: ['1-2', '7-12', '30+', '50+'], correct: 1, explain: '7-12 farkında olmadan ödenir.' }, { q: 'Yıllık tutar tahmini?', options: ['1K', '5-15K TL', '50K', '100K'], correct: 1, explain: 'Yıllık 5.000-15.000 TL.' } ],
  8: [ { q: '50 TL/gün × 30 yıl?', options: ['100K', '540K + faiz', '50K', '1M'], correct: 1, explain: '540K + faiz dahil daha fazla.' }, { q: 'Latte faktörü çözüm?', options: ['Hepsini kes', '1\'ini değiştir', 'Daha çok kahve', 'İlgisiz'], correct: 1, explain: '1 değişiklik etkili.' } ],
  9: [ { q: 'Optimum hesap sayısı?', options: ['1', '3', '10', '20'], correct: 1, explain: '1 ana + 1 tasarruf + 1 yatırım = 3.' }, { q: 'Tek karta neden?', options: ['Şıklık', '1 günlük + 1 yedek', 'Avantaj', 'Etkisiz'], correct: 1, explain: '2 kart yeter.' } ],
  10: [ { q: 'Otomatik tasarruf %?', options: ['%5', '%10', '%20', '%50'], correct: 2, explain: '%20 = ideal hedef.' }, { q: 'Tasarruf hesabı nerede?', options: ['Aynı banka', 'Farklı banka', 'Yastık', 'Cüzdan'], correct: 1, explain: 'Farklı banka = erişim zorlukı.' } ],
  11: [ { q: 'Önce ne öde?', options: ['Faturalar', 'Kendine', 'Gıda', 'Eğlence'], correct: 1, explain: 'Önce kendine = tasarruf öncelik.' }, { q: 'Sıralama etkisi?', options: ['Yok', 'Onyıllık fark', 'Aynı', 'Negatif'], correct: 1, explain: '10 yıl = milyonluk fark.' } ],
  12: [ { q: 'Çığ yöntemi nedir?', options: ['Tüm borç eşit', 'Yüksek faiz önce', 'Küçük borç önce', 'Random'], correct: 1, explain: 'Yüksek faize odaklan.' }, { q: 'Snowball ile çığ?', options: ['Aynı', 'Snow psikolojik / çığ matematik', 'Çığ daha yavaş', 'Snow daha pahalı'], correct: 1, explain: 'İkisi de işler, mantığı farklı.' } ],
  13: [ { q: 'Kredi kartı kuralı?', options: ['Sınırsız harca', 'Tam öde + faizsiz', 'Min öde', 'Hep yan'], correct: 1, explain: 'Tam öde, faiz yapma.' }, { q: 'Cüzdan dışı kart?', options: ['Etkisiz', '%15 az harcama', 'Daha fazla', 'Aynı'], correct: 1, explain: 'Yanında olmayan kart = bilinçli alım.' } ],
  14: [ { q: 'Frugality ≠ ?', options: ['Tutumluluk', 'Yoksulluk', 'Plan', 'Disiplin'], correct: 1, explain: 'Tutumlu ≠ yoksul.' }, { q: 'Tutumlu sevinç örneği?', options: ['Lüks restoran', 'Park yürüyüşü', 'Yeni telefon', 'Akşam bara'], correct: 1, explain: '0 TL keyif örnekleri.' } ],
  15: [ { q: 'Ucuz × 5 = ?', options: ['Pahalı', 'Daha ucuz', 'Aynı', 'Bilinmez'], correct: 0, explain: 'Toplamda pahalıya çıkar.' }, { q: 'Buy-it-for-life nedir?', options: ['Pahalı', 'Bir kez al', 'Sonsuz', 'Genç'], correct: 1, explain: '1 kez al, ömür boyu.' } ],
  16: [ { q: 'Haftalık review süresi?', options: ['5 dk', '30 dk', '5 saat', 'Hiç'], correct: 1, explain: '30 dk yeterli.' }, { q: 'Sabit gün-saat?', options: ['Esnek', 'Sabit', 'Hiç', 'Random'], correct: 1, explain: 'Esnek olunca atlanır.' } ],
  17: [ { q: 'Tek gelir = ?', options: ['Güvenli', 'Risk', 'Yeterli', 'İdeal'], correct: 1, explain: 'Tek gelir = risk.' }, { q: 'Disiplinli profil?', options: ['1 gelir', '2-3 gelir', '10 gelir', 'Yok'], correct: 1, explain: '2-3 gelir kanalı optimum.' } ],
  18: [ { q: 'Index fund getirisi?', options: ['%2', '%7-10/yıl', '%50', '%100'], correct: 1, explain: 'Yıllık ortalama %7-10.' }, { q: 'Dollar-cost averaging?', options: ['Tek seferde', 'Aylık küçük', 'Hiç', 'Pahalı'], correct: 1, explain: 'Aylık düzenli yatırım.' } ],
  19: [ { q: 'Ek gelir 1. yıl?', options: ['Hep kazanır', 'İlk 6 ay 0 TL', 'Garantili', 'Hiç başlama'], correct: 1, explain: 'İlk 6 ay 0 TL normal.' }, { q: 'Ne zaman vazgeçer çoğu?', options: ['Asla', '6 ay sonra', '1 yıl', '2 yıl'], correct: 1, explain: 'Çoğu 6 ay sonra vazgeçer.' } ],
  20: [ { q: 'Lifestyle inflation nedir?', options: ['Tasarruf artışı', 'Maaş artışı = harcama artışı', 'Vergi', 'Bütçe'], correct: 1, explain: 'Net etki sıfır.' }, { q: 'Çözüm?', options: ['Maaşı reddet', 'Artışın %50 tasarruf', 'Daha çok harcama', 'Yok'], correct: 1, explain: '%50 tasarrufa.' } ],
  21: [ { q: 'Pazarlık etkisi?', options: ['Etkisiz', '%5-15 indirim', '%50', 'Negatif'], correct: 1, explain: 'Çoğu zaman %5-15.' }, { q: 'Sihirli cümle?', options: ['Pahalı', '"En iyi fiyat mı?"', 'İndir', 'Ucuz'], correct: 1, explain: 'En iyi fiyat soruyu açar.' } ],
  22: [ { q: 'En büyük yıllık harcama?', options: ['Kira', 'Vergi', 'Yemek', 'Eğlence'], correct: 1, explain: 'Vergi en büyük genelde.' }, { q: 'Mali müşavir maliyet?', options: ['Pahalı', '1 saat = 5K, kazanır 50K', 'Yararsız', 'Lüks'], correct: 1, explain: 'Yatırım gibi.' } ],
  23: [ { q: 'Olmazsa olmaz sigorta?', options: ['Araba', 'Sağlık + hayat', 'Sandalye', 'Hiç'], correct: 1, explain: 'Sağlık, hayat, mesleki sorumluluk.' }, { q: 'Sigorta karşılaştırma?', options: ['Etkisiz', 'Yıllık %30 ucuz', 'Aynı', 'Pahalı'], correct: 1, explain: 'Aynı koruma %30 ucuz.' } ],
  24: [ { q: 'Hedef formatı?', options: ['Belirsiz', 'Tarih + miktar + amaç', 'Sadece niyet', 'Yok'], correct: 1, explain: 'Tarih, miktar, amaç şart.' }, { q: 'Hedef sayısı?', options: ['1', '3 (kısa+orta+uzun)', '10', '20'], correct: 1, explain: '3 hedef = focus.' } ],
  25: [ { q: 'Para hikayesi nereden?', options: ['Doğuştan', 'Çocukluk', 'Genler', 'Şans'], correct: 1, explain: 'Çocuklukta öğrenildi.' }, { q: 'Yeni hikaye nasıl etkili?', options: ['Asla', '30 gün her sabah oku', '1 kez', 'Bilinmez'], correct: 1, explain: 'Tekrar = inanma.' } ],
  26: [ { q: 'Çoğu harcama ne?', options: ['Bilinçli', 'Bilinçaltı', 'Plan', 'Akıllı'], correct: 1, explain: 'Bilinçaltı tetikleyicilerle.' }, { q: 'Farkındalık silahı?', options: ['Yok', '10 sn dur, sorgula', 'Hızlı al', 'Telefon'], correct: 1, explain: 'Niyeti sorgula.' } ],
  27: [ { q: 'Para = ?', options: ['Kâğıt', 'Enerji + zaman', 'Şans', 'Şeker'], correct: 1, explain: 'Saatler emek karşılığı.' }, { q: '$100 = ?', options: ['Az', 'Saatler emek', 'Hiç', 'Çok'], correct: 1, explain: 'Saatlik kazançla çevir.' } ],
  28: [ { q: 'Servet 3 kuşak?', options: ['Hep büyür', 'Yok olur disiplinsiz', 'Aynı', 'Negatif'], correct: 1, explain: 'Disiplin geçmezse yok olur.' }, { q: 'En değerli miras?', options: ['Para', 'Para okuryazarlığı', 'Ev', 'İş'], correct: 1, explain: 'Bilgi para üretir.' } ],
  29: [ { q: 'Sürdürülebilir 1 disiplin?', options: ['İrade', 'Otomatik tasarruf', 'Pazarlık', 'Vergi'], correct: 1, explain: 'Sistem > irade.' }, { q: 'Final test?', options: ['Bitti', 'Hangi 1 sürdürülecek?', 'Yorgun', 'Memnun'], correct: 1, explain: '1 disiplin seç.' } ],
  30: [ { q: 'Geçişten sonra dinlenme?', options: ['Yok', '3 gün', '1 hafta', '1 ay'], correct: 1, explain: '3 gün dinlen.' }, { q: '30 gün özeti?', options: ['Yok', '3+3+3', 'Random', 'Liste'], correct: 1, explain: '3 öğrendiğim, 3 sürdüreceğim, 3 unutmayacağım.' } ],
};

const QUIZ_EN = {
  6: [ { q: 'Net worth = ?', options: ['Cash only', 'Assets - Debts', 'Salary only', 'Profit'], correct: 1, explain: 'Assets - Debts = net worth.' }, { q: 'Track frequency?', options: ['Yearly', 'Monthly', 'Never', 'Daily'], correct: 1, explain: 'Monthly = monthly view.' } ],
  7: [ { q: 'Average subscriptions?', options: ['1-2', '7-12', '30+', '50+'], correct: 1, explain: '7-12 paid unaware.' }, { q: 'Yearly cost?', options: ['$50', '$200-500', '$2000', '$5000'], correct: 1, explain: '$200-500 yearly.' } ],
  8: [ { q: '$5/day × 30 yrs?', options: ['$10K', '$54K + interest', '$5K', '$200K'], correct: 1, explain: '$54K + interest more.' }, { q: 'Latte solution?', options: ['Cut all', 'Change 1', 'More coffee', 'Irrelevant'], correct: 1, explain: '1 change effective.' } ],
  9: [ { q: 'Optimum accounts?', options: ['1', '3', '10', '20'], correct: 1, explain: '1 main + 1 savings + 1 invest = 3.' }, { q: 'Why 2 cards?', options: ['Style', '1 daily + 1 backup', 'Bonus', 'No effect'], correct: 1, explain: '2 cards enough.' } ],
  10: [ { q: 'Auto-savings %?', options: ['5%', '10%', '20%', '50%'], correct: 2, explain: '20% = ideal target.' }, { q: 'Savings account where?', options: ['Same bank', 'Different bank', 'Mattress', 'Wallet'], correct: 1, explain: 'Different bank = harder access.' } ],
  11: [ { q: 'Pay first?', options: ['Bills', 'Yourself', 'Food', 'Fun'], correct: 1, explain: 'Pay yourself first = priority.' }, { q: 'Order effect?', options: ['None', 'Decade difference', 'Same', 'Negative'], correct: 1, explain: '10 years = millions diff.' } ],
  12: [ { q: 'Avalanche method?', options: ['All debts equal', 'Highest interest first', 'Smallest first', 'Random'], correct: 1, explain: 'Focus highest interest.' }, { q: 'Snowball vs avalanche?', options: ['Same', 'Snow=psych / aval=math', 'Aval slower', 'Snow more expensive'], correct: 1, explain: 'Both work, different logic.' } ],
  13: [ { q: 'Credit card rule?', options: ['Spend unlimited', 'Pay full + no interest', 'Min pay', 'Carry'], correct: 1, explain: 'Pay full, no interest.' }, { q: 'Out-of-wallet card?', options: ['No effect', '15% less spending', 'More', 'Same'], correct: 1, explain: 'No card = intentional buying.' } ],
  14: [ { q: 'Frugality ≠ ?', options: ['Saving', 'Poverty', 'Plan', 'Discipline'], correct: 1, explain: 'Frugal ≠ poor.' }, { q: 'Frugal joy example?', options: ['Fancy restaurant', 'Park walk', 'New phone', 'Bar night'], correct: 1, explain: '$0 joy examples.' } ],
  15: [ { q: 'Cheap × 5 = ?', options: ['Expensive', 'Cheaper', 'Same', 'Unknown'], correct: 0, explain: 'Total ends up expensive.' }, { q: 'Buy-it-for-life is?', options: ['Expensive', 'One-time buy', 'Eternal', 'Young'], correct: 1, explain: 'Buy once, last lifetime.' } ],
  16: [ { q: 'Weekly review duration?', options: ['5 min', '30 min', '5h', 'Never'], correct: 1, explain: '30 min suffices.' }, { q: 'Fixed time-day?', options: ['Flex', 'Fixed', 'Never', 'Random'], correct: 1, explain: 'Flex = skip.' } ],
  17: [ { q: 'Single income = ?', options: ['Safe', 'Risk', 'Enough', 'Ideal'], correct: 1, explain: 'Single income = risk.' }, { q: 'Disciplined profile?', options: ['1 income', '2-3 incomes', '10 incomes', 'None'], correct: 1, explain: '2-3 channels optimum.' } ],
  18: [ { q: 'Index fund return?', options: ['2%', '7-10%/yr', '50%', '100%'], correct: 1, explain: 'Avg 7-10% yearly.' }, { q: 'DCA?', options: ['One-time', 'Monthly small', 'Never', 'Expensive'], correct: 1, explain: 'Monthly steady.' } ],
  19: [ { q: 'Side income year 1?', options: ['Always pays', 'First 6 mo $0', 'Guaranteed', 'Never start'], correct: 1, explain: 'First 6 mo $0 normal.' }, { q: 'Most quit when?', options: ['Never', 'After 6 mo', '1 yr', '2 yr'], correct: 1, explain: 'Most quit at 6 mo.' } ],
  20: [ { q: 'Lifestyle inflation?', options: ['Savings up', 'Salary up = expense up', 'Tax', 'Budget'], correct: 1, explain: 'Net effect zero.' }, { q: 'Solution?', options: ['Refuse raise', '50% of raise to savings', 'More spending', 'None'], correct: 1, explain: '50% to savings.' } ],
  21: [ { q: 'Negotiation effect?', options: ['No effect', '5-15% off', '50%', 'Negative'], correct: 1, explain: 'Often 5-15%.' }, { q: 'Magic phrase?', options: ['Expensive', '"Is this best price?"', 'Discount', 'Cheap'], correct: 1, explain: 'Best-price question opens.' } ],
  22: [ { q: 'Biggest yearly expense?', options: ['Rent', 'Tax', 'Food', 'Fun'], correct: 1, explain: 'Tax usually biggest.' }, { q: 'Accountant cost?', options: ['Expensive', '1h = $200, saves $2K', 'Useless', 'Luxury'], correct: 1, explain: 'Investment-like.' } ],
  23: [ { q: 'Must-have insurance?', options: ['Auto', 'Health + life', 'Furniture', 'None'], correct: 1, explain: 'Health, life, professional.' }, { q: 'Insurance compare?', options: ['No effect', 'Yearly 30% cheaper', 'Same', 'Expensive'], correct: 1, explain: 'Same coverage 30% cheaper.' } ],
  24: [ { q: 'Goal format?', options: ['Vague', 'Date + amount + purpose', 'Just intent', 'None'], correct: 1, explain: 'Date, amount, purpose required.' }, { q: 'Goal count?', options: ['1', '3 (short+mid+long)', '10', '20'], correct: 1, explain: '3 goals = focus.' } ],
  25: [ { q: 'Money story from?', options: ['Birth', 'Childhood', 'Genes', 'Luck'], correct: 1, explain: 'Learned in childhood.' }, { q: 'New story effective?', options: ['Never', '30 days every morning', '1 time', 'Unknown'], correct: 1, explain: 'Repetition = belief.' } ],
  26: [ { q: 'Most spending is?', options: ['Conscious', 'Subconscious', 'Plan', 'Smart'], correct: 1, explain: 'Subconscious triggers.' }, { q: 'Awareness weapon?', options: ['None', '10 sec pause + question', 'Quick buy', 'Phone'], correct: 1, explain: 'Question intent.' } ],
  27: [ { q: 'Money = ?', options: ['Paper', 'Energy + time', 'Luck', 'Sugar'], correct: 1, explain: 'Hours of effort.' }, { q: '$100 = ?', options: ['Little', 'Hours of effort', 'Nothing', 'A lot'], correct: 1, explain: 'Convert to hourly rate.' } ],
  28: [ { q: 'Wealth in 3 generations?', options: ['Always grows', 'Dies without discipline', 'Same', 'Negative'], correct: 1, explain: 'Discipline must transfer.' }, { q: 'Most valuable inheritance?', options: ['Money', 'Money literacy', 'House', 'Job'], correct: 1, explain: 'Knowledge generates money.' } ],
  29: [ { q: 'Sustainable 1 discipline?', options: ['Willpower', 'Auto-savings', 'Negotiation', 'Tax'], correct: 1, explain: 'System > willpower.' }, { q: 'Final test?', options: ['Done', 'Which 1 to keep?', 'Tired', 'Satisfied'], correct: 1, explain: 'Pick 1 discipline.' } ],
  30: [ { q: 'Rest after transition?', options: ['None', '3 days', '1 week', '1 month'], correct: 1, explain: '3 days rest.' }, { q: '30-day summary?', options: ['None', '3+3+3', 'Random', 'List'], correct: 1, explain: '3 learned, 3 to keep, 3 not to forget.' } ],
};

function buildLessons(newContent, quizMap, protips) {
  const out = {};
  for (const [order, tip] of Object.entries(protips)) out[order] = { proTip: tip };
  for (const [order, lesson] of Object.entries(newContent)) {
    out[order] = {
      title: lesson.title, teaching: lesson.teaching, action: lesson.action,
      reflectionPrompt: lesson.reflectionPrompt, proTip: lesson.proTip,
      quiz: quizMap[order] || [],
    };
  }
  return out;
}
function applyToFile(filePath, pathId, lessonsMerge) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (!data.lessons[pathId]) data.lessons[pathId] = {};
  for (const [order, fields] of Object.entries(lessonsMerge)) {
    data.lessons[pathId][order] = { ...(data.lessons[pathId][order] || {}), ...fields };
  }
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
}

const TR_MERGE = buildLessons(NEW_TR, QUIZ_TR, PROTIPS_TR);
const EN_MERGE = buildLessons(NEW_EN, QUIZ_EN, PROTIPS_EN);
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.tr.json'), 'money-discipline', TR_MERGE);
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.en.json'), 'money-discipline', EN_MERGE);
console.log(`✓ Money Discipline seeded — ${Object.keys(NEW_TR).length} new lessons + 5 pro tips × 2 langs`);
