/** Money-discipline lessons 31-50 (advanced). TR + EN. */
const fs = require('fs');
const path = require('path');

const NEW_TR = {
  31: { title: 'Bileşik Faiz', teaching: 'Einstein: "dünyanın 8. harikası." 100 TL × %10/yıl × 30 yıl = 1,750 TL. Kaynağı 30 yıl bekleten 17x katlar. Erken başla, küçük başla.', action: 'Bugün bileşik faiz hesaplayıcısı kullan, 30 yıl sonrasını gör.', reflectionPrompt: 'Bugün küçük tasarruf 30 yılda ne olur?', proTip: 'compoundinterestcalculator.net = ücretsiz hesaplama.' },
  32: { title: 'Servet Kimliği', teaching: '"Kazanıyorum" davranış. "Servet sahibiyim" kimlik. Zenginler farklı düşünür: harcamadan önce yatırır, kira değil sahip olur, vakit yatırım. Kimliği değiştir.', action: 'Bugün "servet sahibi" kimliği koy.', reflectionPrompt: 'Yeni kimlikle hangi karar değişti?', proTip: 'Aynaya: "Ben servet inşa ediyorum." Günlük tekrar.' },
  33: { title: 'Bir Kez Al, Pişman Ol', teaching: 'Ucuz × 5 = pahalı. Ayakkabı 200 TL × 5 yıl = 1,000 TL. Ayakkabı 1,000 TL × 20 yıl = 1,000 TL. Aynı bütçe, 4x kalite. Toplam yaşam maliyeti.', action: 'Bugün uzun vade kullanılacak 1 ürünü kaliteli al.', reflectionPrompt: 'Kalite uzun vade nasıl tasarruf eder?', proTip: 'Buy It For Life subreddit = hayat boyu ürün önerileri.' },
  34: { title: 'Gelir Akımları', teaching: '1 gelir = 1 risk. 7 zengin tipinde ortalama 7 gelir akımı (Tom Corley araştırma): maaş + freelance + yatırım temettü + kira + dijital + mentörlük + telif. 3-4\'ü hedef.', action: 'Bugün 1 ek gelir akımı planı yaz.', reflectionPrompt: 'Hangisi en kolay başlatılır?', proTip: 'Dijital ürün (e-kitap, kurs) = en yüksek marjin.' },
  35: { title: 'Vergi Optimizasyonu', teaching: 'Vergi en büyük yıllık harcaman. %25-40 gelir gider. Optimize et: emeklilik fonu, eğitim indirim, sağlık katkısı, bağış. 2 saat öğrenme = yılda binlerce.', action: 'Bugün hangi vergi indirimlerini kullanmıyorsun araştır.', reflectionPrompt: 'En büyük kayıp hangisi?', proTip: 'CPA (mali müşavir) 1 saatlik = 5K TL. Yıllık 50K kazanır.' },
  36: { title: 'Sigorta Mastery', teaching: 'Sigorta sıkıcı ama hayat kurtarır. Olmazsa olmaz: sağlık, hayat (aile varsa), iş kaybı, mesleki sorumluluk. Olmaması: araba kasko, sandalye, telefon ekran.', action: 'Bugün sigortalarını gözden geçir. Eksik veya fazla?', reflectionPrompt: 'Hangi sigorta öncelik?', proTip: 'Yılda 1 karşılaştır. Aynı koruma %30 daha ucuz olabilir.' },
  37: { title: 'Yatırım Çeşitlenmesi', teaching: 'Tek yumurta 1 sepete = risk. Yatırım: %60 hisse, %20 tahvil, %10 emlak, %10 nakit. Çeşitlenme = az risk + uzun vade kazanç.', action: 'Bugün yatırımlarını analiz et. Çeşitli mi?', reflectionPrompt: 'Hangi sınıf eksik?', proTip: 'Ray Dalio "All Weather Portfolio" = ücretsiz şablon.' },
  38: { title: 'Emlak Farkındalığı', teaching: 'Emlak = kira yerine sahip olmak + kira gelir + değer artışı. Türkiye\'de 25 yıl ortalama yıllık %12 değer artışı. 3 evi olan = pasif gelir.', action: 'Bugün ev satın alma vs kira karşılaştırma yap.', reflectionPrompt: '5 yıl sonra hangi seçenek daha karlı?', proTip: 'İlk evi 30 yaş öncesi al. Bileşik kazanç.' },
  39: { title: 'Kripto Farkındalığı', teaching: 'Kripto = volatil ama uzun vade saklamada potansiyel. Bitcoin 2010 = 0.05 USD, 2024 = 70K USD. Risk: %5-10 portföyün max. DCA = aylık küçük al.', action: 'Bugün kripto araştır, %2 portföyle başla (eğer dene).', reflectionPrompt: 'Risk hissi nasıl?', proTip: 'Coldwallet kullan, exchange\'da bırakma.' },
  40: { title: 'Miras Planlaması', teaching: 'Vasiyetname yok = devlet servet dağıtır. Aile = vasiyet zorunlu. Hayat sigortası + vasiyet + güvenli kasa. 30+ yaş için olmazsa olmaz.', action: 'Bugün basit vasiyet yaz. Notere onaylat.', reflectionPrompt: 'Aile bilgilendirildi mi?', proTip: 'Notere noter ücretsiz, vasiyet 200-500 TL.' },
  41: { title: 'Zihniyet Kayması', teaching: '"Param yok" zihniyeti = yok bırakır. "Para çekme bilirim" = çeker. Zenginler zihniyet sorunu çözmüş. Önce kafa, sonra cüzdan.', action: 'Bugün 5 dakika "para iyi bir araçtır" yaz.', reflectionPrompt: 'Eski para hikayen ne?', proTip: 'Yeni hikaye 30 gün her sabah oku.' },
  42: { title: 'Acil Fon Mastery', teaching: '3 ay yetmedi = 6 ay hedefi. 6 ay zorunlu giderlerin = işsizlik, hastalık, kriz buffer\'ı. Hayat değişir, hazır ol.', action: 'Bugün acil fon hedefini 6 aya çek.', reflectionPrompt: '6 ay daha güvenli mi hissettiriyor?', proTip: 'Acil fon high-yield account = enflasyon kaybı az.' },
  43: { title: 'Müzakere Mastery', teaching: 'Maaş müzakere yıllık 50K-200K fark. "Asıl rakam ne?" sor. "Bu son fiyatınız mı?" %5-15 indirim açar. Faturalar bile müzakere edilir.', action: 'Bugün 1 fiyat müzakere et.', reflectionPrompt: 'Müzakere zor muydu?', proTip: 'Internet operatör/kablo bedava müzakere = aylık tasarruf.' },
  44: { title: 'Yan İş Planı', teaching: 'Yan iş ek gelir + kariyer hedge. 5K TL ay = ev kirası ödendi. 10K = lifestyle kalite. 30K = full-time geçiş hazırlığı. 1 yıl plan ile.', action: 'Bugün yan iş için 1 saat ayır.', reflectionPrompt: 'En kolay başlatılır olan?', proTip: 'İlk hedef: aylık 5K TL. Konkret ölçülebilir.' },
  45: { title: 'Finansal Bağımsızlık', teaching: 'FIRE = Financial Independence Retire Early. 25x yıllık harcaman = bağımsızlık. Yıllık 100K harcıyorsan, 2.5M = özgürlük. %4 çekme kuralı.', action: 'Bugün FIRE numaranı hesapla.', reflectionPrompt: 'Sayı ulaşılabilir mi?', proTip: 'Mr. Money Mustache blog = FIRE topluluk.' },
  46: { title: 'Emeklilik Planlaması', teaching: 'Emeklilik 65\'te değil. Hazırlık 30\'da başlar. Bireysel emeklilik + devlet + yatırım = 3 ayak. Erken başlamayan 60\'ta panik.', action: 'Bugün BES açtırmadıysan, başvur.', reflectionPrompt: 'Devlet emekliliği yeter mi?', proTip: '%25 devlet katkısı = otomatik %25 kazanç. Asla bırakma.' },
  47: { title: 'Servet Kimliği Final', teaching: 'Davranışlar tekrar olunca kimlik olur. 50 günde para alışkanlıkların değişti. Şimdi kimlik konuşması: "Ben kontrolüm. Ben planlıyorum. Ben yatırıyorum."', action: 'Bugün servet kimliğini 3 cümlede yaz.', reflectionPrompt: 'En güçlü cümle?', proTip: 'Cüzdana yaz, her açtığında oku.' },
  48: { title: 'Final Sprint', teaching: 'Son 3 gün. 50 günde para ilişkisi karışıktan netleşti. Bu sprint = kalıcı kimlik. Yarın paranın patronu sensin.', action: 'Bugün son sprintin niyetini yaz.', reflectionPrompt: 'En değişen para alışkanlığı?', proTip: 'Net servet sayını kaydet, 30 gün sonra karşılaştır.' },
  49: { title: '49 Gün İçinde', teaching: '49 günde otomatik tasarruf, çerçeveli karar, çeşitlenmiş yatırım, vergi farkındalığı. Yeni baseline = master para. 10 değişiklik listele.', action: 'Bugün 49 günde değişen 10 para alışkanlığını yaz.', reflectionPrompt: 'En unutulmaz değişim?', proTip: 'Net servet grafiği = motivasyon.' },
  50: { title: 'Master Tamamlandı', teaching: '50 gün. Para artık endişe değil araç. Kontrol, plan, çeşitlenme, kimlik. Yeni baseline = finansal master. Diploma yok — net servet artıyor.', action: 'Bugün aynaya bak. Yeni Sen\'i selamla.', reflectionPrompt: '50 gün önceki sen şimdi olmak ister miydi?', proTip: '5 path tamamlandıysa: 6. ay her gün 1 path\'tan ders. Ya da kendi path\'ini tasarla.' },
};

const NEW_EN = {
  31: { title: 'Compound Interest', teaching: 'Einstein: "8th wonder of the world." $100 × 10%/yr × 30 yr = $1,750. Letting money compound 30 years multiplies 17x. Start early, start small.', action: 'Today use a compound interest calculator, see 30 years out.', reflectionPrompt: 'Today\'s small saving in 30 years?', proTip: 'compoundinterestcalculator.net = free calc.' },
  32: { title: 'Wealth Identity', teaching: '"I earn" is behavior. "I am wealthy" is identity. Rich think differently: invest before spend, own not rent, time invested. Change identity.', action: 'Today claim "wealth-builder" identity.', reflectionPrompt: 'Which decision changed with new identity?', proTip: 'Mirror: "I am building wealth." Daily repeat.' },
  33: { title: 'Buy Once, Cry Once', teaching: 'Cheap × 5 = expensive. $40 shoes × 5 yr = $200. $200 shoes × 20 yr = $200. Same budget, 4x quality. Total life cost.', action: 'Today buy 1 long-term-use item with quality.', reflectionPrompt: 'How does quality save long-term?', proTip: 'Buy It For Life subreddit = lifetime product recommendations.' },
  34: { title: 'Income Streams', teaching: '1 income = 1 risk. Average wealthy: 7 income streams (Tom Corley research): salary + freelance + dividends + rent + digital + mentorship + royalty. Target 3-4.', action: 'Today plan 1 additional income stream.', reflectionPrompt: 'Which is easiest to start?', proTip: 'Digital product (ebook, course) = highest margin.' },
  35: { title: 'Tax Optimization', teaching: 'Tax is your biggest annual expense. 25-40% of income gone. Optimize: retirement, education deduction, health contribution, donation. 2 hours of learning = thousands saved.', action: 'Today research which tax deductions you\'re missing.', reflectionPrompt: 'Biggest loss?', proTip: 'CPA 1-hour = $200. Saves $5K yearly.' },
  36: { title: 'Insurance Mastery', teaching: 'Insurance is boring but life-saving. Must-have: health, life (if family), disability, professional liability. Skip: car kasko, furniture, phone screen.', action: 'Today review your insurance. Missing or excess?', reflectionPrompt: 'Priority insurance?', proTip: 'Yearly compare. Same coverage 30% cheaper possible.' },
  37: { title: 'Investment Diversification', teaching: 'All eggs 1 basket = risk. Investment: 60% stocks, 20% bonds, 10% real estate, 10% cash. Diversification = less risk + long-term gains.', action: 'Today analyze your investments. Diverse?', reflectionPrompt: 'Which class is missing?', proTip: 'Ray Dalio "All Weather Portfolio" = free template.' },
  38: { title: 'Real Estate Awareness', teaching: 'Real estate = own vs rent + rental income + appreciation. 25-yr Turkey average +12% yearly. 3 properties = passive income.', action: 'Today compare buying vs renting.', reflectionPrompt: 'Which more profitable in 5 years?', proTip: 'Buy first home before 30. Compound returns.' },
  39: { title: 'Crypto Awareness', teaching: 'Crypto = volatile but long-term holding potential. Bitcoin 2010 = $0.05, 2024 = $70K. Risk: 5-10% of portfolio max. DCA = monthly small buys.', action: 'Today research crypto, start with 2% portfolio (if testing).', reflectionPrompt: 'How does the risk feel?', proTip: 'Use cold wallet, don\'t leave on exchange.' },
  40: { title: 'Estate Planning', teaching: 'No will = state distributes assets. Family = will mandatory. Life insurance + will + safe deposit. After 30, must-have.', action: 'Today write a simple will. Notarize.', reflectionPrompt: 'Family informed?', proTip: 'Notary 200-500 TL / $50-100, will done.' },
  41: { title: 'Mindset Shift', teaching: '"I have no money" mindset = leaves you with none. "I know how to attract money" = attracts. Rich solved mindset problem first. Head before wallet.', action: 'Today write 5 min "money is a good tool."', reflectionPrompt: 'Old money story?', proTip: 'New story 30 days every morning.' },
  42: { title: 'Emergency Fund Mastery', teaching: '3 months not enough = 6-month target. 6 months of expenses = unemployment, illness, crisis buffer. Life changes, be ready.', action: 'Today extend emergency fund target to 6 months.', reflectionPrompt: 'Does 6 months feel safer?', proTip: 'High-yield account = inflation loss minimal.' },
  43: { title: 'Negotiation Mastery', teaching: 'Salary negotiation = $5K-20K yearly difference. "What\'s the real number?" Ask. "Is this best price?" opens 5-15% discount. Bills negotiable too.', action: 'Today negotiate one price.', reflectionPrompt: 'Was negotiating hard?', proTip: 'Internet/cable provider negotiation = monthly savings.' },
  44: { title: 'Side Hustle Plan', teaching: 'Side hustle = extra income + career hedge. $500/mo = rent paid. $1K = lifestyle quality. $3K = full-time transition. 1-year plan.', action: 'Today spend 1 hour on side hustle.', reflectionPrompt: 'Easiest to start?', proTip: 'First target: $500/mo. Concrete measurable.' },
  45: { title: 'Financial Independence', teaching: 'FIRE = Financial Independence Retire Early. 25x annual spend = independence. Spending $40K/yr → $1M = freedom. 4% withdrawal rule.', action: 'Today calculate your FIRE number.', reflectionPrompt: 'Is the number reachable?', proTip: 'Mr. Money Mustache blog = FIRE community.' },
  46: { title: 'Retirement Planning', teaching: 'Retirement isn\'t at 65. Preparation starts at 30. Personal retirement + state + investment = 3 legs. Late starters panic at 60.', action: 'Today open retirement account if not done.', reflectionPrompt: 'Is state retirement enough?', proTip: '25% state contribution = automatic 25% gain. Never skip.' },
  47: { title: 'Wealth Identity Final', teaching: 'Behaviors repeated become identity. 50 days, your money habits changed. Now identity talk: "I am control. I am planning. I am investing."', action: 'Today write your wealth identity in 3 sentences.', reflectionPrompt: 'Strongest sentence?', proTip: 'Write in wallet, read each open.' },
  48: { title: 'Final Sprint', teaching: 'Last 3 days. 50 days transformed money relationship from murky to clear. This sprint = permanent identity. Tomorrow you are money\'s boss.', action: 'Today write final-sprint intent.', reflectionPrompt: 'Most-changed money habit?', proTip: 'Save your net worth number, compare in 30 days.' },
  49: { title: '49 Days In', teaching: 'In 49 days: auto-savings, decision frameworks, diversified investments, tax awareness. New baseline = master money. List 10 changes.', action: 'Today list 10 money habits that changed in 49 days.', reflectionPrompt: 'Most unforgettable change?', proTip: 'Net worth chart = motivation.' },
  50: { title: 'Master Complete', teaching: '50 days. Money no longer worry but tool. Control, plan, diversify, identity. New baseline = financial master. No diploma — net worth grows.', action: 'Today look in mirror. Greet New You.', reflectionPrompt: 'Would 50-days-ago you want to be now?', proTip: '5 paths complete: month 6 daily lesson from each. Or design own path.' },
};

const QUIZ_TR = {
  31: [{ q: 'Bileşik faiz kim "8. harika"?', options: ['Newton', 'Einstein', 'Gates', 'Buffett'], correct: 1, explain: 'Einstein adlandırma.' }, { q: 'Erken başlamak?', options: ['Etkisiz', 'Bileşik gücü', 'Risk', 'Pahalı'], correct: 1, explain: 'Zaman = bileşik gücü.' }],
  32: [{ q: 'Davranış mı kimlik mi?', options: ['Davranış', 'Kimlik kalıcı', 'Aynı', 'Bilinmez'], correct: 1, explain: 'Kimlik > davranış.' }, { q: 'Zenginler farklı düşünür?', options: ['Etkisiz', 'Önce yatırım sonra harcama', 'Aynı', 'Yok'], correct: 1, explain: 'Sıralama farklı.' }],
  33: [{ q: 'Ucuz × 5 = ?', options: ['Ucuz', 'Pahalı', 'Aynı', 'Bilinmez'], correct: 1, explain: 'Toplamda pahalı.' }, { q: 'BIFL kaynak?', options: ['Forum', 'Reddit subreddit', 'Email', 'Yok'], correct: 1, explain: 'Hayat boyu öneriler.' }],
  34: [{ q: 'Optimum gelir akımı?', options: ['1', '3-4', '20', '100'], correct: 1, explain: '7 zengin ortalama, 3-4 hedef.' }, { q: 'En yüksek marjin?', options: ['Maaş', 'Dijital ürün', 'Kira', 'Bilinmez'], correct: 1, explain: 'Dijital ürün.' }],
  35: [{ q: 'Vergi büyüklüğü?', options: ['Yok', '%25-40 gelir', '%5', '%100'], correct: 1, explain: 'En büyük yıllık gider.' }, { q: 'CPA değeri?', options: ['Pahalı', '1 saat = 5K kazandırır', 'Yararsız', 'Bilinmez'], correct: 1, explain: 'Yatırım gibi.' }],
  36: [{ q: 'Olmazsa olmaz sigorta?', options: ['Araba', 'Sağlık+hayat+iş kaybı', 'Sandalye', 'Yok'], correct: 1, explain: 'Kritik 3 alan.' }, { q: 'Yıllık karşılaştırma?', options: ['Etkisiz', '%30 ucuz olabilir', 'Sürekli aynı', 'Risk'], correct: 1, explain: 'Aynı koruma daha ucuz.' }],
  37: [{ q: 'Çeşitlenme avantajı?', options: ['Yok', 'Risk az + uzun vade', 'Pahalı', 'Kompleks'], correct: 1, explain: 'Risk yönetimi.' }, { q: 'All Weather kim?', options: ['Bezos', 'Ray Dalio', 'Buffett', 'Musk'], correct: 1, explain: 'Bridgewater kurucusu.' }],
  38: [{ q: 'Türkiye 25 yıl emlak ortalaması?', options: ['%2', '%12', '%50', '%0'], correct: 1, explain: 'Yıllık ortalama %12.' }, { q: 'İlk ev önerisi?', options: ['65 yaş', '30 yaş öncesi', 'Asla', '50'], correct: 1, explain: 'Bileşik kazanç için erken.' }],
  39: [{ q: 'Kripto portföy max?', options: ['%50', '%5-10', '%100', '%0'], correct: 1, explain: 'Risk yönetimi.' }, { q: 'En güvenli saklama?', options: ['Exchange', 'Cold wallet', 'Bank', 'Hafıza'], correct: 1, explain: 'Cold wallet = offline.' }],
  40: [{ q: 'Vasiyetname yoksa?', options: ['Aile alır', 'Devlet dağıtır', 'Yok olur', 'Eşit'], correct: 1, explain: 'Devlet sistemi.' }, { q: 'Notere maliyet?', options: ['Pahalı', '200-500 TL/$50-100', '0', '10K'], correct: 1, explain: 'Ucuz.' }],
  41: [{ q: 'Önce ne değişir?', options: ['Cüzdan', 'Kafa', 'Banka', 'Maaş'], correct: 1, explain: 'Zihniyet ilk.' }, { q: 'Yeni hikaye süresi?', options: ['1 gün', '30 gün', '1 yıl', 'Yok'], correct: 1, explain: '30 gün her sabah.' }],
  42: [{ q: 'Optimum acil fon?', options: ['1 ay', '6 ay', '1 hafta', 'Yok'], correct: 1, explain: '6 ay = mastery.' }, { q: 'Acil fon nereye?', options: ['Yastık', 'High-yield account', 'Hisse', 'Kripto'], correct: 1, explain: 'Likit + faizli.' }],
  43: [{ q: 'Maaş müzakere yıllık?', options: ['Etkisiz', '$5-20K fark', '$100', '0'], correct: 1, explain: 'Büyük etki.' }, { q: 'Sihirli cümle?', options: ['Pahalı', 'Bu son fiyat mı?', 'Hayır', 'İndirim'], correct: 1, explain: '%5-15 açar.' }],
  44: [{ q: 'İlk yan iş hedefi?', options: ['Etkisiz', '$500/ay', '$10K', '0'], correct: 1, explain: 'Konkret başlangıç.' }, { q: 'Avantaj?', options: ['Stres', 'Kariyer hedge', 'Yorgunluk', 'Risk'], correct: 1, explain: 'Risk yönetimi.' }],
  45: [{ q: 'FIRE numarası?', options: ['10x harcama', '25x yıllık harcama', '100x', 'Sabit'], correct: 1, explain: '4% kuralı = 25x.' }, { q: 'FIRE kaynak?', options: ['Yok', 'Mr. Money Mustache', 'Bank', 'Tabloid'], correct: 1, explain: 'Topluluk + bilgi.' }],
  46: [{ q: 'Emeklilik 3 ayak?', options: ['1', 'Bireysel+devlet+yatırım', 'Sadece devlet', 'Sadece bireysel'], correct: 1, explain: '3 sistem güvenli.' }, { q: 'BES devlet katkısı?', options: ['Yok', '%25', '%10', '%50'], correct: 1, explain: 'Otomatik %25 kazanç.' }],
  47: [{ q: 'Servet kimliği nasıl?', options: ['Düşün', '3 cümle yaz', 'Hatırla', 'Forget'], correct: 1, explain: 'Yazılı net.' }, { q: 'Nereye yaz?', options: ['Bilgisayar', 'Cüzdan', 'Email', 'Yok'], correct: 1, explain: 'Her açtığında oku.' }],
  48: [{ q: 'Final sprint?', options: ['1 gün', '3 gün', '1 ay', 'Yok'], correct: 1, explain: 'Son 3 gün.' }, { q: 'Net servet?', options: ['Etkisiz', 'Kaydet, 30 gün sonra karşılaştır', 'Asla', 'Sürekli'], correct: 1, explain: 'Ölçüm = motivasyon.' }],
  49: [{ q: 'Yeni baseline?', options: ['Eski', 'Master para', 'Pasif', 'Bilinmez'], correct: 1, explain: 'Otomatik sistem.' }, { q: 'Net servet grafiği?', options: ['Etkisiz', 'Motivasyon', 'Risk', 'Pahalı'], correct: 1, explain: 'Görsel ilerleme.' }],
  50: [{ q: 'Master = ?', options: ['Endişe', 'Para araç', 'Pasif', 'Hep zengin'], correct: 1, explain: 'Para artık araç.' }, { q: 'Sonraki adım?', options: ['Hemen', '5 path tamamlandıysa: 6.ay', 'Asla', 'Tatil'], correct: 1, explain: 'Tüm path\'ler tamamlandıysa karışım.' }],
};

const QUIZ_EN = {
  31: [{ q: 'Compound interest "8th wonder" by?', options: ['Newton', 'Einstein', 'Gates', 'Buffett'], correct: 1, explain: 'Einstein named it.' }, { q: 'Early start?', options: ['No effect', 'Compound power', 'Risk', 'Expensive'], correct: 1, explain: 'Time = compound power.' }],
  32: [{ q: 'Behavior or identity?', options: ['Behavior', 'Identity permanent', 'Same', 'Unknown'], correct: 1, explain: 'Identity > behavior.' }, { q: 'Rich think differently?', options: ['No effect', 'Invest before spend', 'Same', 'No'], correct: 1, explain: 'Order is different.' }],
  33: [{ q: 'Cheap × 5 = ?', options: ['Cheap', 'Expensive', 'Same', 'Unknown'], correct: 1, explain: 'Total = expensive.' }, { q: 'BIFL source?', options: ['Forum', 'Reddit subreddit', 'Email', 'No'], correct: 1, explain: 'Lifetime recommendations.' }],
  34: [{ q: 'Optimum income streams?', options: ['1', '3-4', '20', '100'], correct: 1, explain: '7 wealthy avg, 3-4 target.' }, { q: 'Highest margin?', options: ['Salary', 'Digital product', 'Rent', 'Unknown'], correct: 1, explain: 'Digital product.' }],
  35: [{ q: 'Tax magnitude?', options: ['No', '25-40% income', '5%', '100%'], correct: 1, explain: 'Biggest yearly expense.' }, { q: 'CPA value?', options: ['Expensive', '1 hour = $5K saved', 'Useless', 'Unknown'], correct: 1, explain: 'Like investment.' }],
  36: [{ q: 'Must-have insurance?', options: ['Car', 'Health+life+disability', 'Furniture', 'No'], correct: 1, explain: 'Critical 3 areas.' }, { q: 'Yearly compare?', options: ['No effect', '30% cheaper possible', 'Always same', 'Risk'], correct: 1, explain: 'Same coverage cheaper.' }],
  37: [{ q: 'Diversification advantage?', options: ['No', 'Less risk + long-term', 'Expensive', 'Complex'], correct: 1, explain: 'Risk management.' }, { q: 'All Weather by?', options: ['Bezos', 'Ray Dalio', 'Buffett', 'Musk'], correct: 1, explain: 'Bridgewater founder.' }],
  38: [{ q: 'Turkey 25-yr real estate avg?', options: ['2%', '12%', '50%', '0%'], correct: 1, explain: 'Yearly avg 12%.' }, { q: 'First home recommendation?', options: ['65 yo', 'Before 30', 'Never', '50'], correct: 1, explain: 'Compound gain early.' }],
  39: [{ q: 'Crypto portfolio max?', options: ['50%', '5-10%', '100%', '0%'], correct: 1, explain: 'Risk management.' }, { q: 'Safest storage?', options: ['Exchange', 'Cold wallet', 'Bank', 'Memory'], correct: 1, explain: 'Cold wallet = offline.' }],
  40: [{ q: 'No will means?', options: ['Family gets', 'State distributes', 'Lost', 'Equal'], correct: 1, explain: 'State system.' }, { q: 'Notary cost?', options: ['Expensive', '$50-100', '0', '10K'], correct: 1, explain: 'Cheap.' }],
  41: [{ q: 'What changes first?', options: ['Wallet', 'Mind', 'Bank', 'Salary'], correct: 1, explain: 'Mindset first.' }, { q: 'New story duration?', options: ['1 day', '30 days', '1 year', 'No'], correct: 1, explain: '30 days every morning.' }],
  42: [{ q: 'Optimum emergency fund?', options: ['1 month', '6 months', '1 week', 'No'], correct: 1, explain: '6 months = mastery.' }, { q: 'Where to keep?', options: ['Pillow', 'High-yield account', 'Stock', 'Crypto'], correct: 1, explain: 'Liquid + interest.' }],
  43: [{ q: 'Salary negotiation yearly?', options: ['No effect', '$5-20K diff', '$100', '0'], correct: 1, explain: 'Big impact.' }, { q: 'Magic phrase?', options: ['Expensive', 'Is this best price?', 'No', 'Discount'], correct: 1, explain: '5-15% opens.' }],
  44: [{ q: 'First side-hustle target?', options: ['No effect', '$500/mo', '$10K', '0'], correct: 1, explain: 'Concrete start.' }, { q: 'Advantage?', options: ['Stress', 'Career hedge', 'Tired', 'Risk'], correct: 1, explain: 'Risk management.' }],
  45: [{ q: 'FIRE number?', options: ['10x spend', '25x annual spend', '100x', 'Fixed'], correct: 1, explain: '4% rule = 25x.' }, { q: 'FIRE source?', options: ['No', 'Mr. Money Mustache', 'Bank', 'Tabloid'], correct: 1, explain: 'Community + info.' }],
  46: [{ q: 'Retirement 3 legs?', options: ['1', 'Personal+state+investment', 'Just state', 'Just personal'], correct: 1, explain: '3 systems safe.' }, { q: 'State match?', options: ['No', '25%', '10%', '50%'], correct: 1, explain: 'Auto 25% gain.' }],
  47: [{ q: 'Wealth identity how?', options: ['Think', 'Write 3 sentences', 'Remember', 'Forget'], correct: 1, explain: 'Written clear.' }, { q: 'Where to write?', options: ['Computer', 'Wallet', 'Email', 'No'], correct: 1, explain: 'Read each open.' }],
  48: [{ q: 'Final sprint?', options: ['1 day', '3 days', '1 month', 'No'], correct: 1, explain: 'Last 3 days.' }, { q: 'Net worth?', options: ['No effect', 'Save, compare in 30 days', 'Never', 'Always'], correct: 1, explain: 'Measurement = motivation.' }],
  49: [{ q: 'New baseline?', options: ['Old', 'Master money', 'Passive', 'Unknown'], correct: 1, explain: 'Automatic system.' }, { q: 'Net worth chart?', options: ['No effect', 'Motivation', 'Risk', 'Expensive'], correct: 1, explain: 'Visual progress.' }],
  50: [{ q: 'Master = ?', options: ['Worry', 'Money is tool', 'Passive', 'Always rich'], correct: 1, explain: 'Money becomes tool.' }, { q: 'Next step?', options: ['Now', 'Month 6 if 5 paths complete', 'Never', 'Vacation'], correct: 1, explain: 'After all paths complete: mix.' }],
};

function buildLessons(c, q) { const o = {}; for (const [k, v] of Object.entries(c)) o[k] = { ...v, quiz: q[k] || [] }; return o; }
function applyToFile(filePath, pathId, m) { const d = JSON.parse(fs.readFileSync(filePath, 'utf8')); if (!d.lessons[pathId]) d.lessons[pathId] = {}; for (const [k, v] of Object.entries(m)) d.lessons[pathId][k] = { ...(d.lessons[pathId][k] || {}), ...v }; fs.writeFileSync(filePath, JSON.stringify(d, null, 2) + '\n'); }
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.tr.json'), 'money-discipline', buildLessons(NEW_TR, QUIZ_TR));
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.en.json'), 'money-discipline', buildLessons(NEW_EN, QUIZ_EN));
console.log(`✓ Money-discipline 31-50 seeded — ${Object.keys(NEW_TR).length} new lessons × 2 langs`);
