/**
 * Add 20 advanced lessons (31-50) to dopamine-detox path. TR + EN.
 * Run: node scripts/seed_dopamine_31_50.js
 */
const fs = require('fs');
const path = require('path');

const NEW_TR = {
  31: { title: 'Yer Değiştirme', teaching: 'Bağımlılığı kırmak için yasaklamak yetmez — yerine bir şey koymak lazım. Telefon almak istediğinde: yürü, su iç, defter yaz. Beyin "yokluk" kabul etmez ama "değişim" kabul eder.', action: 'Bugün telefon refleksini hissettiğinde 3 dakika başka bir şey yap.', reflectionPrompt: 'Hangi alternatifler işe yaradı?', proTip: 'Liste tut: 5 hızlı alternatif (5 squat, 1 sayfa kitap, ailenle 1 cümle).' },
  32: { title: 'Sıkıntıya Hakimiyet', teaching: 'Sıkıntı bir kas. Çalıştıkça güçlenir. İlk 30 gün önce zorluydu — şimdi sıkıntı dostun. Ona ilaç değil, alan ver. Yaratıcılık orada doğar.', action: 'Bugün 20 dakika hiçbir şey yapmadan otur.', reflectionPrompt: '20 dakika sonu zihninde ne belirdi?', proTip: 'Pencereye bak. Bedeni gözle. Düşünceleri yargılamadan izle.' },
  33: { title: 'Tek Akıl Odağı', teaching: 'Düşünmek değer üretir. Ama dağınık düşünce gürültü üretir. Tek mesele üzerinde 1 saat odaklan, 10 mesele üzerinde 1 saatten daha fazla iş çıkarırsın.', action: 'Bugün 1 saat tek konu hakkında düşün. Hiçbir şey arama.', reflectionPrompt: 'Tek odak deneyimi nasıldı?', proTip: 'Yürürken yap. Stevenote: en iyi fikirler yürüyüşte gelir.' },
  34: { title: 'Bilgi Diyeti', teaching: 'Bilgi de kalori gibi. Az ama nitelikli, çok ama boş olmaktan iyidir. Bugün tükettiğin 80% bilgi: bir hafta sonra hatırlamayacağın. Filtre koy.', action: 'Bugün 3 ana bilgi kaynağını sırala. Her biri sana ne öğretiyor?', reflectionPrompt: 'En büyük "boş" kaynak hangisi?', proTip: '"Bana hizmet ediyor mu?" filtre cümlesi. Hayır olan her kanal kapat.' },
  35: { title: 'Zevk Reseti', teaching: 'Sürekli stimulasyon = zevk eşiği yüksek. Sade hayata dönmek = küçük şeyler tekrar zevk verir. Sabah kahvesi, kuş sesi, dostluk — yeniden tat alır hale gelirsin.', action: 'Bugün küçük bir şeyden zevk al. Telefonsuz, dikkat dağılmadan.', reflectionPrompt: 'Hangi küçük şey unutulmazdı?', proTip: 'Akşam yatmadan: günün 3 küçük zevki yaz.' },
  36: { title: 'Ödül Tahmin Edilemezliği', teaching: 'Slot makinesi neden bağımlılık yapar? Ödül her seferinde gelmez — beklenti dopamini patlatır. Sosyal medya bildirimi de aynı sistem. Tahmin edilemezlik = bağımlılık. Bil ve sınırla.', action: 'Bugün bildirimleri kapatılı tut, kontrol etmek için saat kur.', reflectionPrompt: 'Beklenti hissi en çok hangi an geldi?', proTip: 'Sabit kontrol saatleri = tahmin edilebilirlik = dopamin sakin.' },
  37: { title: 'Dopamin Programlaması', teaching: 'Dopamin doğal akışı: sabah yüksek, öğleden sonra düşük, akşam orta. Yapay yükseltmeler bu akışı bozar. Doğal akışına saygı = uzun vade enerji.', action: 'Bugün 18:00 sonrası ekran kullanma. Vücudunu doğal ritme bırak.', reflectionPrompt: 'Akşam ekrnasız nasıl hissettin?', proTip: 'Akşam mavi ışık filtre + sıcak ışık. Beyin "uyku" sinyali alır.' },
  38: { title: 'Zihin Görselleştirme', teaching: 'Beyin gerçek ile hayal arasında pek fark yapmaz. 5 dakika başardığını görselleştir = pratik etmiş kadar fayda. Sporcular kullanır — sen de kullan.', action: 'Bugün 5 dakika hedefini görselleştir. Detaylı, duyusal.', reflectionPrompt: 'Hangi detaylar görselleştirmeyi güçlendirdi?', proTip: 'Sabah yatakta yap. Beyin uyandığında zaten "başarmış."' },
  39: { title: 'Dürtü Sörfü', teaching: 'Dürtüye karşı çıkmak yerine üzerine sörf yap. Dalgayı engellemezsin — yükselir, doruğa ulaşır, geçer. Tipik dürtü 10-20 dakika sürer. Geçer.', action: 'Bugün bir telefon dürtüsünü 10 dakika izle. Yapma — geçmesini bekle.', reflectionPrompt: 'Dalga ne zaman zirve yaptı?', proTip: 'Nefesle birlikte say: 4-7-8. Dürtü nefesle erir.' },
  40: { title: 'Bildirim Auditi v2', teaching: '30 günde bildirimler tekrar birikti. Yeni indirilenler, eski reaktivasyonlar. Aylık audit yap. Mart\'ta kapadığın WhatsApp grubu nisan\'da geri gelir.', action: 'Bugün tüm bildirimleri tekrar gözden geçir. Yeni gelenler kapat.', reflectionPrompt: 'Hangi yeni "sızıntı" buldun?', proTip: 'Kalender hatırlatıcısı: ayda 1, 5 dakika audit.' },
  41: { title: 'Zevk-Acı Dengesi', teaching: 'Anna Lembke: "her zevk eşit miktarda acı borçu yaratır." Sürekli zevk = sürekli huzursuzluk. Bilinçli "soğuk duş, açlık, çaba" = denge.', action: 'Bugün küçük bir rahatsızlığı aç bırak: soğuk yüz suyu, 12 saat aç, 5 dk meditasyon.', reflectionPrompt: 'Acı sonrası zevk farklı miydi?', proTip: 'Akşam küçük bir zorluk = sabah büyük bir keyif.' },
  42: { title: 'Ortayol Kontrolü', teaching: 'Detoks 42. günde — yarısını geçtin. Bedeli ne, kazanı ne? 30 günlük insan vs şu anki sen: hangi farklar net?', action: 'Bugün 5 değişikliği yaz. Bedensel, zihinsel, sosyal.', reflectionPrompt: 'En şaşırtan değişim hangisi?', proTip: 'Listeyi telefon kilit ekranına koy. Geri dönüş anı: bak.' },
  43: { title: 'Yer Değiştirme Takibi', teaching: 'Hangi alternatif işe yaradı? Hangisi yetmedi? 2 hafta sonra alternatif listesi güncellenmeli. Beyin yeni alternatif arar.', action: 'Bugün alternatif listesinde 1 yeni şey ekle, 1 eski çıkart.', reflectionPrompt: 'En güçlü alternatif hangisi?', proTip: 'Spor ve yaratıcı iş = en güçlü alternatifler.' },
  44: { title: 'Anti-Dağılma Mimarisi', teaching: 'Çevre = davranış. Telefon görünmezse alma. Sosyal medya app silinmişse açma. Çevre kurarsan disiplin kolay. James Clear: "Make it invisible, make it impossible."', action: 'Bugün 1 dağıtıcıyı fiziksel olarak görünmez yap.', reflectionPrompt: 'Görünmez yapınca refleks devam etti mi?', proTip: 'Telefonu sırt çantasına koy, çıkarmak için kalkmak gerekiyor.' },
  45: { title: 'Telefonsuz Yürüyüşler', teaching: 'Yürüyüş + telefonsuz = düşünce + görme. Yürüyüş + telefon = body olmadan zihin. Steve Jobs en zor problemleri telefonsuz yürürken çözerdi.', action: 'Bugün 30 dakika telefonsuz yürü. Kulaklık yok.', reflectionPrompt: 'Yürüyüşte hangi düşünce belirdi?', proTip: 'Sokak seslerini dinle. Gerçek dünya zaten zengin.' },
  46: { title: 'Detoks Kimliği', teaching: '"Telefon kullanmıyorum" demek geçici. "Ben dijital minimalistim" demek kalıcı. Kimliğe dönüştür. Davranış unutulur, kimlik dönmez.', action: 'Bugün kendine 1 yeni dijital kimlik etiketi koy.', reflectionPrompt: 'Hangi kimliği seçtin?', proTip: 'Aynaya bakıp her sabah söyle: "Ben ___."' },
  47: { title: 'Uzun Vade Stratejisi', teaching: '50 gün biter. Sonra ne? "Eski Ben" geri dönmek için sabırsız. Net plan olmazsa 90 günde geri yer. Bugün uzun vade kuralları yaz.', action: 'Bugün 90 günlük plan yaz: 5 kalıcı kural.', reflectionPrompt: 'En sürdürülebilir kural hangisi?', proTip: '"Pazartesi-cuma" + "hafta sonu" iki kural setini ayrı tut.' },
  48: { title: 'Final Faz Başlıyor', teaching: 'Son 3 gün. Bedenin "bitti" sinyali ister. Direnç. Ama bu son sprint = identity locked-in. Yarın kendi kendinin Patronu.', action: 'Bugün son sprintin niyetini yaz. Niye sürdürmek istiyorsun?', reflectionPrompt: 'Niyetin ne kadar derin?', proTip: '"Niye"yi cüzdana koy. Geri dönüş anı bak.' },
  49: { title: '49 Gün İçinde', teaching: '49 günde dopamin sistemi yeniden kalibre oldu. Sıkıntıya tahammül 10x arttı. Anlık zevkler artık tatmin etmiyor. Bu yeni baseline. Koru.', action: 'Bugün 49 günde değişen 10 şeyi yaz.', reflectionPrompt: 'En unutulmaz değişim hangisi?', proTip: 'Listeyi screenshot al, telefon arka planı yap.' },
  50: { title: 'Tamamlandı — Master', teaching: '50 gün. Çoğu insan 5 günde vazgeçer. Sen masteri tamamladın. Yeni Sen = sıkıntıya hakim, dürtüye sörf, dijital minimalist. Diploma yok — sadece ayna.', action: 'Bugün aynaya bak. Yeni Sen\'i selamla.', reflectionPrompt: '50 gün önceki sen şimdi olmak ister miydi?', proTip: 'Bir başka path başlat. 7 gün dinlen, sonra mind veya body discipline.' },
};

const NEW_EN = {
  31: { title: 'Replacement Habits', teaching: 'Breaking addiction needs replacement, not just prohibition. When phone urge hits: walk, drink water, journal. Brain doesn\'t accept "absence" — it accepts "swap."', action: 'Today, on phone reflex, do something else for 3 minutes.', reflectionPrompt: 'Which alternatives worked?', proTip: 'List 5 quick alternatives (5 squats, 1 page book, 1 sentence to family).' },
  32: { title: 'Boredom Mastery', teaching: 'Boredom is a muscle. Trains stronger. First 30 days hard — now boredom is your friend. Give it space, not medicine. Creativity is born there.', action: 'Today sit doing nothing for 20 minutes.', reflectionPrompt: 'What appeared at minute 20?', proTip: 'Look at a window. Watch your body. Observe thoughts without judging.' },
  33: { title: 'Single-Mind Focus', teaching: 'Thinking creates value. Scattered thinking creates noise. Focus 1 hour on one issue, you\'ll get more done than 1 hour on 10 issues.', action: 'Today think on one topic for 1 hour. Don\'t search anything.', reflectionPrompt: 'How was the single-focus experience?', proTip: 'Do it walking. Best ideas come during walks.' },
  34: { title: 'Information Diet', teaching: 'Information is like calories. Few but quality > many but empty. 80% of info you consume today: forgotten in a week. Filter.', action: 'Today list 3 main info sources. What does each teach you?', reflectionPrompt: 'Biggest "empty" source?', proTip: '"Does it serve me?" — filter sentence. Close any "no."' },
  35: { title: 'Pleasure Reset', teaching: 'Constant stimulation = high pleasure threshold. Returning to simple = small things become joys again. Morning coffee, bird sounds, friendship — taste returns.', action: 'Today enjoy a small thing. Phoneless, focused.', reflectionPrompt: 'Which small thing was unforgettable?', proTip: 'Before bed: write 3 small joys of the day.' },
  36: { title: 'Reward Unpredictability', teaching: 'Why are slot machines addictive? Reward isn\'t every time — anticipation pumps dopamine. Social media is the same. Unpredictability = addiction. Know and limit.', action: 'Today keep notifications off, set fixed check times.', reflectionPrompt: 'When did the anticipation feeling come most?', proTip: 'Fixed check times = predictable = dopamine calm.' },
  37: { title: 'Dopamine Schedule', teaching: 'Dopamine\'s natural flow: morning high, afternoon low, evening medium. Artificial peaks disrupt the flow. Respecting the flow = long-term energy.', action: 'Today no screens after 18:00. Let body return to natural rhythm.', reflectionPrompt: 'How did screen-free evening feel?', proTip: 'Evening blue-light filter + warm light. Brain reads "sleep."' },
  38: { title: 'Mental Imagery', teaching: 'Brain barely separates real from imagined. 5 min of seeing yourself succeed = practice-equivalent. Athletes use it — you can too.', action: 'Today visualize your goal for 5 min. Detailed, sensory.', reflectionPrompt: 'Which details strengthened the imagery?', proTip: 'Do it in bed in morning. Brain wakes already "succeeded."' },
  39: { title: 'Urge Surfing', teaching: 'Don\'t fight urges — surf them. You can\'t stop a wave — it rises, peaks, passes. Typical urge = 10-20 min. It passes.', action: 'Today watch a phone urge for 10 min. Don\'t act — wait it out.', reflectionPrompt: 'When did the wave peak?', proTip: 'Count with breath: 4-7-8. Urge dissolves with breath.' },
  40: { title: 'Notification Audit v2', teaching: 'Notifications creep back in 30 days. New downloads, old reactivations. Monthly audit needed. The WhatsApp group you muted in March returns in April.', action: 'Today review all notifications again. Close new ones.', reflectionPrompt: 'What new "leak" did you find?', proTip: 'Calendar reminder: monthly, 5-min audit.' },
  41: { title: 'Pleasure-Pain Balance', teaching: 'Anna Lembke: "every pleasure creates equal pain debt." Constant pleasure = constant unease. Conscious "cold shower, hunger, effort" = balance.', action: 'Today take small discomfort: cold face wash, 12-hour fast, 5-min meditation.', reflectionPrompt: 'Was pleasure different after the pain?', proTip: 'Small evening hardship = bigger morning joy.' },
  42: { title: 'Mid-Path Check', teaching: 'Detox at day 42 — past halfway. Cost vs benefit? 30-days-ago you vs now: which differences are clear?', action: 'Today list 5 changes. Body, mind, social.', reflectionPrompt: 'Most surprising change?', proTip: 'Put list on phone lock screen. Backslide moment: look.' },
  43: { title: 'Replacement Tracking', teaching: 'Which alternative worked? Which didn\'t? After 2 weeks the list updates itself. Brain seeks new alternatives.', action: 'Today add 1 new alternative, remove 1 old one.', reflectionPrompt: 'Which alternative is strongest?', proTip: 'Sport and creative work = strongest alternatives.' },
  44: { title: 'Anti-Distraction Architecture', teaching: 'Environment = behavior. Phone invisible = no grab. Social-media app deleted = no open. Architect your environment, discipline becomes easy. James Clear: "Make it invisible, make it impossible."', action: 'Today make 1 distraction physically invisible.', reflectionPrompt: 'Did the reflex continue when invisible?', proTip: 'Phone in backpack — must stand to grab.' },
  45: { title: 'Phone-Free Walks', teaching: 'Walk + phoneless = thought + sight. Walk + phone = mind without body. Steve Jobs solved hardest problems phoneless on walks.', action: 'Today take a 30-minute phoneless walk. No earbuds.', reflectionPrompt: 'What thought arose?', proTip: 'Listen to street sounds. The real world is rich.' },
  46: { title: 'Detox Identity', teaching: '"I don\'t use my phone" = temporary. "I am a digital minimalist" = permanent. Convert to identity. Behavior is forgotten, identity stays.', action: 'Today claim 1 new digital identity label.', reflectionPrompt: 'Which identity?', proTip: 'Speak it in the mirror each morning: "I am ___."' },
  47: { title: 'Long-Term Strategy', teaching: '50 days end. Then what? Old You is impatient to return. Without a plan, in 90 days you\'re back. Today write the long-term rules.', action: 'Today write a 90-day plan: 5 permanent rules.', reflectionPrompt: 'Most sustainable rule?', proTip: 'Keep "weekday" + "weekend" rule sets separate.' },
  48: { title: 'Final Phase Begins', teaching: 'Last 3 days. Body wants the "done" signal. Resistance. But this last sprint = identity locked-in. Tomorrow you are your own boss.', action: 'Today write the final-sprint intent. Why continue?', reflectionPrompt: 'How deep is your why?', proTip: 'Put the "why" in your wallet. Backslide moment: look.' },
  49: { title: '49 Days In', teaching: 'In 49 days the dopamine system has recalibrated. Boredom tolerance up 10x. Instant pleasures no longer satisfy. New baseline. Protect it.', action: 'Today list 10 things that changed in 49 days.', reflectionPrompt: 'Most unforgettable change?', proTip: 'Screenshot the list, set as phone wallpaper.' },
  50: { title: 'Complete — Master', teaching: '50 days. Most quit at 5. You finished the master. New You = boredom-master, urge-surfer, digital minimalist. No diploma — just the mirror.', action: 'Today look in the mirror. Greet New You.', reflectionPrompt: 'Would 50-days-ago you want to be now?', proTip: 'Start another path. Rest 7 days, then mind or body discipline.' },
};

const QUIZ_TR = {
  31: [{ q: 'Yer değiştirme nedir?', options: ['Yasak', 'Alternatif koyma', 'İhmal', 'Saklamak'], correct: 1, explain: 'Beyin yokluk kabul etmez, değişim kabul eder.' }, { q: 'En güçlü alternatif?', options: ['Telefon', 'Hareket/yaratıcılık', 'Yemek', 'Uyku'], correct: 1, explain: 'Hareket + yaratıcılık dopamini sağlıklı yükseltir.' }],
  32: [{ q: 'Sıkıntı nedir?', options: ['Hastalık', 'Bir kas', 'Ödül', 'Kaza'], correct: 1, explain: 'Çalıştıkça güçlenir.' }, { q: 'Sıkıntı ne kadarda dostlaşır?', options: ['1 hafta', '30 gün', '6 ay', 'Asla'], correct: 1, explain: '~30 gün sonra dostluk başlar.' }],
  33: [{ q: 'Tek odak süresi öneri?', options: ['10 dk', '1 saat', '8 saat', 'Sürekli'], correct: 1, explain: '1 saat tek konu = derin işlem.' }, { q: 'Yürüyerek düşünme tekniği?', options: ['Ok', 'En iyi fikirler', 'Yorgunluk', 'Etkisiz'], correct: 1, explain: 'En iyi fikirler yürüyüşte gelir.' }],
  34: [{ q: 'Bilgi diyeti filtre cümlesi?', options: ['Trend?', 'Bana hizmet ediyor mu?', 'Popüler mi?', 'Yeni mi?'], correct: 1, explain: 'Hayır olan kanal = noise.' }, { q: 'Az ama nitelikli?', options: ['Yanlış', 'İyi diyet', 'Risk', 'Eski'], correct: 1, explain: 'Az + nitelikli > çok + boş.' }],
  35: [{ q: 'Zevk eşiği nasıl yükselir?', options: ['Çalışma', 'Sürekli stimulasyon', 'Açlık', 'Spor'], correct: 1, explain: 'Sürekli yapay yüksek zevkler eşiği büyütür.' }, { q: 'Reset nasıl olur?', options: ['Daha fazla zevk', 'Sade hayata dön', 'Uyu', 'Kork'], correct: 1, explain: 'Sadelik = küçük zevkler tekrar tatlı.' }],
  36: [{ q: 'Slot makinesi neden bağımlılık?', options: ['Şans', 'Tahmin edilemez ödül', 'Para', 'Renk'], correct: 1, explain: 'Beklenti dopamini patlatır.' }, { q: 'Çözüm?', options: ['Sürekli kontrol', 'Sabit kontrol saatleri', 'Hiç bakma', 'Telefonu kır'], correct: 1, explain: 'Sabit zaman = tahmin edilebilir = sakin.' }],
  37: [{ q: 'Dopamin doğal akışı?', options: ['Akşam zirve', 'Sabah yüksek-akşam orta', 'Sürekli aynı', 'Rastgele'], correct: 1, explain: 'Sabah yüksek, öğle düşük, akşam orta.' }, { q: 'Saat 18 sonra ne yap?', options: ['Daha çok ekran', 'Ekran kıs', 'Kahve iç', 'Çalış'], correct: 1, explain: 'Akşam doğal akış için ekran kıs.' }],
  38: [{ q: 'Görselleştirme süresi?', options: ['1 dk', '5 dk', '1 saat', '24 saat'], correct: 1, explain: '5 dk yeter, sporcular kullanır.' }, { q: 'Beyin gerçek-hayal farkı?', options: ['Net', 'Az', 'Çok büyük', 'Yok'], correct: 1, explain: 'Beyin pek fark etmez, pratik etkisi var.' }],
  39: [{ q: 'Urge sörfü nedir?', options: ['Direnç', 'Üzerine sörf yap', 'Engelle', 'Yok say'], correct: 1, explain: 'Dalga gibi: yükselir-zirve-geçer.' }, { q: 'Tipik dürtü süresi?', options: ['1 dk', '10-20 dk', '1 saat', '1 gün'], correct: 1, explain: '10-20 dk sonra dürtü erir.' }],
  40: [{ q: 'Audit ne sıklıkla?', options: ['1 kez', 'Aylık', 'Yıllık', 'Asla'], correct: 1, explain: 'Bildirimler 30 günde tekrar birikir.' }, { q: 'Audit süresi?', options: ['1 saat', '5 dakika', '1 gün', '0'], correct: 1, explain: '5 dk yeter.' }],
  41: [{ q: 'Lembke prensibi?', options: ['Zevk hep iyi', 'Zevk = acı borçu', 'Acı kötü', 'Denge yok'], correct: 1, explain: 'Her zevk acı borçu yaratır.' }, { q: 'Denge örneği?', options: ['Sürekli zevk', 'Bilinçli zorluk', 'Ne yapacağım', 'Boş'], correct: 1, explain: 'Soğuk duş, açlık, çaba = denge.' }],
  42: [{ q: 'Yarıyolda ne yap?', options: ['Vazgeç', 'Geriye bak + ölç', 'Hızlandır', 'Aynı'], correct: 1, explain: '5 değişikliği yaz, listele.' }, { q: 'Liste nereye?', options: ['Çek defteri', 'Telefon kilit ekranı', 'Kafan', 'Çöp'], correct: 1, explain: 'Görünür yer = hatırlatma.' }],
  43: [{ q: 'Alternatif takibi?', options: ['Sabit', '2 haftada güncelle', 'Asla', '1 yıl'], correct: 1, explain: 'Beyin yeni alternatif arar.' }, { q: 'En güçlü alternatifler?', options: ['Pasif tüketim', 'Spor + yaratıcılık', 'Uyku', 'Yemek'], correct: 1, explain: 'Aktif + yaratıcı = en güçlü.' }],
  44: [{ q: 'Çevre ne yapar?', options: ['Etkisiz', 'Davranışı şekillendirir', 'Sadece güzel', 'Pahalı'], correct: 1, explain: 'Çevre = davranış.' }, { q: 'Clear formülü?', options: ['Make it impossible', 'Make it visible', 'Make it good', 'Buy it'], correct: 0, explain: 'Görünmez/imkânsız yap.' }],
  45: [{ q: 'Telefonsuz yürüyüş etkisi?', options: ['Yok', 'Düşünce + görme', 'Yorgunluk', 'Sıkıntı'], correct: 1, explain: 'Beden + zihin birlikte.' }, { q: 'Süre?', options: ['5 dk', '30 dk', '5 saat', '0'], correct: 1, explain: '30 dk optimum.' }],
  46: [{ q: 'Davranış vs kimlik?', options: ['Aynı', 'Kimlik kalıcı, davranış geçici', 'Kimlik daha zayıf', 'Yok'], correct: 1, explain: 'Kimlik = uzun vade.' }, { q: 'Kimlik nasıl pekişir?', options: ['Düşünme', 'Tekrar söyle', 'Yaz', 'Unut'], correct: 1, explain: 'Aynaya günlük tekrar.' }],
  47: [{ q: '50 gün sonu strateji?', options: ['Bitti', '90 günlük plan', 'Hiç', 'Tatil'], correct: 1, explain: 'Sonrası kayma riski.' }, { q: 'Optimum kural sayısı?', options: ['1', '5', '20', '100'], correct: 1, explain: '5 net kural sürdürülebilir.' }],
  48: [{ q: 'Final fazda hisset?', options: ['Kolay', 'Direnç', 'Yorgunluk', 'Sıkıntı'], correct: 1, explain: 'Beden "bitti" sinyali ister.' }, { q: 'Niyet nereye?', options: ['Kafa', 'Cüzdan / görünür yer', 'Hatırla', 'Çöp'], correct: 1, explain: 'Görünür = hatırlatma.' }],
  49: [{ q: '49 günde dopamin?', options: ['Bozulur', 'Kalibre olur', 'Aynı', 'Bitirilir'], correct: 1, explain: 'Sistem yeniden ayarlanır.' }, { q: 'Sıkıntı toleransı?', options: ['Düşer', '10x artar', 'Aynı', 'Yok olur'], correct: 1, explain: 'Sıkıntıya tahammül büyük artar.' }],
  50: [{ q: 'Master ne demek?', options: ['Sertifika', 'Yeni Sen', 'Para', 'Ünvan'], correct: 1, explain: 'Aynadaki yeni sen.' }, { q: 'Sonraki path?', options: ['Hemen', '7 gün dinlen', '1 ay bekle', 'Asla'], correct: 1, explain: '7 gün dinlen, sonra devam.' }],
};

const QUIZ_EN = {
  31: [{ q: 'Replacement habit means?', options: ['Ban', 'Substitute', 'Ignore', 'Hide'], correct: 1, explain: 'Brain accepts swap, not absence.' }, { q: 'Strongest alternative?', options: ['Phone', 'Movement/creativity', 'Food', 'Sleep'], correct: 1, explain: 'Movement + creative = healthy dopamine.' }],
  32: [{ q: 'Boredom is?', options: ['Sickness', 'A muscle', 'Reward', 'Accident'], correct: 1, explain: 'Trains stronger.' }, { q: 'When does boredom befriend?', options: ['1 week', '~30 days', '6 months', 'Never'], correct: 1, explain: '~30 days for friendship.' }],
  33: [{ q: 'Single focus duration?', options: ['10 min', '1 hour', '8 hours', 'Always'], correct: 1, explain: '1 hour = deep processing.' }, { q: 'Walking + thinking?', options: ['No', 'Best ideas', 'Tired', 'No effect'], correct: 1, explain: 'Best ideas come walking.' }],
  34: [{ q: 'Info diet filter sentence?', options: ['Trend?', 'Does it serve me?', 'Popular?', 'New?'], correct: 1, explain: 'Any "no" = noise.' }, { q: 'Few but quality?', options: ['Wrong', 'Good diet', 'Risk', 'Old'], correct: 1, explain: 'Few + quality > many + empty.' }],
  35: [{ q: 'How does pleasure threshold rise?', options: ['Work', 'Constant stimulation', 'Hunger', 'Sport'], correct: 1, explain: 'Constant artificial peaks raise threshold.' }, { q: 'Reset by?', options: ['More pleasure', 'Return to simple', 'Sleep', 'Fear'], correct: 1, explain: 'Simplicity = small pleasures sweet again.' }],
  36: [{ q: 'Why slot machine addictive?', options: ['Luck', 'Unpredictable reward', 'Money', 'Color'], correct: 1, explain: 'Anticipation pumps dopamine.' }, { q: 'Solution?', options: ['Always check', 'Fixed check times', 'Never check', 'Break phone'], correct: 1, explain: 'Fixed time = predictable = calm.' }],
  37: [{ q: 'Dopamine natural flow?', options: ['Evening peak', 'Morning high - evening medium', 'Always same', 'Random'], correct: 1, explain: 'Morning high, noon low, evening medium.' }, { q: 'After 18:00 do?', options: ['More screen', 'Reduce screen', 'Coffee', 'Work'], correct: 1, explain: 'Evening reduce screen for natural flow.' }],
  38: [{ q: 'Visualization duration?', options: ['1 min', '5 min', '1 hour', '24 hours'], correct: 1, explain: '5 min enough, athletes use it.' }, { q: 'Brain real-imagined gap?', options: ['Clear', 'Small', 'Huge', 'None'], correct: 1, explain: 'Brain barely separates — practice effect.' }],
  39: [{ q: 'Urge surfing means?', options: ['Resist', 'Surf the wave', 'Block', 'Ignore'], correct: 1, explain: 'Like a wave: rises, peaks, passes.' }, { q: 'Typical urge duration?', options: ['1 min', '10-20 min', '1 hour', '1 day'], correct: 1, explain: 'Urge dissolves in 10-20 min.' }],
  40: [{ q: 'How often audit?', options: ['Once', 'Monthly', 'Yearly', 'Never'], correct: 1, explain: 'Notifications creep back in 30 days.' }, { q: 'Audit duration?', options: ['1 hour', '5 minutes', '1 day', '0'], correct: 1, explain: '5 min suffices.' }],
  41: [{ q: 'Lembke principle?', options: ['Pleasure always good', 'Pleasure = pain debt', 'Pain bad', 'No balance'], correct: 1, explain: 'Each pleasure creates pain debt.' }, { q: 'Balance example?', options: ['Constant pleasure', 'Conscious hardship', 'No idea', 'Empty'], correct: 1, explain: 'Cold shower, hunger, effort = balance.' }],
  42: [{ q: 'Mid-path do?', options: ['Quit', 'Look back + measure', 'Speed up', 'Same'], correct: 1, explain: 'List 5 changes.' }, { q: 'List where?', options: ['Drawer', 'Phone lock screen', 'Head', 'Trash'], correct: 1, explain: 'Visible = reminder.' }],
  43: [{ q: 'Alternative tracking?', options: ['Fixed', 'Update biweekly', 'Never', '1 year'], correct: 1, explain: 'Brain seeks new alternatives.' }, { q: 'Strongest alternatives?', options: ['Passive consumption', 'Sport + creativity', 'Sleep', 'Food'], correct: 1, explain: 'Active + creative = strongest.' }],
  44: [{ q: 'What does environment do?', options: ['No effect', 'Shapes behavior', 'Just looks', 'Costs'], correct: 1, explain: 'Environment = behavior.' }, { q: 'Clear\'s formula?', options: ['Make it impossible', 'Make it visible', 'Make it good', 'Buy it'], correct: 0, explain: 'Make invisible/impossible.' }],
  45: [{ q: 'Phoneless walk effect?', options: ['None', 'Thought + sight', 'Tired', 'Boring'], correct: 1, explain: 'Body + mind together.' }, { q: 'Duration?', options: ['5 min', '30 min', '5 hours', '0'], correct: 1, explain: '30 min optimum.' }],
  46: [{ q: 'Behavior vs identity?', options: ['Same', 'Identity permanent, behavior temp', 'Identity weaker', 'None'], correct: 1, explain: 'Identity = long-term.' }, { q: 'Identity solidifies via?', options: ['Thinking', 'Repeat speaking', 'Writing', 'Forget'], correct: 1, explain: 'Daily mirror repeat.' }],
  47: [{ q: 'After 50 days strategy?', options: ['Done', '90-day plan', 'Nothing', 'Vacation'], correct: 1, explain: 'After-risk: backslide.' }, { q: 'Optimal rule count?', options: ['1', '5', '20', '100'], correct: 1, explain: '5 clear rules sustainable.' }],
  48: [{ q: 'Final phase feeling?', options: ['Easy', 'Resistance', 'Tired', 'Bored'], correct: 1, explain: 'Body wants "done" signal.' }, { q: 'Intent where?', options: ['Head', 'Wallet/visible', 'Remember', 'Trash'], correct: 1, explain: 'Visible = reminder.' }],
  49: [{ q: '49-day dopamine?', options: ['Broken', 'Recalibrated', 'Same', 'Done'], correct: 1, explain: 'System resets.' }, { q: 'Boredom tolerance?', options: ['Drops', 'Up 10x', 'Same', 'Gone'], correct: 1, explain: 'Massive tolerance increase.' }],
  50: [{ q: 'Master means?', options: ['Certificate', 'New You', 'Money', 'Title'], correct: 1, explain: 'New you in mirror.' }, { q: 'Next path?', options: ['Now', 'Rest 7 days', '1 month', 'Never'], correct: 1, explain: 'Rest 7 days, then continue.' }],
};

function buildLessons(newContent, quizMap) {
  const out = {};
  for (const [order, lesson] of Object.entries(newContent)) {
    out[order] = {
      title: lesson.title,
      teaching: lesson.teaching,
      action: lesson.action,
      reflectionPrompt: lesson.reflectionPrompt,
      proTip: lesson.proTip,
      quiz: quizMap[order] || [],
    };
  }
  return out;
}

function applyToFile(filePath, pathId, lessonsMerge) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (!data.lessons[pathId]) data.lessons[pathId] = {};
  for (const [order, fields] of Object.entries(lessonsMerge)) {
    data.lessons[pathId][order] = { ...(data.lessons[pathId][order] || {}), ...fields };
  }
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
}

const TR_MERGE = buildLessons(NEW_TR, QUIZ_TR);
const EN_MERGE = buildLessons(NEW_EN, QUIZ_EN);
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.tr.json'), 'dopamine-detox', TR_MERGE);
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.en.json'), 'dopamine-detox', EN_MERGE);
console.log(`✓ Dopamine-detox 31-50 seeded — ${Object.keys(NEW_TR).length} new lessons × 2 langs`);
