/** Mind-discipline lessons 31-50 (advanced). TR + EN. */
const fs = require('fs');
const path = require('path');

const NEW_TR = {
  31: { title: 'Ultradian Ritm', teaching: 'Beyin 90-120 dakika döngülerle çalışır. Bu ritmin sonunda dikkat düşer. Çözüm: 90 dakika derin iş + 20 dakika gerçek mola. Pomodoro\'nun büyük abi versiyonu.', action: 'Bugün 90-20 ritmiyle çalış.', reflectionPrompt: '90 dakika sonu ne hissettin?', proTip: 'Mola tam mola: telefon yok, ekran yok. Pencere bak, su iç.' },
  32: { title: 'Default Mode Network', teaching: 'Beyin "boş" zaman = DMN aktif. Bu mod yaratıcılık + öz farkındalık üretir. Sürekli stimulasyon = DMN kapalı = boş yaratıcılık. Ekransız 30 dk şart.', action: 'Bugün 30 dakika hiç ekran kullanma.', reflectionPrompt: 'Ekransız zihninde ne belirdi?', proTip: 'Yürüyüş + ekransız = DMN max. Gözlem yap.' },
  33: { title: 'Zihinsel Modeller', teaching: 'Charlie Munger: "100 mental modelini öğren, dünyayı çözersin." Birinci ilkeler, fırsat maliyeti, ikinci derece etkileri. Her hafta 1 yeni model öğren.', action: 'Bugün 1 zihinsel model araştır.', reflectionPrompt: 'Hangi modeli seçtin?', proTip: 'Farnam Street blog = 100\'lerce mental model.' },
  34: { title: 'Birinci İlkeler Düşüncesi', teaching: 'Elon Musk: "varsayımlardan değil, fizikten başla." Her problem için: temel gerçekler ne? Genel kabul edilenleri sorgula. Roket fiyatları %90 düştü çünkü Musk böyle düşündü.', action: 'Bugün bir varsayımı sorgula. "Niye böyle?"', reflectionPrompt: 'Hangi varsayım çürüdü?', proTip: '"Niye?" 5 kez üst üste sor. Köke iner.' },
  35: { title: 'Katedral Etkisi', teaching: 'Yüksek tavanlı odalar yaratıcı düşünce, alçak tavanlı odalar detay düşünce yaratır. Mekan = zihin durumu. Yaratıcı iş için yüksek tavanlı kafede çalış.', action: 'Bugün yüksek tavanlı bir mekanda 1 saat çalış.', reflectionPrompt: 'Mekan zihnini nasıl değiştirdi?', proTip: 'Park, kütüphane, müze cafe = yaratıcı yer.' },
  36: { title: 'Tek Görev Mastery', teaching: 'Multitasking myth — tek görev tek başarı. Notification yok, sekme tek, müzik instrümental. 90 dakika tam single-task = haftalık iş.', action: 'Bugün 90 dakika tam single-task.', reflectionPrompt: 'Verim ne kadar arttı?', proTip: '\"Do not disturb\" mode = telefon + Mac. Önemsiz çağrı geçmez.' },
  37: { title: 'Dikkat Kalıntısı', teaching: 'Sophie Leroy: bir görevden diğerine geçince beyin %33 ilk görevde kalır. Bu "attention residue." Çözüm: tam bitir, sonra geç. Yarım bırakma.', action: 'Bugün her görevi tam bitir, sonra geç.', reflectionPrompt: 'Tam bitirme zihninde ne yaptı?', proTip: 'Geçişler arası 30 saniye derin nefes = residue temizler.' },
  38: { title: '4 Saatlik İş Günü', teaching: 'Tim Ferriss: "8 saat iş = 4 saat boşaltma." Çoğu beyin 4 saat derin iş üretir. 5. saat = düşük getiri. 4 saat odakla, geri kalan: spor, sosyal, dinlenme.', action: 'Bugün 4 saat tam odakla çalış. Sonra dur.', reflectionPrompt: '4 saat sonu ne hissettin?', proTip: 'Saatleri 09-13 ya da 10-14 yap. Beyin sabah daha keskin.' },
  39: { title: 'Sıkıntı Toleransı', teaching: 'Dijital nesil sıkıntıyı kaldıramaz — anında telefona uzanır. Sıkıntıya tolerans = zihin gücü. Günde 30 dakika sıkıntıya izin ver.', action: 'Bugün 30 dakika sıkıntı pratik et.', reflectionPrompt: 'Sıkıntı sonrası zihinsel netlik?', proTip: 'Tuvalette telefon kullanma. 5 dakika başlangıç.' },
  40: { title: 'Bilişsel Çıkış', teaching: 'Beyin yorulduğunda "ısrar etme." Doğru çıkış noktasını tanı: yürüyüş, duş, yemek. 15 dakika çıkış = saatlerin verimi.', action: 'Bugün takıldığında çıkış al, 15 dk sonra geri dön.', reflectionPrompt: 'Çıkış nasıl yardımcı oldu?', proTip: 'Çıkışta düşünme — sadece beden hareketi. Beyin arka planda çözer.' },
  41: { title: 'Karar Çerçeveleri', teaching: 'Her gün ~35,000 karar = irade gücü tükenir. Çerçeve = pre-decision. "Hafta içi alkol içmem." Karar yok — uygula.', action: 'Bugün 3 karar çerçevesi yaz, 30 gün uygula.', reflectionPrompt: 'Hangi alanlar çerçeve istedi?', proTip: 'Çerçeveleri yazılı tut. Hafıza güvenilmez.' },
  42: { title: '80/20 Zihin', teaching: 'Pareto: %20 iş %80 sonuç. Bugün yaptığın 10 işten en kritik 2\'sini bul, geri kalanı kes. 80/20 her hafta uygulanır.', action: 'Bugün 10 görevden 2\'sini seç, kalanı erteleı veya delege et.', reflectionPrompt: 'Hangi 2 işti kritik?', proTip: 'Cuma akşamı haftaya 80/20 yap. Pazartesi keskin başla.' },
  43: { title: 'Tersine Düşünme', teaching: 'Munger: "ne yapmamamı bilirsem, ne yapmamı zaten biliyorum." Hedefe ulaşmak yerine, başarısızlığı önlemek üzerine kur. Tersini düşün.', action: 'Bugün hedef için 5 başarısızlık nedeni yaz.', reflectionPrompt: 'En riskli neden hangisi?', proTip: 'Premortem yöntemi: "1 yıl sonra başarısız oldum, neden?"' },
  44: { title: 'Zihinsel Çıkartma', teaching: 'Stoa tekniği: bir şey kaybetseydim ne olurdu? Mental subtraction = şükran kasını çalıştırır. Sahip olduklarını yeniden değerli görmek.', action: 'Bugün sahip olduğun 1 şeyi kaybetmeyi mental olarak yaşa.', reflectionPrompt: 'Hangi varlık daha değerli geldi?', proTip: 'Akşam 1 dakika: bugün gerçekleşen 3 iyiliği görselleştir.' },
  45: { title: 'Günlük Mind Map', teaching: 'Mind map = beynin doğal yapısı. Lineer not yerine merkez + dallar. Karmaşık fikri 30 saniyede tutarlı kıl.', action: 'Bugün 1 problemi mind map ile çöz.', reflectionPrompt: 'Mind map sezgini güçlendirdi mi?', proTip: 'Boş kâğıt + renkli kalem. Telefonun mind map app yorucu.' },
  46: { title: 'Hafıza Sarayı', teaching: 'Antik teknik: hatırlamak istediğin şeyi tanıdık bir mekana yerleştir. Çocukluk evi = saraydı. 5 odaya 5 fikir = 1 hafta hatırlanır.', action: 'Bugün 5 fikri hafıza sarayına yerleştir.', reflectionPrompt: 'Yarın hatırlayacak mısın?', proTip: 'Komik + abartılı görseller en kalıcı.' },
  47: { title: 'Aralıklı Tekrarlama', teaching: 'Spaced repetition = optimum öğrenme. 1 gün, 3 gün, 7 gün, 14 gün, 30 gün. Bu aralıklarla tekrar = uzun vade hafıza. Anki app altın standart.', action: 'Bugün son 7 günde öğrendiğini kısa tekrar et.', reflectionPrompt: 'Hangi öğrenme zaten unutulmuştu?', proTip: 'Anki 5 dk = günlük tekrar yeterli.' },
  48: { title: 'Final Sprint', teaching: 'Son 3 gün. 50 günde zihin disiplinin sıfırdan master\'a. Bu sprint = lock-in. Yarın özünü değiştirdin.', action: 'Bugün son sprintin niyetini yaz.', reflectionPrompt: 'En değişen zihinsel alışkanlık hangisi?', proTip: 'Niyeti pano yap, 30 gün ulaşılan yere as.' },
  49: { title: '49 Gün İçinde', teaching: '49 günde tek odak, derin iş, 80/20, mental modeller artık otomatik. Yeni baseline = master beyin. 10 değişiklik listele.', action: 'Bugün 49 günde değişen 10 zihinsel alışkanlığı yaz.', reflectionPrompt: 'En unutulmaz değişim?', proTip: 'Listeyi tek bir A4\'e yaz. Çalışma masasına as.' },
  50: { title: 'Master Tamamlandı', teaching: '50 gün. Çoğu insanın zihni dağıtık. Senin ki master. Sıkıntı dostun, derin iş dilin, mental modeller silahların. Disiplin = yeni IQ.', action: 'Bugün aynaya bak. Yeni Sen\'i selamla.', reflectionPrompt: '50 gün önceki sen şimdi olmak ister miydi?', proTip: '7 gün dinlen, sonra body veya money discipline.' },
};

const NEW_EN = {
  31: { title: 'Ultradian Rhythm', teaching: 'Brain works in 90-120 min cycles. End of cycle = focus drops. Solution: 90 min deep work + 20 min real break. Pomodoro\'s big brother.', action: 'Today work in 90-20 rhythm.', reflectionPrompt: 'How did you feel after 90 minutes?', proTip: 'Real break = no phone, no screen. Look out window, drink water.' },
  32: { title: 'Default Mode Network', teaching: 'Brain "empty" time = DMN active. This mode produces creativity + self-awareness. Constant stimulation = DMN off = no creativity. 30 min screen-free essential.', action: 'Today 30 min no screens.', reflectionPrompt: 'What appeared without screens?', proTip: 'Walk + screen-free = max DMN. Observe.' },
  33: { title: 'Mental Models', teaching: 'Charlie Munger: "Learn 100 mental models, you understand the world." First principles, opportunity cost, second-order effects. Each week, 1 new model.', action: 'Today research 1 mental model.', reflectionPrompt: 'Which model did you pick?', proTip: 'Farnam Street blog = hundreds of mental models.' },
  34: { title: 'First Principles', teaching: 'Elon Musk: "Start from physics, not assumptions." For each problem: what are the basic truths? Question accepted norms. Rocket prices dropped 90% this way.', action: 'Today question one assumption. "Why this way?"', reflectionPrompt: 'Which assumption broke?', proTip: 'Ask "why?" 5 times. You reach the root.' },
  35: { title: 'Cathedral Effect', teaching: 'High ceilings → creative thinking. Low ceilings → detail thinking. Space = mind state. For creative work, high-ceiling cafe.', action: 'Today work 1 hour in a high-ceiling spot.', reflectionPrompt: 'How did the space change your mind?', proTip: 'Park, library, museum cafe = creative spots.' },
  36: { title: 'Single-Task Mastery', teaching: 'Multitask is myth. Single task = single win. No notifications, single tab, instrumental music. 90 min full single-task = a week of work.', action: 'Today 90 min full single-task.', reflectionPrompt: 'How much did productivity rise?', proTip: '"Do not disturb" on phone + Mac. Only urgent gets through.' },
  37: { title: 'Attention Residue', teaching: 'Sophie Leroy: switching tasks leaves 33% of attention on previous one. Solution: finish completely, then move on. Don\'t leave half-done.', action: 'Today finish each task fully before moving on.', reflectionPrompt: 'What did full-finishing do mentally?', proTip: '30 sec deep breath between transitions clears residue.' },
  38: { title: '4-Hour Workday', teaching: 'Tim Ferriss: "8h work = 4h emptying time." Most brains produce 4 hours of deep work. Hour 5 = low return. 4 hours focused, rest: sport, social, rest.', action: 'Today work 4 fully focused hours, then stop.', reflectionPrompt: 'How did you feel after 4 hours?', proTip: 'Hours 09-13 or 10-14. Brain sharper in morning.' },
  39: { title: 'Boredom Tolerance', teaching: 'Digital generation can\'t tolerate boredom — instant phone grab. Boredom tolerance = mental strength. Allow 30 min boredom daily.', action: 'Today practice 30 min boredom.', reflectionPrompt: 'Mental clarity after boredom?', proTip: 'No phone in bathroom. 5 min start.' },
  40: { title: 'Cognitive Off-Ramps', teaching: 'When brain tires, don\'t insist. Recognize the right exit: walk, shower, food. 15-min off-ramp = hours of saved productivity.', action: 'Today take an off-ramp when stuck, return in 15 min.', reflectionPrompt: 'How did the off-ramp help?', proTip: 'Don\'t think during exit — just body movement. Brain solves in background.' },
  41: { title: 'Decision Frameworks', teaching: 'Brain makes ~35K daily decisions = willpower drain. Framework = pre-decision. "No alcohol weekdays." No decision — execute.', action: 'Today write 3 decision frameworks, apply 30 days.', reflectionPrompt: 'Which areas needed framework?', proTip: 'Keep frameworks written. Memory unreliable.' },
  42: { title: '80/20 Mind', teaching: 'Pareto: 20% input = 80% output. Of 10 tasks today, find the most critical 2, cut the rest. Apply 80/20 weekly.', action: 'Today choose 2 of 10 tasks, defer or delegate the rest.', reflectionPrompt: 'Which 2 were critical?', proTip: 'Friday evening 80/20 for next week. Monday sharp start.' },
  43: { title: 'Inversion Thinking', teaching: 'Munger: "Tell me where I\'ll die so I don\'t go there." Instead of reaching the goal, prevent failure. Think reverse.', action: 'Today list 5 failure causes for your goal.', reflectionPrompt: 'Riskiest cause?', proTip: 'Premortem method: "1 year later I failed, why?"' },
  44: { title: 'Mental Subtraction', teaching: 'Stoic technique: what if I lost something? Mental subtraction = trains gratitude muscle. See what you have as valuable again.', action: 'Today mentally experience losing 1 thing you have.', reflectionPrompt: 'Which possession became more valuable?', proTip: '1 min evening: visualize 3 good things that happened today.' },
  45: { title: 'Daily Mind Map', teaching: 'Mind map = brain\'s natural structure. Center + branches instead of linear notes. Make complex ideas coherent in 30 sec.', action: 'Today solve 1 problem with mind map.', reflectionPrompt: 'Did mind map strengthen intuition?', proTip: 'Blank paper + colored pens. Mind-map apps tire.' },
  46: { title: 'Memory Palace', teaching: 'Ancient technique: place what you want to remember in a familiar space. Childhood home = palace. 5 rooms × 5 ideas = remembered for a week.', action: 'Today place 5 ideas in your memory palace.', reflectionPrompt: 'Will you remember tomorrow?', proTip: 'Funny + exaggerated images stick best.' },
  47: { title: 'Spaced Repetition', teaching: 'Spaced repetition = optimum learning. 1 day, 3, 7, 14, 30. Repeating at these intervals = long-term memory. Anki app is gold standard.', action: 'Today briefly review what you learned in last 7 days.', reflectionPrompt: 'Which learning was already forgotten?', proTip: 'Anki 5 min daily = enough for retention.' },
  48: { title: 'Final Sprint', teaching: 'Last 3 days. 50 days transformed your mind from scattered to master. This sprint = lock-in. Tomorrow your essence shifts.', action: 'Today write final-sprint intent.', reflectionPrompt: 'Most-changed mental habit?', proTip: 'Print intent, hang in workspace. 30 days reach point.' },
  49: { title: '49 Days In', teaching: 'In 49 days, single focus, deep work, 80/20, mental models are automatic. New baseline = master brain. List 10 changes.', action: 'Today list 10 mental habits that changed in 49 days.', reflectionPrompt: 'Most unforgettable change?', proTip: 'Write list on a single A4. Pin at desk.' },
  50: { title: 'Master Complete', teaching: '50 days. Most minds scattered. Yours master. Boredom is your friend, deep work your language, mental models your weapons. Discipline = new IQ.', action: 'Today look in mirror. Greet New You.', reflectionPrompt: 'Would 50-days-ago you want to be now?', proTip: 'Rest 7 days, then body or money discipline.' },
};

const QUIZ_TR = {
  31: [{ q: 'Ultradian döngü süresi?', options: ['25 dk', '90-120 dk', '8 saat', 'Sürekli'], correct: 1, explain: 'Beyin 90-120 dk dönerli.' }, { q: 'Mola önerisi?', options: ['5 dk', '20 dk gerçek mola', '0', '1 saat'], correct: 1, explain: '20 dk telefon-ekransız mola.' }],
  32: [{ q: 'DMN aktif olur?', options: ['Stimülasyon', 'Boş zaman', 'Telefon', 'Çalışma'], correct: 1, explain: 'Beyin "boş" = DMN açık.' }, { q: 'Yaratıcılık burada doğar?', options: ['Hayır', 'Evet', 'Etkisiz', 'Bilinmez'], correct: 1, explain: 'DMN = yaratıcılık + öz farkındalık.' }],
  33: [{ q: 'Mental model kaynak?', options: ['Bilinmez', 'Farnam Street', 'Tabloid', 'Sosyal medya'], correct: 1, explain: 'Farnam Street = en iyi kaynak.' }, { q: 'Munger formülü?', options: ['10 model', '100 model', '1000', 'Yok'], correct: 1, explain: '100 mental model = dünyayı çöz.' }],
  34: [{ q: 'Birinci ilkeler kim?', options: ['Naval', 'Musk', 'Buffett', 'Munger'], correct: 1, explain: 'Elon Musk yaklaşımı.' }, { q: 'Niye? sayısı?', options: ['1', '5 üst üste', '100', '0'], correct: 1, explain: '5 niye = köke.' }],
  35: [{ q: 'Yüksek tavan etkisi?', options: ['Detay', 'Yaratıcı düşünce', 'Yorgunluk', 'Ses'], correct: 1, explain: 'Yüksek tavan = yaratıcı.' }, { q: 'Yaratıcı yer?', options: ['Ofis', 'Park/kütüphane', 'Yatak', 'Bilinmez'], correct: 1, explain: 'Yüksek tavan/açık yer.' }],
  36: [{ q: 'Single-task süresi?', options: ['10 dk', '90 dk', '8 saat', 'Yok'], correct: 1, explain: '90 dk tam odak.' }, { q: 'DND mode?', options: ['Etkisiz', 'Telefon+Mac kapat', 'Sadece sus', 'Yok'], correct: 1, explain: 'Tüm cihazlarda.' }],
  37: [{ q: 'Attention residue?', options: ['%5', '%33', '%80', 'Yok'], correct: 1, explain: 'Leroy %33 ölçtü.' }, { q: 'Çözüm?', options: ['Hızlı geç', 'Tam bitir', 'Multitask', 'Yarım bırak'], correct: 1, explain: 'Tam bitir, sonra geç.' }],
  38: [{ q: '4-hour workday kim?', options: ['Sharma', 'Ferriss', 'Newport', 'Clear'], correct: 1, explain: 'Tim Ferriss kavramı.' }, { q: 'Optimum saat?', options: ['18-22', '09-13', '00-04', '12-16'], correct: 1, explain: 'Sabah beyin keskin.' }],
  39: [{ q: 'Sıkıntı toleransı?', options: ['Eski', 'Zihin gücü', 'Yorgunluk', 'Pasif'], correct: 1, explain: 'Tolerans = güç.' }, { q: 'Pratik süresi?', options: ['1 dk', '30 dk', '1 saat', '0'], correct: 1, explain: 'Günde 30 dk.' }],
  40: [{ q: 'Off-ramp süresi?', options: ['1 saat', '15 dk', '1 dk', 'Yok'], correct: 1, explain: '15 dk yeter.' }, { q: 'Off-ramp\'de ne yap?', options: ['Düşün', 'Beden hareketi', 'Çalış', 'Telefon'], correct: 1, explain: 'Beyin arka planda çözer.' }],
  41: [{ q: 'Çerçeve nedir?', options: ['Karar an', 'Pre-decision', 'Sonuç', 'Stres'], correct: 1, explain: 'Önceden karar.' }, { q: 'Avantajı?', options: ['Yorgunluk', 'İrade tasarrufu', 'Daha çok karar', 'Etkisiz'], correct: 1, explain: 'Karar yorgunluğunu azaltır.' }],
  42: [{ q: 'Pareto 80/20?', options: ['Eşit', '%20 input %80 output', 'Tersi', 'Yok'], correct: 1, explain: 'Az çok yapar.' }, { q: '80/20 ne sıklıkta?', options: ['Yok', 'Haftalık', 'Yıllık', 'Asla'], correct: 1, explain: 'Haftalık uygulanır.' }],
  43: [{ q: 'Inversion?', options: ['Hedef', 'Başarısızlığı önle', 'Hız', 'Eski'], correct: 1, explain: 'Tersini düşün.' }, { q: 'Premortem?', options: ['Otopsi', '1 yıl sonra başarısız neden?', 'Tıp', 'Yok'], correct: 1, explain: 'Geleceği şimdiden analiz.' }],
  44: [{ q: 'Mental subtraction?', options: ['Şükran kasi', 'Korku', 'Negatif', 'Yorgunluk'], correct: 0, explain: 'Şükranı çalıştırır.' }, { q: 'Pratik?', options: ['Sahip değilmiş gibi', 'Daha fazla iste', 'Karşılaştır', 'Yok'], correct: 0, explain: 'Kayıp simulate et.' }],
  45: [{ q: 'Mind map yapısı?', options: ['Lineer', 'Merkez+dallar', 'Tablo', 'Yazı'], correct: 1, explain: 'Beynin doğal yapısı.' }, { q: 'En iyi araç?', options: ['App', 'Boş kâğıt+kalem', 'Tablet', 'Yok'], correct: 1, explain: 'Kâğıt = pürüzsüz.' }],
  46: [{ q: 'Hafıza sarayı?', options: ['Modern', 'Antik teknik', 'Pahalı', 'App'], correct: 1, explain: 'Antik klasik.' }, { q: 'Ne tür görsel?', options: ['Ciddi', 'Komik+abartılı', 'Renkli', 'Soyut'], correct: 1, explain: 'Komik kalıcı.' }],
  47: [{ q: 'Spaced repetition aralıkları?', options: ['Hep', '1-3-7-14-30 gün', '1 ay', '1 yıl'], correct: 1, explain: 'Optimum aralık.' }, { q: 'En iyi app?', options: ['Notion', 'Anki', 'Notes', 'Word'], correct: 1, explain: 'Anki altın standart.' }],
  48: [{ q: 'Final sprint?', options: ['1 gün', '3 gün', '1 ay', 'Yok'], correct: 1, explain: 'Son 3 gün lock-in.' }, { q: 'Niyet nereye?', options: ['Bellek', 'Pano', 'Çöp', 'Email'], correct: 1, explain: 'Görünür.' }],
  49: [{ q: 'Yeni baseline?', options: ['Eski', 'Master beyin', 'Yorgun', 'Pasif'], correct: 1, explain: 'Otomatik tekniklere dönüştü.' }, { q: 'Liste yer?', options: ['Bellek', 'A4 + masada', 'Çöp', 'App'], correct: 1, explain: 'Görünür.' }],
  50: [{ q: 'Disiplin = ?', options: ['IQ farkı', 'Yeni IQ', 'Test', 'Hız'], correct: 1, explain: 'Disiplin = yeni IQ.' }, { q: 'Sonraki path?', options: ['Hemen', '7 gün dinlen', 'Asla', '1 ay'], correct: 1, explain: '7 gün dinlen.' }],
};

const QUIZ_EN = {
  31: [{ q: 'Ultradian cycle duration?', options: ['25 min', '90-120 min', '8 hours', 'Always'], correct: 1, explain: 'Brain runs in 90-120 min.' }, { q: 'Break recommendation?', options: ['5 min', '20 min real break', '0', '1 hour'], correct: 1, explain: '20 min phoneless break.' }],
  32: [{ q: 'DMN active when?', options: ['Stimulation', 'Empty time', 'Phone', 'Work'], correct: 1, explain: 'Brain "empty" = DMN on.' }, { q: 'Creativity born here?', options: ['No', 'Yes', 'No effect', 'Unknown'], correct: 1, explain: 'DMN = creativity + self-awareness.' }],
  33: [{ q: 'Mental model source?', options: ['Unknown', 'Farnam Street', 'Tabloid', 'Social media'], correct: 1, explain: 'Best source.' }, { q: 'Munger formula?', options: ['10 models', '100 models', '1000', 'No'], correct: 1, explain: '100 mental models = solve world.' }],
  34: [{ q: 'First principles by?', options: ['Naval', 'Musk', 'Buffett', 'Munger'], correct: 1, explain: 'Elon Musk approach.' }, { q: 'Why? count?', options: ['1', '5 in row', '100', '0'], correct: 1, explain: '5 whys = root.' }],
  35: [{ q: 'High ceiling effect?', options: ['Detail', 'Creative thinking', 'Tired', 'Sound'], correct: 1, explain: 'High = creative.' }, { q: 'Creative spot?', options: ['Office', 'Park/library', 'Bed', 'Unknown'], correct: 1, explain: 'High ceiling/open space.' }],
  36: [{ q: 'Single-task duration?', options: ['10 min', '90 min', '8 hours', 'No'], correct: 1, explain: '90 min full focus.' }, { q: 'DND mode?', options: ['No effect', 'Phone+Mac off', 'Just silent', 'No'], correct: 1, explain: 'All devices.' }],
  37: [{ q: 'Attention residue?', options: ['5%', '33%', '80%', 'None'], correct: 1, explain: 'Leroy measured 33%.' }, { q: 'Solution?', options: ['Switch fast', 'Finish fully', 'Multitask', 'Leave half'], correct: 1, explain: 'Finish then move.' }],
  38: [{ q: '4-hour workday by?', options: ['Sharma', 'Ferriss', 'Newport', 'Clear'], correct: 1, explain: 'Tim Ferriss concept.' }, { q: 'Optimal hours?', options: ['18-22', '09-13', '00-04', '12-16'], correct: 1, explain: 'Morning brain sharp.' }],
  39: [{ q: 'Boredom tolerance?', options: ['Old', 'Mental strength', 'Tired', 'Passive'], correct: 1, explain: 'Tolerance = strength.' }, { q: 'Practice duration?', options: ['1 min', '30 min', '1 hour', '0'], correct: 1, explain: 'Daily 30 min.' }],
  40: [{ q: 'Off-ramp duration?', options: ['1 hour', '15 min', '1 min', 'No'], correct: 1, explain: '15 min suffices.' }, { q: 'During off-ramp do?', options: ['Think', 'Body movement', 'Work', 'Phone'], correct: 1, explain: 'Brain solves in background.' }],
  41: [{ q: 'Framework is?', options: ['Decision moment', 'Pre-decision', 'Result', 'Stress'], correct: 1, explain: 'Decided in advance.' }, { q: 'Advantage?', options: ['Tired', 'Willpower save', 'More decisions', 'No effect'], correct: 1, explain: 'Reduces decision fatigue.' }],
  42: [{ q: 'Pareto 80/20?', options: ['Equal', '20% input 80% output', 'Reverse', 'No'], correct: 1, explain: 'Few do most.' }, { q: '80/20 frequency?', options: ['No', 'Weekly', 'Yearly', 'Never'], correct: 1, explain: 'Weekly applied.' }],
  43: [{ q: 'Inversion?', options: ['Goal', 'Prevent failure', 'Speed', 'Old'], correct: 1, explain: 'Think reverse.' }, { q: 'Premortem?', options: ['Autopsy', '1-year-failed cause?', 'Medicine', 'No'], correct: 1, explain: 'Pre-analyze future.' }],
  44: [{ q: 'Mental subtraction?', options: ['Gratitude muscle', 'Fear', 'Negative', 'Tired'], correct: 0, explain: 'Trains gratitude.' }, { q: 'Practice?', options: ['As if not owning', 'Want more', 'Compare', 'No'], correct: 0, explain: 'Simulate loss.' }],
  45: [{ q: 'Mind map structure?', options: ['Linear', 'Center+branches', 'Table', 'Text'], correct: 1, explain: 'Brain\'s natural structure.' }, { q: 'Best tool?', options: ['App', 'Blank paper+pen', 'Tablet', 'No'], correct: 1, explain: 'Paper = frictionless.' }],
  46: [{ q: 'Memory palace?', options: ['Modern', 'Ancient technique', 'Expensive', 'App'], correct: 1, explain: 'Ancient classic.' }, { q: 'Image type?', options: ['Serious', 'Funny+exaggerated', 'Colored', 'Abstract'], correct: 1, explain: 'Funny sticks.' }],
  47: [{ q: 'Spaced rep intervals?', options: ['Always', '1-3-7-14-30 days', '1 month', '1 year'], correct: 1, explain: 'Optimum spacing.' }, { q: 'Best app?', options: ['Notion', 'Anki', 'Notes', 'Word'], correct: 1, explain: 'Anki gold standard.' }],
  48: [{ q: 'Final sprint?', options: ['1 day', '3 days', '1 month', 'No'], correct: 1, explain: 'Last 3 = lock-in.' }, { q: 'Intent where?', options: ['Memory', 'Pinned/visible', 'Trash', 'Email'], correct: 1, explain: 'Visible.' }],
  49: [{ q: 'New baseline?', options: ['Old', 'Master brain', 'Tired', 'Passive'], correct: 1, explain: 'Techniques became automatic.' }, { q: 'List location?', options: ['Memory', 'A4 at desk', 'Trash', 'App'], correct: 1, explain: 'Visible.' }],
  50: [{ q: 'Discipline = ?', options: ['IQ diff', 'New IQ', 'Test', 'Speed'], correct: 1, explain: 'Discipline = new IQ.' }, { q: 'Next path?', options: ['Now', '7 days rest', 'Never', '1 month'], correct: 1, explain: '7 days rest.' }],
};

function buildLessons(c, q) { const o = {}; for (const [k, v] of Object.entries(c)) o[k] = { ...v, quiz: q[k] || [] }; return o; }
function applyToFile(filePath, pathId, m) { const d = JSON.parse(fs.readFileSync(filePath, 'utf8')); if (!d.lessons[pathId]) d.lessons[pathId] = {}; for (const [k, v] of Object.entries(m)) d.lessons[pathId][k] = { ...(d.lessons[pathId][k] || {}), ...v }; fs.writeFileSync(filePath, JSON.stringify(d, null, 2) + '\n'); }
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.tr.json'), 'mind-discipline', buildLessons(NEW_TR, QUIZ_TR));
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.en.json'), 'mind-discipline', buildLessons(NEW_EN, QUIZ_EN));
console.log(`✓ Mind-discipline 31-50 seeded — ${Object.keys(NEW_TR).length} new lessons × 2 langs`);
