/** Body-discipline lessons 31-50. TR + EN. */
const fs = require('fs');
const path = require('path');

const NEW_TR = {
  31: { title: 'Vagus Sinir', teaching: 'Vagus = beyin-bağırsak otobanı. Tıkalıysa: stres, sindirim sorunu, depresyon. Açma: derin nefes, soğuk, mırıldama, gargara. Günde 5 dakika = sistem reset.', action: 'Bugün 5 dakika gargara veya mırıldama yap.', reflectionPrompt: 'Vagus pratiği nasıl hissettirdi?', proTip: 'Soğuk yüz suyu = vagus stimülasyonu en hızlı.' },
  32: { title: 'NEAT Farkındalığı', teaching: 'NEAT = non-exercise activity thermogenesis. Yürüyüş, ayakta durma, kıpırdama. Yüksek NEAT = günde 500-800 kcal yakıt. Spor olmadan da forma girersin.', action: 'Bugün 5 saat ayakta durmayı dene (oturma yerine).', reflectionPrompt: 'NEAT günün enerjisini değiştirdi mi?', proTip: 'Telefon çağrısında ayakta dur. Toplantıyı yürüyerek yap.' },
  33: { title: 'Güneş Maruziyeti v2', teaching: 'Sabah ilk güneş = melatonin baskılar, ucb sefalin yükseltir. Gün ortası güneş = D vitamini. Akşam güneş = sirkadiyen reset. 3 maruziyet = ideal.', action: 'Bugün sabah + öğle + akşam 5\'er dakika güneş al.', reflectionPrompt: 'Hangi maruziyet en güçlü hissettirdi?', proTip: 'Çıplak ayakla = grounding bonus.' },
  34: { title: 'Uyku Mimarisi', teaching: 'Uyku = REM + N1 + N2 + N3. N3 (derin uyku) = beden onarımı, REM = zihin onarımı. Geç uyumak N3\'ü çalar. Erken yatmak = derin uyku zenginliği.', action: 'Bugün 22:00\'da yat. N3 dolu olsun.', reflectionPrompt: 'Sabah enerjisi farklı mı?', proTip: 'İlk 3 saat N3 zengin. 22-01 = en kıymetli uyku.' },
  35: { title: 'Mobilite 15 Dakika', teaching: '5 dk yetmedi — 15 dk mobilite günde fark yapar. Omuz, kalça, ayak bileği, sırt, boyun. Her gün küçük açıklık = uzun vade büyük fark.', action: 'Bugün 15 dakika tüm vücut mobilite yap.', reflectionPrompt: 'Hangi eklem hissedilir açıldı?', proTip: 'YouTube "15 min mobility" + 7 gün tekrar.' },
  36: { title: 'Günlük Yürüme Mastery', teaching: '10K adım iyi. 12K adım çok daha iyi. 15K = elite. Hareket en doğal ilaç. Kıvrılarak değil, dik + tempolu yürü.', action: 'Bugün 12K adımı vur.', reflectionPrompt: '12K\'da uyku farklı mı?', proTip: 'Toplantıyı yürüyerek yap. Adım sayını 2x.' },
  37: { title: 'Soğuk Mastery', teaching: 'Soğuk duş 2 dk geçtin. Şimdi: ice bath. 1-3 dk, 5-10°C. Norepinefrin %500, depresyon %29 düşer, bağışıklık 10x. Eğitim sonrası = hızlı recovery.', action: 'Bugün ice bath dene (kova soğuk su + buz).', reflectionPrompt: 'Sıcaklık kontrolü hissettiğin baskın duygu?', proTip: 'İlk 30 sn nefesle, sonra rahatla.' },
  38: { title: 'Sıcak Terapi', teaching: 'Sauna 20 dk × 4 hafta = kalp hastalığı %40 düşük (Finland study). Sıcak şok proteini = vücut onarımı. Yoksa: sıcak duş 10 dk + soğuk bitiriş.', action: 'Bugün sıcak duş 10 dk + 30 sn soğuk.', reflectionPrompt: 'Sıcak-soğuk kontrast nasıldı?', proTip: 'Sauna bulamazsan: sıcak banyo 40°C, 15 dk.' },
  39: { title: 'Bilinçli Yeme', teaching: '20 dakika kuralı: beyin tokluk sinyalini 20 dk sonra alır. 20 dakikadan az yeme = aşırı yeme. Çatal yere koy, çiğne, yut, dur.', action: 'Bugün her öğünü 20 dk\'ya yay.', reflectionPrompt: 'Yavaş yemek doygunluğu değiştirdi mi?', proTip: 'Lokmayı 30 kez çiğne. Sindirim 2x kolaylaşır.' },
  40: { title: 'Hidrasyon 3L', teaching: '2L yeterli değil = optimum. 3L = elit hidrasyon. Beden %72 su. 3L = bilişsel performans %30 artar. İdrar açık sarı = doğru.', action: 'Bugün 3L su iç. Kapsayan 1L sabah, 1L öğleden önce, 1L öğleden sonra.', reflectionPrompt: '3L\'de zihinsel netlik?', proTip: '1L şişe + günde 3 kez doldur. Sayma yok.' },
  41: { title: 'Güç Disiplini', teaching: 'Push-up + squat + plank yetmez. Hafta 3 gün ağırlık antrenmanı = kas + kemik + hormon. Ev = direnç bandı + kettlebell. Spor salonu = optimum.', action: 'Bugün 30 dk ağırlık antrenmanı yap.', reflectionPrompt: 'Ağırlıkla bedenin nasıl tepki verdi?', proTip: '5x5 sistemi: 5 hareket × 5 set × 5 tekrar. Basit + güçlü.' },
  42: { title: 'Postür Mastery', teaching: '2 dk postür hatırlatıcısı yetmez — sürekli farkındalık. Saat başı + her oturuş + her telefon. Postür = solunum + kortizol + kas dengesi.', action: 'Bugün her saat başı 1 dk postür kontrolü.', reflectionPrompt: 'Akşam sırt ağrısı azaldı mı?', proTip: 'Telefonu göz hizasında. Boyun bükümü = günde 30 dk ekstra ağrı.' },
  43: { title: 'Uyku Sınırı', teaching: 'Az uyu, sınırlı uyu = derin uyku zenginleşir. 7 saat hedefli yat. 9 saat erteleme. Uykusuzluk = beden alarm.', action: 'Bugün 7 saat tam uyumayı dene.', reflectionPrompt: '7 saat 8 saatle aynı hissetti mi?', proTip: '7 saat tam = 8 saat parçalı\'dan iyi.' },
  44: { title: 'Direnç Antrenman Planı', teaching: 'Pazartesi: göğüs+omuz. Çarşamba: bacak. Cuma: sırt+kol. 3 gün × 30 dk = haftalık optimum. Cumartesi-pazar: aktif dinlenme.', action: 'Bugün 3 günlük antrenman planı yaz.', reflectionPrompt: 'Plan motivasyonu artırdı mı?', proTip: 'Antrenman uygulaması: Strong (iOS) = ücretsiz tracking.' },
  45: { title: 'Recovery Mastery', teaching: 'Antrenman = yıkım. Recovery = inşa. Az recovery = ilerleme yok. Foam roller + 8 saat uyku + protein + masaj. Cumartesi yoga, pazar dinlenme.', action: 'Bugün 30 dk dedicated recovery.', reflectionPrompt: 'Recovery sonrası enerji?', proTip: 'Theragun veya foam roller = haftada 3 kez.' },
  46: { title: 'Atletik Kimlik', teaching: '"Spor yapıyorum" = davranış. "Atletim" = kimlik. Sürdürülebilir disiplin kimlik gerektirir. 30 günde "atlet kimliği"ne dönüşür.', action: 'Bugün kendine atlet kimliği koy.', reflectionPrompt: 'Atlet kimliği davranışını nasıl değiştirdi?', proTip: 'Aynaya bak: "Ben atletim. Bedenime saygı duyuyorum."' },
  47: { title: 'Antrenman Sıklığı', teaching: 'Hafta 3 = başlangıç. Hafta 4 = optimum. Hafta 5+ = aşırı, recovery düşer. 3-4 hafta + 1 dinlenme haftası döngüsü = uzun vade.', action: 'Bugün haftalık antrenman planını gözden geçir, 4 günü geç değil.', reflectionPrompt: 'Recovery zamanın yeterli mi?', proTip: 'Her 4 hafta 1 deload (kolay) hafta. Uzun vade ilerleme.' },
  48: { title: 'Final Sprint', teaching: 'Son 3 gün. 50 günde beden zayıftan dirençliye. Bu sprint = kimlik mührü. Yarın bedeninin patronu sensin.', action: 'Bugün son sprintin niyetini yaz.', reflectionPrompt: 'En değişen fiziksel alışkanlık?', proTip: 'Ayna fotoğraf çek. 50 gün önceki ile karşılaştır.' },
  49: { title: '49 Gün İçinde', teaching: '49 günde beden başkası. Hareket otomatik, soğuk dost, uyku zengin, postür dik. Yeni baseline. 10 değişiklik listele.', action: 'Bugün 49 günde değişen 10 fiziksel alışkanlığı yaz.', reflectionPrompt: 'En unutulmaz fiziksel değişim?', proTip: 'Önce-sonra fotoğraf. Hatırlatma sıkıntı anında.' },
  50: { title: 'Master Tamamlandı', teaching: '50 gün. Bedenin disiplinin = kimlikin. Hareket, uyku, beslenme, soğuk, mobilite — hepsi otomatik. Bedenin patronu sen.', action: 'Bugün aynaya bak. Yeni Sen\'i selamla.', reflectionPrompt: '50 gün önceki sen şimdi olmak ister miydi?', proTip: '7 gün dinlen, sonra money veya başka path.' },
};

const NEW_EN = {
  31: { title: 'Vagus Nerve', teaching: 'Vagus = brain-gut highway. Blocked: stress, digestion problems, depression. Open: deep breath, cold, humming, gargling. 5 min daily = system reset.', action: 'Today gargle or hum for 5 min.', reflectionPrompt: 'How did vagus practice feel?', proTip: 'Cold face wash = fastest vagus stimulation.' },
  32: { title: 'NEAT Awareness', teaching: 'NEAT = non-exercise activity thermogenesis. Walk, stand, fidget. High NEAT = 500-800 kcal/day burned. Get fit without exercise.', action: 'Today try standing 5 hours (vs sitting).', reflectionPrompt: 'Did NEAT change daily energy?', proTip: 'Stand on phone calls. Walking meetings.' },
  33: { title: 'Sun Exposure v2', teaching: 'Morning sun = suppresses melatonin, raises wakefulness. Midday = vitamin D. Evening = circadian reset. 3 exposures = ideal.', action: 'Today 5 min sun morning + noon + evening.', reflectionPrompt: 'Which exposure felt strongest?', proTip: 'Barefoot = grounding bonus.' },
  34: { title: 'Sleep Architecture', teaching: 'Sleep = REM + N1 + N2 + N3. N3 (deep) = body repair, REM = mind repair. Late sleep steals N3. Early bed = deep-sleep rich.', action: 'Today sleep at 22:00. N3 abundant.', reflectionPrompt: 'Morning energy different?', proTip: 'First 3 hours rich in N3. 22-01 = most precious sleep.' },
  35: { title: 'Mobility 15 Min', teaching: '5 min wasn\'t enough — 15 min mobility daily makes a difference. Shoulder, hip, ankle, back, neck. Small openness daily = big long-term.', action: 'Today 15 min full-body mobility.', reflectionPrompt: 'Which joint felt unlocked?', proTip: 'YouTube "15 min mobility" + repeat 7 days.' },
  36: { title: 'Daily Walking Mastery', teaching: '10K steps good. 12K much better. 15K = elite. Movement is most natural medicine. Don\'t slouch — upright + brisk.', action: 'Today hit 12K steps.', reflectionPrompt: 'Sleep different at 12K?', proTip: 'Walking meetings. Double your steps.' },
  37: { title: 'Cold Mastery', teaching: 'Cold shower 2-min done. Now: ice bath. 1-3 min, 5-10°C. Norepinephrine +500%, depression -29%, immunity 10x. Post-training = quick recovery.', action: 'Today try ice bath (bucket cold + ice).', reflectionPrompt: 'Dominant feeling at temp control?', proTip: 'First 30 sec breath, then relax.' },
  38: { title: 'Heat Therapy', teaching: 'Sauna 20 min × 4 weeks = -40% heart disease (Finland study). Heat shock proteins = body repair. Else: hot shower 10 min + cold finish.', action: 'Today hot shower 10 min + 30 sec cold.', reflectionPrompt: 'How was hot-cold contrast?', proTip: 'No sauna? Hot bath 40°C, 15 min.' },
  39: { title: 'Mindful Eating', teaching: '20-min rule: brain gets satiety signal after 20 min. Eating less than 20 min = overeating. Fork down, chew, swallow, pause.', action: 'Today extend each meal to 20 min.', reflectionPrompt: 'Did slow eating change satiety?', proTip: 'Chew bite 30 times. Digestion 2x easier.' },
  40: { title: 'Hydration 3L', teaching: '2L sufficient = 3L optimum. Body 72% water. 3L = +30% cognitive performance. Light yellow urine = correct.', action: 'Today drink 3L water. 1L morning, 1L pre-noon, 1L afternoon.', reflectionPrompt: 'Mental clarity at 3L?', proTip: '1L bottle + fill 3x. No counting.' },
  41: { title: 'Strength Discipline', teaching: 'Push-up + squat + plank not enough. 3 days/week weight training = muscle + bone + hormones. Home = resistance band + kettlebell. Gym = optimum.', action: 'Today do 30 min weight training.', reflectionPrompt: 'How did body respond to weights?', proTip: '5x5 system: 5 moves × 5 sets × 5 reps. Simple + strong.' },
  42: { title: 'Posture Mastery', teaching: '2-min posture reminder isn\'t enough — constant awareness. Hourly + every sit + every phone. Posture = breath + cortisol + muscle balance.', action: 'Today 1 min posture check every hour.', reflectionPrompt: 'Less back pain in evening?', proTip: 'Phone at eye level. Neck bend = +30 min daily pain.' },
  43: { title: 'Sleep Restriction', teaching: 'Less sleep, restricted sleep = deep sleep enriched. Target 7 hours. Push 9. Sleeplessness = body alarm.', action: 'Today try sleeping exactly 7 hours.', reflectionPrompt: 'Did 7h feel like 8h?', proTip: 'Solid 7h > fragmented 8h.' },
  44: { title: 'Resistance Training Plan', teaching: 'Monday: chest+shoulder. Wednesday: legs. Friday: back+arm. 3 days × 30 min = optimum weekly. Saturday-Sunday: active rest.', action: 'Today write a 3-day training plan.', reflectionPrompt: 'Did plan boost motivation?', proTip: 'Tracking app: Strong (iOS) = free.' },
  45: { title: 'Recovery Mastery', teaching: 'Training = breakdown. Recovery = build. Less recovery = no progress. Foam roller + 8h sleep + protein + massage. Sat yoga, Sun rest.', action: 'Today 30 min dedicated recovery.', reflectionPrompt: 'Energy after recovery?', proTip: 'Theragun or foam roller = 3x weekly.' },
  46: { title: 'Athletic Identity', teaching: '"I exercise" = behavior. "I am an athlete" = identity. Sustainable discipline requires identity. 30 days transforms into "athlete identity."', action: 'Today claim athlete identity.', reflectionPrompt: 'How did athlete identity change behavior?', proTip: 'Mirror: "I am an athlete. I respect my body."' },
  47: { title: 'Training Frequency', teaching: 'Week 3 = beginner. Week 4 = optimum. Week 5+ = excessive, recovery drops. 3-4 weeks + 1 rest week cycle = long-term.', action: 'Today review weekly plan, don\'t exceed 4 days.', reflectionPrompt: 'Is your recovery time enough?', proTip: 'Every 4 weeks 1 deload (easy) week. Long-term progress.' },
  48: { title: 'Final Sprint', teaching: 'Last 3 days. 50 days transformed body weak to resilient. This sprint = identity stamp. Tomorrow you are body\'s boss.', action: 'Today write final-sprint intent.', reflectionPrompt: 'Most-changed physical habit?', proTip: 'Take mirror photo. Compare with 50-days-ago.' },
  49: { title: '49 Days In', teaching: 'In 49 days body is different. Movement automatic, cold a friend, sleep rich, posture upright. New baseline. List 10 changes.', action: 'Today list 10 physical habits that changed in 49 days.', reflectionPrompt: 'Most unforgettable physical change?', proTip: 'Before-after photo. Reminder during slumps.' },
  50: { title: 'Master Complete', teaching: '50 days. Your body discipline = identity. Movement, sleep, nutrition, cold, mobility — all automatic. You are body\'s boss.', action: 'Today look in mirror. Greet New You.', reflectionPrompt: 'Would 50-days-ago you want to be now?', proTip: 'Rest 7 days, then money or other path.' },
};

const QUIZ_TR = {
  31: [{ q: 'Vagus ne bağlar?', options: ['Beyin-böbrek', 'Beyin-bağırsak', 'Kalp-kas', 'Yok'], correct: 1, explain: 'Beyin-bağırsak otobanı.' }, { q: 'Açma yöntemi?', options: ['Stres', 'Mırıldama/gargara/soğuk', 'Spor', 'Uyku'], correct: 1, explain: 'Vagus stimülasyon teknikleri.' }],
  32: [{ q: 'NEAT açılım?', options: ['Egzersiz', 'Non-exercise activity', 'Diyet', 'Uyku'], correct: 1, explain: 'Egzersiz dışı aktivite ısı üretimi.' }, { q: 'Yüksek NEAT günde?', options: ['100 kcal', '500-800 kcal', '5000', '0'], correct: 1, explain: '500-800 kcal yakım.' }],
  33: [{ q: 'Sabah güneşi etkisi?', options: ['Melatonin yükselir', 'Melatonin düşer', 'Etkisiz', 'Stres'], correct: 1, explain: 'Uyanıklık sefalin yükselir.' }, { q: 'Optimum maruziyet sayısı?', options: ['1', '3 (sabah/öğle/akşam)', '10', '0'], correct: 1, explain: '3 maruziyet ideal.' }],
  34: [{ q: 'Derin uyku evresi?', options: ['REM', 'N3', 'N1', 'Uyanıklık'], correct: 1, explain: 'N3 = derin onarım.' }, { q: 'En kıymetli uyku saatleri?', options: ['00-04', '22-01', '04-07', 'Eşit'], correct: 1, explain: 'İlk 3 saat N3 zengin.' }],
  35: [{ q: 'Mobilite yeni süre?', options: ['1 dk', '15 dk', '1 saat', '0'], correct: 1, explain: '15 dk fark yapar.' }, { q: 'Hangi eklemler?', options: ['Sadece omuz', 'Tüm vücut', 'Bilek', 'Diz'], correct: 1, explain: 'Omuz/kalça/ayak bileği/sırt/boyun.' }],
  36: [{ q: 'Optimum adım?', options: ['5K', '12K iyi-15K elit', '50K', '1K'], correct: 1, explain: '12K iyi, 15K elite.' }, { q: 'Yürüme şekli?', options: ['Eğri', 'Dik+tempolu', 'Yavaş', 'Random'], correct: 1, explain: 'Postür önemli.' }],
  37: [{ q: 'Ice bath süre?', options: ['10 sn', '1-3 dk', '1 saat', 'Yok'], correct: 1, explain: '1-3 dakika.' }, { q: 'Ice bath sıcaklık?', options: ['20°C', '5-10°C', '0°C', '15°C'], correct: 1, explain: '5-10°C.' }],
  38: [{ q: 'Sauna kaç dakika?', options: ['5 dk', '20 dk', '60 dk', '1 dk'], correct: 1, explain: '20 dk × 4 hafta.' }, { q: 'Yedek?', options: ['Yok', 'Sıcak duş + soğuk bitiriş', 'Soğuk', 'Uyku'], correct: 1, explain: 'Sıcak-soğuk kontrast.' }],
  39: [{ q: '20-dakika kuralı?', options: ['Hızlı ye', 'Tokluk sinyali 20 dk sonra', 'Etkisiz', 'Yok'], correct: 1, explain: 'Beyin sinyali geç gelir.' }, { q: 'Çiğneme önerisi?', options: ['1', '30 kez', '5 kez', 'Sayma'], correct: 1, explain: '30 kez çiğne.' }],
  40: [{ q: 'Optimum hidrasyon?', options: ['1L', '3L', '10L', '500ml'], correct: 1, explain: '3L = optimum.' }, { q: 'İdrar rengi kontrol?', options: ['Koyu sarı', 'Açık sarı = doğru', 'Kırmızı', 'Renk yok'], correct: 1, explain: 'Açık sarı doğru.' }],
  41: [{ q: '5x5 sistem?', options: ['5 hareket', '5 hareket × 5 set × 5 tekrar', '5 saat', '5 gün'], correct: 1, explain: 'Klasik temel.' }, { q: 'Haftalık antrenman?', options: ['7 gün', '3 gün', '0', '14 gün'], correct: 1, explain: '3 gün optimum.' }],
  42: [{ q: 'Postür kontrolü ne sıklıkta?', options: ['Yıllık', 'Saat başı', 'Hiç', 'Aylık'], correct: 1, explain: 'Sürekli farkındalık.' }, { q: 'Telefon yüksekliği?', options: ['Aşağı', 'Göz hizası', 'Eşit', 'Yan'], correct: 1, explain: 'Boyun bükümü engellenir.' }],
  43: [{ q: 'Hedef uyku?', options: ['9 saat', '7 saat tam', '4 saat', '12 saat'], correct: 1, explain: '7 saat hedefi.' }, { q: '7 saat tam vs 8 parça?', options: ['8 iyi', '7 tam iyi', 'Aynı', 'Bilinmez'], correct: 1, explain: 'Tam > parçalı.' }],
  44: [{ q: 'Plan yapısı?', options: ['Random', 'Pzt-Çar-Cum 3 gün', 'Hep', 'Yok'], correct: 1, explain: '3 gün bölünmüş.' }, { q: 'Tracking app?', options: ['Yok', 'Strong (iOS)', 'Notion', 'Email'], correct: 1, explain: 'Strong ücretsiz.' }],
  45: [{ q: 'Recovery şart mı?', options: ['Hayır', 'Evet, ilerleme şartı', 'Lüks', 'Pasif'], correct: 1, explain: 'Az recovery = ilerleme yok.' }, { q: 'Foam roller sıklık?', options: ['Yok', '3x hafta', 'Yıllık', 'Asla'], correct: 1, explain: 'Haftada 3 kez.' }],
  46: [{ q: 'Davranış mı kimlik mi?', options: ['Davranış', 'Kimlik kalıcı', 'Aynı', 'Bilinmez'], correct: 1, explain: 'Kimlik > davranış.' }, { q: 'Pekiştirme?', options: ['Düşün', 'Aynaya söyle', 'Yaz', 'Unut'], correct: 1, explain: 'Aynaya günlük tekrar.' }],
  47: [{ q: 'Optimum hafta?', options: ['7', '3-4', '14', '1'], correct: 1, explain: '3-4 hafta + deload.' }, { q: 'Deload?', options: ['Yok', 'Her 4 hafta kolay 1 hafta', 'Hep', 'Asla'], correct: 1, explain: 'Recovery döngüsü.' }],
  48: [{ q: 'Final sprint?', options: ['1 gün', '3 gün', '1 ay', 'Yok'], correct: 1, explain: 'Son 3 gün.' }, { q: 'Görsel kanıt?', options: ['Yok', 'Ayna fotoğraf', 'Email', 'Hafıza'], correct: 1, explain: 'Önce-sonra karşılaştır.' }],
  49: [{ q: 'Yeni baseline?', options: ['Eski', 'Otomatik beden disiplini', 'Yorgun', 'Pasif'], correct: 1, explain: 'Otomatik master.' }, { q: 'Önce-sonra foto?', options: ['Etkisiz', 'Slump anı hatırlatma', 'Risk', 'Pahalı'], correct: 1, explain: 'Geri dönüş anı kanıt.' }],
  50: [{ q: 'Bedenin patronu?', options: ['Genler', 'Sen', 'Doktor', 'Şans'], correct: 1, explain: '50 gün sonrası: sen.' }, { q: 'Sonraki path?', options: ['Hemen', '7 gün dinlen', 'Asla', '1 ay'], correct: 1, explain: '7 gün dinlen.' }],
};

const QUIZ_EN = {
  31: [{ q: 'Vagus connects?', options: ['Brain-kidney', 'Brain-gut', 'Heart-muscle', 'No'], correct: 1, explain: 'Brain-gut highway.' }, { q: 'Activation method?', options: ['Stress', 'Hum/gargle/cold', 'Sport', 'Sleep'], correct: 1, explain: 'Vagus stimulation techniques.' }],
  32: [{ q: 'NEAT acronym?', options: ['Exercise', 'Non-exercise activity', 'Diet', 'Sleep'], correct: 1, explain: 'Non-exercise activity thermogenesis.' }, { q: 'High NEAT daily burn?', options: ['100 kcal', '500-800 kcal', '5000', '0'], correct: 1, explain: '500-800 kcal burned.' }],
  33: [{ q: 'Morning sun effect?', options: ['Melatonin up', 'Melatonin down', 'No effect', 'Stress'], correct: 1, explain: 'Wakefulness hormone rises.' }, { q: 'Optimal exposure count?', options: ['1', '3 (morn/noon/eve)', '10', '0'], correct: 1, explain: '3 exposures ideal.' }],
  34: [{ q: 'Deep sleep stage?', options: ['REM', 'N3', 'N1', 'Wake'], correct: 1, explain: 'N3 = deep repair.' }, { q: 'Most precious hours?', options: ['00-04', '22-01', '04-07', 'Equal'], correct: 1, explain: 'First 3 hours rich in N3.' }],
  35: [{ q: 'New mobility duration?', options: ['1 min', '15 min', '1 hour', '0'], correct: 1, explain: '15 min makes a difference.' }, { q: 'Which joints?', options: ['Just shoulder', 'Whole body', 'Wrist', 'Knee'], correct: 1, explain: 'Shoulder/hip/ankle/back/neck.' }],
  36: [{ q: 'Optimum steps?', options: ['5K', '12K good - 15K elite', '50K', '1K'], correct: 1, explain: '12K good, 15K elite.' }, { q: 'Walking style?', options: ['Slouched', 'Upright + brisk', 'Slow', 'Random'], correct: 1, explain: 'Posture matters.' }],
  37: [{ q: 'Ice bath duration?', options: ['10 sec', '1-3 min', '1 hour', 'No'], correct: 1, explain: '1-3 minutes.' }, { q: 'Ice bath temp?', options: ['20°C', '5-10°C', '0°C', '15°C'], correct: 1, explain: '5-10°C.' }],
  38: [{ q: 'Sauna minutes?', options: ['5 min', '20 min', '60 min', '1 min'], correct: 1, explain: '20 min × 4 weeks.' }, { q: 'Backup?', options: ['No', 'Hot shower + cold finish', 'Cold', 'Sleep'], correct: 1, explain: 'Hot-cold contrast.' }],
  39: [{ q: '20-min rule?', options: ['Eat fast', 'Satiety signal after 20 min', 'No effect', 'No'], correct: 1, explain: 'Brain signal arrives late.' }, { q: 'Chew recommendation?', options: ['1', '30 times', '5 times', 'No count'], correct: 1, explain: 'Chew 30 times.' }],
  40: [{ q: 'Optimum hydration?', options: ['1L', '3L', '10L', '500ml'], correct: 1, explain: '3L = optimum.' }, { q: 'Urine color check?', options: ['Dark yellow', 'Light yellow = correct', 'Red', 'No color'], correct: 1, explain: 'Light yellow correct.' }],
  41: [{ q: '5x5 system?', options: ['5 moves', '5 moves × 5 sets × 5 reps', '5 hours', '5 days'], correct: 1, explain: 'Classic foundation.' }, { q: 'Weekly training?', options: ['7 days', '3 days', '0', '14 days'], correct: 1, explain: '3 days optimum.' }],
  42: [{ q: 'Posture check frequency?', options: ['Yearly', 'Hourly', 'Never', 'Monthly'], correct: 1, explain: 'Constant awareness.' }, { q: 'Phone height?', options: ['Down', 'Eye level', 'Equal', 'Side'], correct: 1, explain: 'Prevents neck bend.' }],
  43: [{ q: 'Sleep target?', options: ['9 hours', '7 hours full', '4 hours', '12 hours'], correct: 1, explain: '7 hours target.' }, { q: '7 full vs 8 fragmented?', options: ['8 better', '7 full better', 'Same', 'Unknown'], correct: 1, explain: 'Solid > fragmented.' }],
  44: [{ q: 'Plan structure?', options: ['Random', 'Mon-Wed-Fri 3 days', 'All days', 'No'], correct: 1, explain: '3-day split.' }, { q: 'Tracking app?', options: ['No', 'Strong (iOS)', 'Notion', 'Email'], correct: 1, explain: 'Strong free.' }],
  45: [{ q: 'Recovery essential?', options: ['No', 'Yes, progress required', 'Luxury', 'Passive'], correct: 1, explain: 'Less recovery = no progress.' }, { q: 'Foam roller frequency?', options: ['No', '3x weekly', 'Yearly', 'Never'], correct: 1, explain: '3x weekly.' }],
  46: [{ q: 'Behavior or identity?', options: ['Behavior', 'Identity permanent', 'Same', 'Unknown'], correct: 1, explain: 'Identity > behavior.' }, { q: 'Solidify how?', options: ['Think', 'Mirror speak', 'Write', 'Forget'], correct: 1, explain: 'Daily mirror repeat.' }],
  47: [{ q: 'Optimum weeks?', options: ['7', '3-4', '14', '1'], correct: 1, explain: '3-4 weeks + deload.' }, { q: 'Deload?', options: ['No', 'Every 4 weeks easy week', 'Always', 'Never'], correct: 1, explain: 'Recovery cycle.' }],
  48: [{ q: 'Final sprint?', options: ['1 day', '3 days', '1 month', 'No'], correct: 1, explain: 'Last 3 days.' }, { q: 'Visual proof?', options: ['No', 'Mirror photo', 'Email', 'Memory'], correct: 1, explain: 'Before-after compare.' }],
  49: [{ q: 'New baseline?', options: ['Old', 'Automatic body discipline', 'Tired', 'Passive'], correct: 1, explain: 'Automatic master.' }, { q: 'Before-after photo?', options: ['No effect', 'Slump moment reminder', 'Risk', 'Expensive'], correct: 1, explain: 'Backslide moment proof.' }],
  50: [{ q: 'Body\'s boss?', options: ['Genes', 'You', 'Doctor', 'Luck'], correct: 1, explain: 'After 50 days: you.' }, { q: 'Next path?', options: ['Now', '7 days rest', 'Never', '1 month'], correct: 1, explain: '7 days rest.' }],
};

function buildLessons(c, q) { const o = {}; for (const [k, v] of Object.entries(c)) o[k] = { ...v, quiz: q[k] || [] }; return o; }
function applyToFile(filePath, pathId, m) { const d = JSON.parse(fs.readFileSync(filePath, 'utf8')); if (!d.lessons[pathId]) d.lessons[pathId] = {}; for (const [k, v] of Object.entries(m)) d.lessons[pathId][k] = { ...(d.lessons[pathId][k] || {}), ...v }; fs.writeFileSync(filePath, JSON.stringify(d, null, 2) + '\n'); }
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.tr.json'), 'body-discipline', buildLessons(NEW_TR, QUIZ_TR));
applyToFile(path.join(__dirname, '..', 'src', 'i18n', 'locales', 'lessons.en.json'), 'body-discipline', buildLessons(NEW_EN, QUIZ_EN));
console.log(`✓ Body-discipline 31-50 seeded — ${Object.keys(NEW_TR).length} new lessons × 2 langs`);
